across-protocol/relayer

- src/dataworker/Dataworker.ts
fixes broken build due to bad stub.
> fix: address broken stub

- cloudbuild.yml
Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>
> CI: Update container tag

- src/clients/ConfigStoreClient.ts
- src/clients/SpokePoolClient.ts
- src/clients/index.ts
- test/ConfigStoreClient.ts
- test/Relayer.IterativeFill.ts
- test/fixtures/Dataworker.Fixture.ts
- test/utils/utils.ts
This PR only changes file names, no code changes
> improve: Rename RateModelClient => AcrossConfigStoreClient

- src/clients/SpokePoolClient.ts
- src/dataworker/Dataworker.ts
- src/dataworker/index.ts
- src/interfaces/SpokePool.ts
- test/Dataworker.loadData.ts
- Fixes one minor bug where we're reading the wrong `max` config variable in the Dataworker
- removes a very noisy log 
- changes filter in `_loadData` for `deposits` to compare against the ORIGIN chain block range instead of the DESTINATION chain block range
> fix: Various bugs in Dataworker

- package.json
- src/utils/TransactionUtils.ts
- yarn.lock
> fix: lock file

- src/utils/TransactionUtils.ts
- src/utils/index.ts
Polygon gas estimator has issues sometimes with bad gas estimations. This PR refines this by using an API with gas station network to avoid the poor pricing.
> fix: address issue with polygon gas estimator

- package.json
- src/clients/HubPoolClient.ts
- src/clients/SpokePoolClient.ts
- src/common/ClientHelper.ts
- src/dataworker/Dataworker.ts
- src/dataworker/DataworkerUtils.ts
- src/dataworker/DepositUtils.ts
- src/dataworker/FillUtils.ts
- src/dataworker/PoolRebalanceUtils.ts
- src/finalizer/index.ts
- src/interfaces/SpokePool.ts
- src/relayer/RelayerClientHelper.ts
- src/scripts/validateRootBundle.ts
- src/utils/ObjectUtils.ts
- test/Dataworker.buildRoots.ts
- test/Dataworker.proposeRootBundle.ts
- test/Dataworker.validateRootBundle.ts
- test/HubPoolClient.RootBundleEvents.ts
- yarn.lock
This PR is created mostly to start a discussion around how we want to organize the L2 finalizer code, but also to play with the `@arbitrum/sdk` module which we'll need to use and replace the soon to be deprecated `arb-ts` module.
> feat: Add demo for finalizer script

- src/clients/MonitorClientHelper.ts
- src/monitor/Monitor.ts
- src/monitor/MonitorConfig.ts
- src/monitor/RootBundleProcessor.ts
- src/monitor/index.ts
There were a number of issues preventing the monitor from running correctly. This PR addresses these.
> fix: Address multiple run issues in monitor

- .prettierignore
- src/clients/HubPoolClient.ts
- src/clients/MultiCallerClient.ts
- src/clients/SpokePoolClient.ts
- src/dataworker/Dataworker.ts
- src/dataworker/index.ts
- src/interfaces/Common.ts
- src/interfaces/SpokePool.ts
- src/utils/EventUtils.ts
- test/Dataworker.executePoolRebalances.ts
- test/Dataworker.executeRelayerRefunds.ts
- test/Dataworker.executeSlowRelay.ts
- test/utils/utils.ts
This PR includes execution logic and simple lifecycle tests for pool rebalance leaves, relayer refund leaves, and slow relay leaves.
> feat: add pool rebalance and relayer refund leaf execution

- src/clients/SpokePoolClient.ts
- src/clients/TokenClient.ts
- src/relayer/Relayer.ts
- test/Relayer.SlowFill.ts
- test/Relayer.UnfilledDeposits.ts
The relayer needs the ability to send 0 sized fills if a relay is not totally fillable. This PR adds the logic to do this.
> feat: add slow relay logic

- src/clients/SpokePoolClient.ts
- src/common/ClientHelper.ts
- src/dataworker/Dataworker.ts
- src/utils/EventUtils.ts
add better concurrency settings
> fix: concurrency

- package.json
- yarn.lock
> fix: migrate to new contracts

- src/clients/TokenClient.ts
> fix optimism approval

- src/relayer/Relayer.ts
Percentages need to be scaled by 100.
> fix: formatting of percentages

- index.ts
- src/clients/HubPoolClient.ts
- src/clients/MultiCallerClient.ts
- src/dataworker/Dataworker.ts
- src/finalizer/index.ts
- src/monitor/Monitor.ts
- src/monitor/RelayerProcessor.ts
- src/monitor/RootBundleProcessor.ts
- src/relayer/Relayer.ts
- src/utils/ExecutionUtils.ts
- src/utils/TransactionUtils.ts
- fix: formatting of percentages
- wip
- wip
> address monitor and alerting issues

- src/monitor/Monitor.ts
> fix monitor issue

- index.ts
- package.json
- src/clients/MultiCallerClient.ts
- src/common/Config.ts
- src/dataworker/Dataworker.ts
- src/dataworker/DataworkerConfig.ts
- src/dataworker/PoolRebalanceUtils.ts
- src/finalizer/FinalizerConfig.ts
- src/finalizer/index.ts
- src/finalizer/utils/arbitrum.ts
- src/finalizer/utils/index.ts
- src/finalizer/utils/optimism.ts
- src/finalizer/utils/polygon.ts
- src/utils/TransactionUtils.ts
- src/utils/index.ts
- test/Dataworker.validateRootBundle.ts
- yarn.lock
This is still just a script that can be run with `ts-node ./src/finalizer/index.ts --wallet mnemonic` which is janky and manual for now but its confirmed to work with polygon and at least prints out transaction hashes for arbitrum
> feat: Polygon finalizer

- scripts/sendTokens.ts
- scripts/utils.ts
Simple script used when sending tokens. useful when using GCKMS.
> feat: useful token send script

- scripts/sendTokens.ts
- src/clients/ConfigStoreClient.ts
- src/clients/HubPoolClient.ts
- src/clients/TokenClient.ts
- src/dataworker/index.ts
- src/finalizer/FinalizerClientHelper.ts
- src/finalizer/index.ts
- src/finalizer/utils/arbitrum.ts
- src/finalizer/utils/optimism.ts
- src/finalizer/utils/polygon.ts
Follow up PR to add lifecyle/unit tests
> improve: Refactor finalizer

- src/clients/SpokePoolClient.ts
- src/dataworker/Dataworker.ts
Exit for loops early. Anecdotally speeds up loadData 50x
> improve: optimize spokePoolClient

- src/finalizer/utils/optimism.ts
Avoid this situation. The bottom two txn hashes all originated from the same L2 transaction, which was a batch call that created three different withdrawal messages. So we need to map the L1 withdrawal message to the correct L2 token that was withdrawn, even though they were all in the same L2 batch txn
> fix: Map withdrawal message to L2 transaction better

- test/Dataworker.buildRoots.ts
Unit tests for feature added in #114
﻿Signed-off-by: nicholaspai <npai.nyc@gmail.com>
> improve: Add unit test for pool rebalance leaf construction with refunds for some but not all L1 tokens

- .github/workflows/test.yml
- src/scripts/validateRootBundle.ts
This PR is mainly to prevent cases where `test` action in CI succeeds but `build` fails in GCP because compiling fails in untested `ts` files like `scripts/*`
> feat: add tsc -b to github ci

- src/clients/InventoryClient/InventoryClient.ts
> fix inventory for undefined config

- src/monitor/Monitor.ts
Changes in monitoring report:
1. Add a "[Summary]" section at the end of the balance report that prints a single balance number for each token on all chains. For example:
[Summary]
WETH: 4,725.89
USDC: 5,573,559.85
WBTC: 41.82
UMA: 27,183.31
DAI: 1,524,912.04
BOBA: 502,143.71
BADGER: 17,754.88
2. Shorten 0 balances. For example:
Optimism: 59,855.72, 0.000, 0.000, 59,855.72 => Optimism: 59,855.72, 0, 0, 59,855.72
3. Just print 0 when all balances are 0. For example:
Optimism: 0.000, 0.000, 0.000, 0.000 => Optimism: 0
> improve: Relayer reporting - Add all chains summary and print 0 when balances are 0

- scripts/unwrapWeth.ts
- src/utils/index.ts
Convenience script to unwrap weth from gckms account
> feat: Add unwrap weth script

- src/clients/BundleDataClient.ts
- src/clients/InventoryClient/InventoryClient.ts
- src/dataworker/DataworkerClientHelper.ts
- src/monitor/Monitor.ts
- src/monitor/MonitorClientHelper.ts
- src/relayer/RelayerClientHelper.ts
- test/InventoryClient.InventoryRebalance.ts
- test/InventoryClient.RefundChain.ts
- test/Monitor.ts
- test/fixtures/Dataworker.Fixture.ts
- test/mocks/MockBundleDataClient.ts
- test/mocks/MockInventoryClient.ts
- test/mocks/index.ts
Context: When deciding which chain to get refunded on when filling a deposit, we need to consider the refunds from pending and next bundles for both the destination chain and L1.
> feat: Consider refunds from pending and next bundles in inventory management

- src/monitor/Monitor.ts
- src/monitor/MonitorConfig.ts
- src/monitor/index.ts
This adds a simple balance monitoring module to the across monitor bot to send an error if the balance drops below a threshold.
> feat: add balance monitor

- src/clients/BundleDataClient.ts
Problem: HubPoolClient#getNextBundleStartBlockNumber returns the starting block of the next bundle if the previous bundle is considered "valid", which is only the case if it has been fully executed by the time the next bundle is proposed. This creates a racing condition where HubPoolClient#getNextBundleStartBlockNumber can return 0 for the starting block number if the previous bundle has not fully been executed by the time the next bundle is proposed.
Impact: This leads to double counting of everything in the balance report.
Solution: We can either pass latestBundle.blockNumber in the getNextBundleStartBlockNumber or just look directly at the ending block of the last fully executed bundle. The latter is more readable/intuitive so this PR goes with it.
> fix: Prevent overlapping when setting bundle's starting block for fetching pending refunds

- package.json
- yarn.lock
Especially the changes to split long markdown into multiple Slack messages.
> feat: Update to @uma/financial-templates-lib to 2.28.0 to get latest logger changes

- package.json
Reverts across-protocol/relayer-v2#173
> Revert "improve: Downgrade ethers to 5.6.1"

- src/clients/InventoryClient.ts
- src/clients/bridges/AdapterManager.ts
- src/clients/bridges/ArbitrumAdapter.ts
- src/clients/bridges/BaseAdapter.ts
- src/clients/bridges/CrossChainTransferClient.ts
- src/clients/bridges/OptimismAdapter.ts
- src/clients/bridges/PolygonAdapter.ts
- src/monitor/Monitor.ts
- src/monitor/MonitorClientHelper.ts
- src/relayer/Relayer.ts
- src/relayer/RelayerClientHelper.ts
- src/relayer/index.ts
- test/AdapterManager.SendTokensCrossChain.ts
- test/InventoryClient.InventoryRebalance.ts
- test/InventoryClient.RefundChain.ts
- test/Monitor.ts
- test/Relayer.BasicFill.ts
- test/Relayer.IterativeFill.ts
- test/Relayer.SlowFill.ts
- test/Relayer.TokenShortfall.ts
- test/Relayer.UnfilledDeposits.ts
- test/mocks/MockAdapterManager.ts
We'll need this support to monitor cross chain transfers from HubPool to SpokePools (rebalances).
> feat: Update adaptermanager and bridge adapters to support multiple addresses

- src/clients/bridges/BaseAdapter.ts
I ran simulations on a GCP VM instance with and without the change and the relayer succeeded with the change (in simulation mode)
> fix(adapter): Fix undefined errors due to unset entries for monitored addresses in BaseAdapter

- package.json
- src/finalizer/index.ts
- src/finalizer/utils/arbitrum.ts
- src/finalizer/utils/optimism.ts
- src/finalizer/utils/polygon.ts
- yarn.lock
Arbitrum nitro is imminent we should stay updated with latest release of the sdk
https://offchain.medium.com/introducing-nova-arbitrum-anytrust-mainnet-is-open-for-developers-9a54692f345e
> feat: Upgrade arbitrum-sdk to 2.0

- src/relayer/Relayer.ts
Before: https://risklabs.slack.com/archives/C03GWG1GPK3/p1657724105052889
After: https://risklabs.slack.com/archives/C03GT3LE78E/p1657723947598289
> fix: Fix relayer fee formatting in unprofitable fill message

- src/clients/MultiCallerClient.ts
Arbitrum has been failing with chunks of 100
> fix: lower chunk from 100 to 50

- .gitignore
- src/dataworker/Dataworker.ts
- src/dataworker/DataworkerConfig.ts
- src/dataworker/index.ts
https://linear.app/uma/issue/ACX-96/fix-bug-related-to-proposing-bundles-right-after-poolrebalanceleaves
> fix: Temporary stopgap to delay proposing bundles until 20 mins after latest Ethereum relayer refund leaf execution

- src/clients/SpokePoolClient.ts
Currently if the relayer finds only invalid fills for a deposit, the code throws an error as it expects at least one of the fills to be valid. This PR adds a check to return unfilledAmount = 0 if all fills are invalid.
error: TypeError: Cannot read property 'amount' of undefined
at SpokePoolClient.getValidUnfilledAmountForDeposit (/across-relayer/dist/src/clients/SpokePoolClient.js:147:61)
at /across-relayer/dist/src/utils/FillUtils.js:115:47
at Array.map (<anonymous>)
at getUnfilledDeposits (/across-relayer/dist/src/utils/FillUtils.js:112:18)
at Relayer.checkForUnfilledDepositsAndFill (/across-relayer/dist/src/relayer/Relayer.js:29:66)
at runRelayer (/across-relayer/dist/src/relayer/index.js:21:27)
at runMicrotasks (<anonymous>)
at processTicksAndRejections …
> fix: return unfilled amount = 0 if all fills found for a deposit are invalid

- src/monitor/Monitor.ts
Context: https://risklabs.slack.com/archives/C03JLFNQNDV/p1659046599069139
Problem: Around the time of relayer refund leaf executions we often see double counting in the balances report where it shows updated balances (including refunds) but there are still pending refunds. This likely indicates that the reporter bot didn't see the refund leaf executions yet but the balances it got are still updated. One possible root cause of this is the spokepoolclients are updated at the beginning of the bot run so they might not see the execution events yet. However when balances are queried later on, the provider node might see now see the executions => updated balances.
Solution: Query balances with the same latest block number the SpokePoolClients see. This ensures both the execution events and …
> fix(reporter): Query balances at the same block number as events to avoid double counting

- src/clients/bridges/AdapterManager.ts
- src/clients/bridges/ArbitrumAdapter.ts
- src/clients/bridges/BaseAdapter.ts
- src/clients/bridges/CrossChainTransferClient.ts
- src/clients/bridges/OptimismAdapter.ts
- src/clients/bridges/PolygonAdapter.ts
- src/interfaces/Bridge.ts
- src/monitor/Monitor.ts
- src/monitor/MonitorClientHelper.ts
- src/monitor/MonitorConfig.ts
- src/monitor/index.ts
- test/AdapterManager.getOutstandingCrossChainTokenTransferAmount.ts
- test/Monitor.ts
- test/mocks/MockAdapterManager.ts
Originally reviewed in https://github.com/across-protocol/relayer-v2/pull/197
> improve(monitoring): Add monitoring of stuck HubPool -> SpokePools cross chain transfers

- src/clients/ProfitClient.ts
The current construction can produce a *lot* of warning logs when things
aren't going so well, and this can in turn generate a lot of monitoring
events.
Also correct the following:
- A log message was incorrectly attributed to the TokenClient.
- A log message was incorrectly formatted and caused downstream
reporting warnings (missing at: keyword).
Ref: ACX-125
> fix: Incorrect log message format + reduce noise

- src/clients/ProfitClient.ts
- src/relayer/RelayerClientHelper.ts
- src/relayer/RelayerConfig.ts
- test/ProfitClient.ConsiderProfitability.ts
This is a temporary solution until we fully implement a capital fee requirement to be consistent with the API.
> improve(relayer): Filter all deposits with relayer fee % < 0.03%

- src/dataworker/Dataworker.ts
- test/Relayer.UnfilledDeposits.ts
- test/SpokePoolClient.SpeedUp.ts
So we're aware of any stuck leaves as soon as possible
> improve(dataworker): Update message about stuck leaves to warn

- package.json
- yarn.lock
Signed-off-by: david <david@umaproject.org>
> chore: bump fin-temp-lib version to include pdv2 logging

- src/dataworker/DataworkerClientHelper.ts
- src/scripts/validateRootBundle.ts
- Script is missing instructions about using cache﻿
- Script should not set allowances on hub pool for wallet
> improve: Update validation script

- src/common/Constants.ts
Align with RL internal config.
> chore(Constants): Adjust Ethereum minDepositConfirmations

- src/dataworker/index.ts
I suspect that the Dataworker is taking a long time between runs but its hard to know since there are overlapping logs in GCP, this PR adds a log to clearly print how long a loop run takes to complete.
﻿Signed-off-by: nicholaspai <npai.nyc@gmail.com>
> feat: Time Dataworker loop

- Dockerfile
- package.json
- yarn.lock
Signed-off-by: david <david@umaproject.org>
> chore: bump financial temp logging version

- src/clients/SpokePoolClient.ts
- src/dataworker/Dataworker.ts
I’m trying to get a benchmark for how fast the dataworker runs in order to improve its speed
> improve: Add timers for debugging speed

- src/clients/ConfigStoreClient.ts
- src/dataworker/DataworkerUtils.ts
- src/dataworker/PoolRebalanceUtils.ts
- src/dataworker/RelayerRefundUtils.ts
- src/interfaces/ConfigStore.ts
- src/utils/BigNumberUtils.ts
- src/utils/index.ts
- test/ConfigStoreClient.ts
- test/Dataworker.buildRoots.ts
- test/utils/utils.ts
This is a draft of how the target balance functionality might work. This is meant as an implementation proposal roughly following [this spec](https://docs.google.com/document/d/1kpu4r9FGU8CmAD6oUHVWX6V7DGkHww-hBdcdU7bQMLE/edit?usp=sharing).
The associated UMIP change is here: https://github.com/UMAprotocol/UMIPs/pull/556.
Note: the functionality is intended to be 100% backwards compatible, because a default threshold and target of 0 should result in the current behavior.
> feat: add target balances

- src/clients/bridges/ArbitrumAdapter.ts
- src/clients/bridges/PolygonAdapter.ts
This fixes an issue with #315 where the behavior was accidentally changed to error on unsupported tokens being seen in events (which is expected).
> fix(clients/birdges): fix error where unsupported tokens were not being ignored

- package.json
- yarn.lock
Signed-off-by: david <david@umaproject.org>
This introduces the pagerduty v2 severity level fixes
> chore: bump logger version for pdv2 fixes

- src/clients/SpokePoolClient.ts
Implements intended change that should have been included in https://github.com/across-protocol/relayer-v2/pull/321
> fix: Correctly update deposits in cache with sped up relayer fee pct 

- src/dataworker/DataworkerClientHelper.ts
Only update the ProfitClient if the proposer is enabled. Other dataworker functions don't need to know about token prices.
nb. This is a simple, low-impact change to work around logging of failed price request lookups.
> improve(Dataworker): Constrain ProfitClient update

- src/clients/ProfitClient.ts
- Factor out token price update and gas cost update into separate
methods.
- Update token prices and gas cost update in parallel.
Motivation: This makes the the follow-up diff to support the PriceClient
smaller and cleaner.
> improve(ProfitClient): Simplify update

- src/clients/ProfitClient.ts
This relieves the the new profitability logic from needing to know whether gas costs were retrieved.
> improve(ProfitClient): Always update gas costs

- package.json
- yarn.lock
Gives us access to some new toys.
> chore: Bump sdk-v2 ^0.1.21 -> ^0.1.30

- src/relayer/RelayerClientHelper.ts
- src/relayer/index.ts
When sending relays is disabled, don't bother checking for approvals.
> improve(relayer): Skip approvals in test

- src/clients/ProfitClient.ts
- src/common/Constants.ts
- src/relayer/RelayerClientHelper.ts
- src/relayer/RelayerConfig.ts
- test/ProfitClient.ConsiderProfitability.ts
- test/mocks/MockProfitClient.ts
Straight to the wall of shame...
> fix(ProfitClient): Avoid ethers underflow

- src/common/Config.ts
It's not actually used by ProviderUtils.ts...
> fix(Config): Nuke NODE_QUORUM_THRESHOLD

- src/clients/MultiCallerClient.ts
- src/finalizer/index.ts
- src/finalizer/utils/arbitrum.ts
> feat: Batch Arbitrum finalizations

- package.json
- src/clients/AcrossAPIClient.ts
- src/clients/ConfigStoreClient.ts
- src/clients/HubPoolClient.ts
- src/common/ClientHelper.ts
- src/finalizer/index.ts
- src/monitor/MonitorClientHelper.ts
- src/relayer/Relayer.ts
- src/relayer/RelayerClientHelper.ts
- src/utils/RedisUtils.ts
- src/utils/index.ts
- yarn.lock
findBlockAtOrOlder doesn't always work causing some timeouts bc lookback defaults to full range﻿
Added comment about buggy code in sdk-v2 [here](https://github.com/across-protocol/sdk-v2/pull/137)
> fix: Use BlockFinder instead of sdk.findBlockAtOrOlder

- src/utils/ProviderUtils.ts
Makes it easier to manually spot in logs
> improve(ProviderUtils): Add emoji to `warn` log about disagreeing providers

- src/utils/TransactionUtils.ts
To be useful in a pending MultiCallerClient update...
Prettier makes this change look bigger than it really is.
> improve(runTransaction): Permit caller to specify nonce

- src/finalizer/utils/polygon.ts
Handle this error so it doesn't go to PD error level
> fix(finalizer): Handle undefined error?.reason

- src/clients/MultiCallerClient.ts
- src/utils/TransactionUtils.ts
Makes life easier for users of this function.
> improve(TransactionUtils): Export willSucceed return type

- package.json
- yarn.lock
Fixes bug where rate model has Ubar = 0
> fix: Update sdk-v2 to handle divide-by-0 bug in lpFeeCalculator

- src/clients/MultiCallerClient.ts
- test/MultiCallerClient.ts
Add an initial test to mock out simulation of enqueued transactions. This will enable test of other functionalities to specify whether the transactions should succeed or fail.
More to follow.
> improve(MultiCallerClient): Bootstrap test

- src/clients/MultiCallerClient.ts
- test/MultiCallerClient.ts
Allows it to be mocked out in a subclass for test purposes.
> improve(MultiCallerClient): Factor out txn submission

- src/clients/ConfigStoreClient.ts
- src/interfaces/ConfigStore.ts
- test/ConfigStoreClient.ts
should read routeRateModel not routeRateModels
> fix: Fix routeRateModel typo

- src/clients/MultiCallerClient.ts
- test/MultiCallerClient.ts
- Verify robustness against a 0-length array being supplied to buildMultiCallBundles().
- Remove async on buildMultiCallBundles().
- Improve test naming.
> improve(MultiCallerClient): Correctness & test improvements

- src/clients/MultiCallerClient.ts
The new MultiCallerClient is dropping the transaction message when
it is creating bundles.
> fix(MultiCallerClient): Retain txn message

- src/clients/SpokePoolClient.ts
- src/utils/RedisUtils.ts
- src/utils/TimeUtils.ts
Mitigates chance of caching deposit that gets re-orged
> improve(RedisUtils): Add delay to cache historical deposits

- package.json
- scripts/constructEmergencyRoot.ts
- src/finalizer/index.ts
- src/finalizer/utils/optimism.ts
- src/scripts/validateRootBundle.ts
- yarn.lock
Boba's fork of Optimism's SDK isn't published on NPM so I forked a repo under @across-protoocl/boba:packages/sdk
> feat: add Boba finalizer

- src/utils/TransactionUtils.ts
So we can experiment with relayer gas pricing
> feat: Allow gas fee scaler's to be settable via env variables

- src/clients/MultiCallerClient.ts
- src/utils/TransactionUtils.ts
For  nonce collisions and gas price estimation errors, bots should try to resubmit
> improve(TxUtils): Should try to resubmit txn when encountering certain errors

- test/MultiCallerClient.ts
- test/TransactionClient.ts
- test/mocks/MockTransactionClient.ts
Driveby change -  spotted these while referencing these tests, and my editor
has started proactively warning me about them.
> fix(test): Fix various issues flagged by editor

- yarn.lock
I've noticed this change being included by dependabot when it proposes other, unrelated updates.
Am pulling it out here so it can be considered independently.
> chore(yarn.lock): Re-sync

- src/utils/EventUtils.ts
Should have been removed as part of the following commit:
- 8391525a430bb15432b89c267674ef3493177e92.
> chore: Cleanup unused variable

- src/relayer/ProfitabilityCalculator.ts
- src/relayer/Relayer.ts
- src/relayer/RelayerClientHelper.ts
- src/relayer/index.ts
This change aims to correct the `relayer` directory.
> refactor: :recycle: refactor the `relayer` directory

- src/utils/AddressUtils.ts
- src/utils/ContractUtils.ts
- src/utils/DepositUtils.ts
- src/utils/EventUtils.ts
- src/utils/ExecutionUtils.ts
- src/utils/FillMathUtils.ts
- src/utils/FillUtils.ts
- src/utils/FormattingUtils.ts
- src/utils/GckmsUtils.ts
- src/utils/Help.ts
- src/utils/MerkleTreeUtils.ts
- src/utils/ObjectUtils.ts
- src/utils/ProviderUtils.ts
- src/utils/RedisUtils.ts
- src/utils/TransactionPropBuilder.ts
- src/utils/TransactionUtils.ts
This PR aims to bring the `util` functions within compliance of the new tsconfig & eslint config.
> refactor: :recycle: update `util` directory to comply with new tsconfig

- src/dataworker/Dataworker.ts
This was causing the executor to fail silently.
> fix: fix bug in slow relay construction

- package.json
- src/interfaces/index.ts
- src/utils/UBAFeeCalculator.ts
- yarn.lock
This change adds the UBAFeeCalculator client class. This class will eventually work with @pxrl's logic to extract and sequence an array of UBA flows as well as logic that is used to calculate the latest running validated balance.
> feat(UBA): :sparkles: add stub for new UBAFeeCalculator

- package.json
- src/clients/SpokePoolClient.ts
- src/dataworker/PoolRebalanceUtils.ts
- src/relayer/Relayer.ts
- src/utils/DepositUtils.ts
- src/utils/FillUtils.ts
- test/Dataworker.loadData.ts
- test/Relayer.UnfilledDeposits.ts
- test/SpokePoolClient.SpeedUp.ts
- test/SpokePoolClient.ValidateFill.ts
- yarn.lock
The FundsDeposited event is unique in that its blockNumber currently refers to the block number according to its quoteTimestamp. All other events use blockNumber to specify the timestamp of their event.
This change re-aligns FundsDeposited to be more compatible with the other type definitions, which will make it easier to sort them for the UBA model.
> refactor(FundsDeposited): Realign blockNumber purpose

- hardhat.config.ts
Pulled from Nick's changes on the Across-2.5 branch. Can be merged to master without
affecting prod, so the strategy is to migrate it in advance so that the remaining delta is
smaller and confined (as much as possible) to breaking changes.
Co-authored-by: nicholaspai <9457025+nicholaspai@users.noreply.github.com>
> chore(across-v2.5): Import hardhat config changes

- src/clients/SpokePoolClient.ts
This makes the code a bit more compact and requires fewer type assertions, and should also be compatible with both master and across-2.5.
> refactor(SpokePoolClient): Adjust DepositWithBlock production

- scripts/disableDepositRoutes.ts
Example run
```sh
nicholaspai@Nicholass-MacBook-Pro-772 ➜  relayer-v2 git:(catch-error) ✗ ts-node ./scripts/disableDepositRoutes.ts --wallet mnemonic
...
2023-04-19 15:57:16 [debug]: {
"at": "disableDepositRoutes",
"message": "Routes to disable",
"routesToDisable": [
{
"originChainId": 1,
"destinationChainId": 10,
"originToken": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
"depositsEnabled": true
},
{
"originChainId": 1,
"destinationChainId": 137,
"originToken": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
"depositsEnabled": true
},
{
"originChainId": 1,
"destinationChainId": 42161,
"originToken": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
"depositsEnabled": true
},
{
"originChainId": 1,
"destinationChainId": 10,
"originToken": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48", …
```
> feat: Update disable deposit script to include one blob that disables all routes

- src/utils/UBAFeeCalculator/UBAFeeCalculator.ts
- src/utils/UBAFeeCalculator/UBAFeeCalculatorWithRefresh.ts
- src/utils/UBAFeeCalculator/index.ts
This PR adds the ability for the UBA Fee Calculator to replay the fees of each of the running events within its running balance.
> feat(UBA): :sparkles: Add function to compute a range of fees

- src/utils/UBAFeeCalculator/UBAFeeCalculator.ts
- src/utils/UBAFeeCalculator/UBAFeeCalculatorWithRefresh.ts
- src/utils/UBAFeeCalculator/index.ts
This change modifies the UBA fee calculations into an LP fee and a relayer fee.
> feat(UBA): :sparkles: separate UBA fees into fee categories

- src/utils/UBAFeeCalculator/UBAFeeCalculator.ts
- src/utils/UBAFeeCalculator/UBAFeeCalculatorWithRefresh.ts
- src/utils/UBAFeeCalculator/index.ts
This PR separates the logic within the UBA Fee calculator to include both manual and refresh variants of the UBA Fee Calculator.
> feat: ✨ add refresh and manual version of UBA Fee calc

- hardhat.config.ts
- package.json
- yarn.lock
Includes a fix to the `hardhat.config` file to deal with imported `hardhat` objects from updated packages
> improve: Update sdk-v2 and contracts-v2 to non-beta versions

- src/common/ClientHelper.ts
- src/finalizer/index.ts
> improve(ClientHelper): Document client dependencies

- package.json
- yarn.lock
Reduce log noise from the ConfigStoreClient.
> chore: Bump SDK

- test/Monitor.ts
The MonitorConfig hasn't read this from the environment for quite a while.
> chore(monitor): Remove CONFIGURED_NETWORKS

- package.json
- yarn.lock
Main benefit is getting access to more accurate Optimism gas estimation post-bedrock
> chore: Bump @across-protocol/sdk-v2

- src/relayer/Relayer.ts
Compact the code ahead of some pending updates for the UBA.
> refactor(Relayer): Dereference commonly used objects

- src/clients/ProfitClient.ts
- test/ProfitClient.ConsiderProfitability.ts
Reuse fixed-point division. This saves creating a bunch of throwaway
BigNumber types just for the purpose of dividing. Additionally,
normalise log formatting of numbers back from 18 decimals. This
makes it much easier to read the messages and debug misbehaviour.
These changes are made in preparation for an update for UBA, but
were diff-noisy, so I split them out.
> refactor(ProfitClient): Misc improvements

- src/finalizer/utils/optimism.ts
I've manually finalized all withdrawals that originated pre bedrock.
The SDK does not correctly recognize these as `RELAYED` when `getMessageStatus()` is queried, instead they are returned as `READY_TO_RELAY` which causes the finalizer to revert.
This fix temporarily filters out pre bedrock messages, and can be removed once the SDK is fixed.
There is no harm keeping this PR in outside of extra async latency caused by calling `toCrossChainMessage`, since there shouldn't be any new pre bedrock withdrawals
> fix(finalizer): Filter out non Bedrock withdrawals

- src/clients/TransactionClient.ts
Harden the submit() method by verifying that each enqueued transaction specifies the same chainId as the input chainId argument. This should help prevent accidentall submission on the wrong chain.
Additionally, adjust the recently added gas padding log message for better readability.
> improve(TransactionClient): Robustness + logging

- package.json
- src/clients/ProfitClient.ts
- src/clients/UBAClient.ts
- src/interfaces/index.ts
- src/relayer/Relayer.ts
- test/Relayer.BasicFill.ts
- test/mocks/MockUBAClient.ts
- test/mocks/index.ts
- yarn.lock
Introduces UBA fees to the relayer. UBA fees are only applied if the deposit version is >= the minimum applicable UBA version.
Closes ACX-1189
> feat(UBA): Derive UBA relayer fees via UBAClient

- src/utils/ProviderUtils.ts
- src/utils/TimeUtils.ts
This is a generally useful function.
> refactor: Export delay() from TimeUtils

- package.json
- src/clients/BundleDataClient.ts
- src/clients/UBAClient.ts
- src/relayer/Relayer.ts
- src/utils/DepositUtils.ts
- src/utils/FillUtils.ts
- test/ConfigStoreClient.ts
- test/Dataworker.buildRoots.ts
- test/Dataworker.proposeRootBundle.ts
- test/Relayer.BasicFill.ts
- test/Relayer.UnfilledDeposits.ts
- test/SpokePool.Utilities.ts
- test/SpokePoolClient.ValidateFill.ts
- test/UBAClientUtilities.ts
- test/UBAFeeConfig.ts
- test/mocks/MockUBAClient.ts
- yarn.lock
Companion unit tests to SDK PR [#308](https://github.com/across-protocol/sdk-v2/pull/308/files#diff-d2decf35e36422291323a94ed96a949778b031996571644c1b65d3ffcf40db4e)
> feat(test): Add UBAClientUtilities unit tests

- src/caching/RedisCache.ts
Purely a documentation add to the previous PR
> docs: add comments

- src/dataworker/README.md
- src/scripts/testUBAClient.ts
> feat(dataworker): Add README explaining without code how bundles are made

- scripts/disableDepositRoutes.ts
- src/common/ClientHelper.ts
- src/common/Config.ts
- src/dataworker/DataworkerClientHelper.ts
- src/dataworker/index.ts
- src/monitor/MonitorClientHelper.ts
- src/monitor/MonitorConfig.ts
- src/relayer/RelayerClientHelper.ts
- src/scripts/testUBAClient.ts
- src/scripts/validateRootBundle.ts
- src/scripts/validateRunningBalances.ts
- test/UBAClient.validateFlow.ts
- test/UBAClientUtilities.ts
- test/utils/HubPoolUtils.ts
This way we can validate configs that are set per-chain once we know all chains to validate using the config store client's chain ID's fetched from on-chain
Fixes ACX-1390
> feat: add validation function to Config class

- package.json
- src/clients/ProfitClient.ts
- yarn.lock
This is just some boilerplate necessary for fillRelay estimates to be computed correctly.
> chore: Specify zkSync relay fee calculator

- package.json
- src/clients/UBAClient.ts
- src/dataworker/index.ts
- src/relayer/RelayerClientHelper.ts
- src/scripts/testUBAClient.ts
- test/Relayer.RefundRequests.ts
- test/mocks/MockUBAClient.ts
- yarn.lock
Adds a new UBAClientConfig object to the UBAClient which will allow caller to more easily add a configuration in the future
> feat: Import sdk@15.11

- src/monitor/Monitor.ts
- src/monitor/MonitorClientHelper.ts
Certain monitor functions need chains for all spokepool clients, certain ones only care about those that have cross chain adapters
> fix(monitor): Distinguish better between cross-chain adapter-supported chains and all spoke pool chains

- hardhat.config.ts
- package.json
- scripts/unwrapWeth.ts
- src/clients/ProfitClient.ts
- src/common/Constants.ts
- src/common/ContractAddresses.ts
- src/dataworker/DataworkerUtils.ts
- src/utils/NetworkUtils.ts
- yarn.lock
This adds a bunch of constants and defaults to support Base.
Note: for some of the code here to work, this sdk PR will need to be merged and released: https://github.com/across-protocol/sdk-v2/pull/369.
> feat: add Base constants/defaults

- src/finalizer/index.ts
- src/finalizer/utils/opStack.ts
This cleans up index.ts and removes a lot of exports from utils/opStack.ts.
Have only done Optimism so far to keep the diff simple, but will repeat separately for Polygon and Arbtirum.
> refactor(finalizer): Remove opStack code from index

- package.json
- yarn.lock
Includes Base deployment data.
> chore(across-v2): Bump contracts-v2

- src/finalizer/index.ts
- src/finalizer/utils/polygon.ts
Following on from the Optimism change, this repeats the process for Polygon.
> refactor(finalizer): Remove Polygon code from index

- src/finalizer/index.ts
- src/finalizer/utils/arbitrum.ts
Repeat the finalizer refactoring for Arbitrum One.
> refactor(finalizer): Remove Arbitrum One code from index

- src/utils/CLIUtils.ts
This PR wraps the provided keyfile as an array.
> hotfix: relayer signer

- package.json
- scripts/hubpool.ts
- scripts/spokepool.ts
- scripts/utils.ts
This script can be used to:
- Scrape arbitrary HubPool events (ProposeRootBundle, DisputeRootBundle, ...)
- Initiate a dispute, automating the use of the bond token.
Closes ACX-1502
> feat: HubPool helper script

- scripts/utils.ts
Was recently broken during a refactor.
> fix: Correct scripts contract resolution utility

- src/clients/ProfitClient.ts
- src/common/Constants.ts
Note - we still need to bump contracts-v2 to get Mumbai contract addresses.
> feat: Update constants for Polyon Mumbai

- src/finalizer/index.ts
Simulate all finalizations before bundling them into the multicall aggregate() transaction, which will fail in aggregate if even a single transaction is unsuccessful. This caused problems today, when a small number of zkSync withdrawals were unsuccessful, resulting in a finalizer halt for a few hours.
Transactions are simulated first for logging purposes; it would be possible to user multicall3.tryAggregate(false, ...), except it's non-trivial to extract the results of each transaction.
Fixes ACX-1551
> improve: Simulate finalization txns before failure

- src/common/ContractAddresses.ts
- src/utils/UmaUtils.ts
Removes another UMA dependency from relayer-v2.
> refactor: Host UMA VotingV2 ABI and address locally

- src/utils/index.ts
- test/utils/utils.ts
Basic import plumbing to pull in depdencies from sdk-v2.
> refactor: Update utils imports and exports

- package.json
- src/clients/AcrossAPIClient.ts
- src/clients/ProfitClient.ts
- src/clients/bridges/ArbitrumAdapter.ts
- src/clients/bridges/PolygonAdapter.ts
- src/utils/TokenUtils.ts
- test/AdapterManager.SendTokensCrossChain.ts
- yarn.lock
> feat: Import constants-v2

- src/finalizer/index.ts
I discovered this the hard way.
> improve: Catch Finalizer lookback misconfiguration

- src/utils/RedisUtils.ts
This PR resolves the get/set key for redis
> fix: :ambulance: resolve get key error

- .github/workflows/dependency-review.yml
> fix: Re-enable dependency review

- src/dataworker/Dataworker.ts
Utilize the sdk implementation of `isMessageEmpty`
> improve: use SDK for verifying `isMessageEmpty`

- scripts/spokepool.ts
- scripts/utils.ts
This will be useful for verifying messaging.
> improve(spokepool): Dynamic relayerFeePct pricing on deposits

- src/clients/ProfitClient.ts
- test/ProfitClient.ConsiderProfitability.ts
- test/ProfitClient.PriceRetrieval.ts
Simplify and cleanup some of the code in advance of a more significant change
> refactor(ProfitClient): Initial cleanup

- src/dataworker/Dataworker.ts
Minor adjustment to remove some redundant code - no change in behaviour.
> refactor(Dataworker): Simplify bundle block ranges

- src/finalizer/index.ts
- src/finalizer/utils/opStack.ts
For unknown reasons the finalizer is not estimating gas correctly and failing unexpectedly when the batch gets too large
> feat(finalizer): Cap # of txns included in a single finalizer batch

- package.json
- scripts/hubpool.ts
- scripts/utils.ts
- yarn.lock
The motivation for this was adding support for Optimism Goerli.
> improve: Update scripts w/ centralised chain defs

- src/clients/InventoryClient.ts
The relayer now calls into the InventoryClient in new ways, and this can backfire if the relayer doesn't have an inventory config defined.
While here, sub out instances of toBN(0) in favour of the predefined bnZero. This is more memory efficient and saves creating disposable BNs.
> improve(InventoryClient): Safer dereferencing & use bnZero

- src/clients/AcrossAPIClient.ts
- src/clients/InventoryClient.ts
- src/clients/MultiCallerClient.ts
- src/clients/ProfitClient.ts
- src/dataworker/PoolRebalanceUtils.ts
- src/relayer/Relayer.ts
- src/utils/SDKUtils.ts
- test/MultiCallerClient.ts
- test/ProfitClient.ConsiderProfitability.ts
- test/ProfitClient.PriceRetrieval.ts
- test/Relayer.BasicFill.ts
- test/mocks/MockProfitClient.ts
Per a comment by James to a previous PR.
> refactor: Consolidate sdk-v2 BN imports

- src/relayer/Relayer.ts
It's important to filter on supported tokens before trying to evaluate whether the fill amount is within the maximum limit.
> fix(relayer): Reorder deposit filtering

- src/dataworker/index.ts
This gets updated in `createDataworker` above
> improve(Dataworker): Remove redundant configStoreClient.update

- src/common/ClientHelper.ts
Using `latestBlockNumber` leads to drift between mainnet and the respective spoke chains due to the time delay implied by the HubPoolClient update.
> fix(ClientHelper): Sync SpokePoolClient search configs

- src/dataworker/Dataworker.ts
No intended change in behaviour, but this commit collapses the code somewhat.
> refactor(Dataworker): Simplify legacy/UBA proposal flow

- src/clients/ProfitClient.ts
- src/dataworker/Dataworker.ts
- src/dataworker/PoolRebalanceUtils.ts
- src/utils/FillUtils.ts
- Reflow up markdown generation.
- Reuse sdk-v2 filledSameDeposit().
> refactor: Minor adjustments before v3 update

- .gitignore
> improve: Document git dotfile policy

- src/relayer/Relayer.ts
> refactor: Compress relayer deposit MDC filtering

- src/clients/InventoryClient.ts
The rebalancer intends to verify that the mainnet balance has not changed under its feet, but it was decrementing the expected balance for each rebalance operation once approved. Any cases where the same token was rebalanced on multiple chains would fail after the first iteration because the expected balance would be different from the onchain value due to this decrement.
> fix: rebalancer should use non-decrementing balance for checking against chain state

- test/utils/index.ts
- test/utils/utils.ts
As was recently done over in the SDK.
> refactor: Cleanup UMA exports in test

- src/clients/InventoryClient.ts
No functional change intended.
> refactor: Minor InventoryClient simplifications

- package.json
- src/common/Constants.ts
- src/dataworker/DataworkerClientHelper.ts
- src/dataworker/DataworkerUtils.ts
- src/monitor/MonitorClientHelper.ts
- src/relayer/RelayerClientHelper.ts
- src/utils/BlockUtils.ts
- test/Dataworker.buildRoots.ts
- yarn.lock
I also added a test for this scenario
> fix: Update SDK so HubPoolClient.batchCompute handles multiple origin chains

- src/common/Constants.ts
Wait until bots are stable with version bumped on local bots before we add to this repo
> feat: Bump CONFIG_STORE_VERSION to 3

- package.json
- src/clients/BundleDataClient.ts
- src/clients/InventoryClient.ts
- src/common/Config.ts
- src/dataworker/DataworkerUtils.ts
- src/monitor/Monitor.ts
- test/mocks/MockBundleDataClient.ts
- test/utils/utils.ts
- yarn.lock
- Allows InventoryClient to better project upcoming refunds
- Allows reporter to do the same
> fix: Implement V3 event handling to getRefund logic in BundleDataClient 

- src/relayer/Relayer.ts
Signs should be reversed so that a negative number represents a virtual loss for relayer
Example of logs without this PR
> fix: Reverse signs in repayment chain choice log

- package.json
- scripts/spokepool.ts
- scripts/utils.ts
- src/clients/ProfitClient.ts
- src/common/Constants.ts
- src/dataworker/DataworkerConfig.ts
- src/relayer/Relayer.ts
- yarn.lock
This PR is aimed at allowing the relayer-v2 repo to be run on sepolia based testnets.
> feat: facilitate testnet relays/dataworker operations

- test/Relayer.TokenShortfall.ts
In anticipation of removing v2 functionalities.
> refactor: Update Relayer TokenShortfall test to v3

- src/clients/MultiCallerClient.ts
Will filter these type of errors out of error-level logs
> improve: Add nonce-reused error to known list of error reasons

- test/Relayer.BasicFill.ts
- test/utils/utils.ts
This is submitted separately from the previous updates because otherwise the resulting diff is impossible to read. While here, make some tiny cleanups to resolve warnings in my editor.
> refactor: Flush Relayer BasicFill v2 test

- src/clients/ProfitClient.ts
- src/relayer/Relayer.ts
- test/ProfitClient.ConsiderProfitability.ts
It was easier to re-add this than first thought.
> fix: Restore unprofitable fill reporting

- src/monitor/Monitor.ts
- src/relayer/Relayer.ts
- src/utils/FillUtils.ts
- test/Relayer.UnfilledDeposits.ts
This reverts commit 8c307af2898cc9bfddd92d2d2c3c2d1e0f5c208b.
> fix: Revert "refactor: Simplify FillUtils getUnfilledDeposits() (#1249)"

- src/dataworker/DataworkerUtils.ts
The PR makes the following changes:
1. Adds an emoji to the end of the Arweave data posting Slack message
2. Rearrange/replace some object parameters passed to Slack for Arweave
> improve(logs): update arweave logs

- src/monitor/MonitorClientHelper.ts
In advance of bumping contracts-v2.
> chore: Drop v2 events from monitor

- test/Dataworker.executePoolRebalances.ts
- test/Dataworker.executeRelayerRefunds.ts
- test/Dataworker.executeSlowRelay.ts
- test/Dataworker.proposeRootBundle.ts
- test/Dataworker.validateRootBundle.ts
Helps support removing V2 reliance in Dataworker
> improve: Change some dataworker tests to use V3 functions instead of V2

- src/relayer/Relayer.ts
This logic isn't needed anymore; removing it cuts out some complexity and helps with follow-up refactoring.
> refactor: Remove redundant slow fill rebalancing checks

- src/clients/bridges/LineaAdapter.ts
- src/common/ContractAddresses.ts
This PR adds a mostly completed Linea Adapter Manager. Namely - the only function that has been specifically made a no-op is `getOutstandingCrossChainTransfers` but a `// FIXME:` has been added and I will follow up with it before EOD.
> feat(linea): Adapter Manager Client

- src/dataworker/Dataworker.ts
Currently we are sending the fee for every single Linea leaf execution. This ultimately means we are donating the fee to the LP pool because the LineaSpokePool will deposit any ETH in its balance into WETH rather than keep an ETH balance to use for these leaf executions. (In other words, the Linea SpokePool is dumb and doesn't segregate leaf execution fees from LP funds, therefore it is the responsibility of the leaf executor to only send an appropriate amount to pay for fees exactly when those fees are meant to be used).
The damage right now is minimal, totalling ~0.01 ETH for 10 leaf executions.
Also, sending value needlessly on these executions doesn't allow the MulticallerClient to batch these txns, adding extra gas costs
> fix(Dataworker): Send msgValue to pay for Linea leaf executions IFF amountToReturn > 0

- src/clients/AcrossAPIClient.ts
Reduce chance of bursty API calls when caches all expire at same time
> improve(ApiClient): Randomize /limits cache TTL

- src/clients/bridges/BaseAdapter.ts
Shuffle the code slightly so that the markdown is included in the transaction request.
Fixes ACX-1912
> fix: Restore markdown on token rebalancing

- src/clients/ProfitClient.ts
The previous change suppressed the wrong log message.
> chore(ProfitClient): Suppress the correct warning message

- src/relayer/Relayer.ts
In case of a self-relay the relayer's immediate token balance doesn't change.
> fix(relayer): Don't decrement local balance for self-relay

- src/clients/InventoryClient.ts
To aid in debugging repayment chain selection.
> improve(InventoryClient): Additional logging

- src/clients/InventoryClient.ts
I see this failing on prod but not locally so its been hard to reproduce
> improve: Add error to bundle refund failure log

- package.json
- yarn.lock
> chore(sdk-v2): bump to v0.23.4

- src/clients/AcrossAPIClient.ts
Rather than throwing, just fall back to a safe deposit (...repayment) limit.
> refactor(relayer): Default to 0 for maxDeposit

- index.ts
- src/utils/ExecutionUtils.ts
This reverts commit 4621240a1af6acd7af2c8c562b513fe091dc65df.
This seems to make the bot occasionally hang. We're not exactly sure why, but reverting out of caution.
> Revert "refactor: Remove top-level bot loop (#1397)"

- src/common/ContractAddresses.ts
My work in the IM has overlapped with an open PR in the finalizer that's awaiting final reviews - to avoid committing duplicate definitions, my work can be rebased with this PR upstream
> improve(CCTP): add addresses for CCTP ABI

- src/relayer/index.ts
This commit changes the way config.pollingDelay is used in the relayer. Previously, the relayer would wait pollingDelay seconds _after_ its previous run before commencing its next loop. This is OK when loop times are fairly predictable, but in practice there can be quite high variance in loop times due to variable RPC response timing. In cases where the loop times are slow, the relayer becomes significantly less responsive to new deposits.
Instead, use pollingDelay as an interval timer at which the relayer should be started. In the event that the relayer takes more than pollingDelay seconds to execute its loop, the delay will be skipped and the relayer will instead proceed to evaluate and deposits that may have occurred during the previous loop.
While here, improve the logging such that …
> improve(relayer): Reduce delays & improve logging

- src/relayer/Relayer.ts
Identical idea to https://github.com/across-protocol/relayer-v3/pull/1433 to quiet down logs when not sending relays
> improve(Relayer): Don't log about shortfalls when not sending relays

- src/relayer/Relayer.ts
Rebalancer slack channel should not be logging these
> improve(Relayer): Reduce log level when sending relays disabled

- src/relayer/Relayer.ts
The MDC floor should only be computed against the deposits that the relayer can reasonably expect to fill. This would mostly occur when a large slow fill is pending.
> improve(relayer): Exclude unfillable deposits from MDCs

- src/clients/bridges/LineaAdapter.ts
This PR builds off of #1469 to add the LineaAdapter
> fix: resolve linea

- src/clients/bridges/BaseAdapter.ts
When I converted the if statement to an assert the boolean wasn't inverted.
> hotfix(assert): invert assertion

- test/InventoryClient.InventoryRebalance.ts
Partly required as a byproduct of the pending USDC/CCTP updates.
> refactor(test): InventoryClient simplifications

- test/InventoryClient.InventoryRebalance.ts
- test/InventoryClient.RefundChain.ts
- test/utils/utils.ts
...prior to introducing new tests.
> refactor(test): Cleanup InventoryClient refund chain test

- test/Relayer.IndexedSpokePoolClient.ts
> fix(test): Avoid external RPC call

- src/clients/InventoryClient.ts
Replace with `tokenClient.getShortfallTotalRequirement` because `getTokenShortFall` doesn't correctly get shortfall for a specific L2 token in the case where multiple L2 tokens map to the same L1 token
> improve: Remove getTokenShortfall

- src/clients/HubPoolClient.ts
- src/utils/AddressUtils.ts
> fix: Handle case where getUsdcSymbol returns undefined

- src/finalizer/index.ts
This PR aims to push a fix to finalize CCTP events.
> fix(finalizer): enrich l1 -> l2 addresses

- src/finalizer/index.ts
We should probably be able to specify finality direction as we need to have different frequency intervals for l1 & l2 finalizations.
> feat(finalizer): specify finalization direction

- src/finalizer/index.ts
Could be good to log which direction the finalizer is going in
> improve(finalizer): log finalization strategy

- src/finalizer/utils/cctp/l1ToL2.ts
- src/finalizer/utils/cctp/l2ToL1.ts
This reverts commit 7e6b5a69f8b434ff5f53f171f9e373266055a300.
> improve(finalizer#cctp): clearer logs

- src/clients/TokenClient.ts
This makes it easier to scan for any delays in logs.
> improve(TokenClient): Tweak update log message

- src/monitor/index.ts
I don't understand how this previously passed CI.
> fix(monitor): Update multicallerclient function name

- src/monitor/index.ts
> improve(Monitor): Instantiate clients correctly

- src/utils/RetryUtils.ts
- test/RetryUtils.ts
Adds unit tests to verify behavior
> feat(utils): Fix retryAsync with delay function

- test/Relayer.UnfilledDeposits.ts
- test/utils/utils.ts
This permits depositV3() to be called in parallel, which does actually happen in current tests. Also, update the unfilled deposits test to read unfilled deposits correctly.
> improve(test): Better depositV3() in test

- .circleci/config.yml
- .github/workflows/publish.yml
- Dockerfile
- package.json
I've seen a roughly 20% speed improvement
> chore(v20): bump to v20

- .circleci/config.yml
- .github/workflows/publish.yml
- Dockerfile
- package.json
Reverts across-protocol/relayer#1599
> chore(revert): 1599

- package.json
- src/monitor/Monitor.ts
- yarn.lock
Reverts across-protocol/relayer#1563
> Revert "improve(Monitor): reformat reportRelayerBalances log"

- src/clients/bridges/BaseAdapter.ts
- src/clients/bridges/utils.ts
For future reuse by a slimmed-down bridge adapter structure.
> refactor(bridges): Factor out approval functions

- src/clients/BundleDataClient.ts
- src/relayer/Relayer.ts
- test/Dataworker.loadData.ts
This PR aims to disable slow fills for deposits that need to be filled on a lite chain or originating from a lite chain.
> feat: disable slow fills for deposits involving lite chains

- contracts/MockCctpEvents.sol
- contracts/MockOpStackEvents.sol
- src/clients/bridges/op-stack/DefaultErc20Bridge.ts
- src/clients/bridges/op-stack/OpStackAdapter.ts
- src/clients/bridges/op-stack/UsdcCCTPBridge.ts
- src/clients/bridges/op-stack/UsdcTokenSplitterBridge.ts
- src/clients/bridges/op-stack/WethBridge.ts
- src/clients/bridges/op-stack/optimism/DaiOptimismBridge.ts
- src/clients/bridges/op-stack/optimism/SnxOptimismBridge.ts
- test/cross-chain-adapters/OpStack.ts
Closes ACX-2206
Refines existing unit tests for "old" OP stack adapters.
> test(op-stack): refine unit tests

- package.json
- yarn.lock
...for the Lisk SpokePool re-deployment.
> chore: Bump contracts & sdk

- package.json
- yarn.lock
Add the new changes about the deposit schema
> chore: bump sdk version

- package.json
- yarn.lock
> chore: Bump constants, contracts & sdk

- src/libexec/RelayerSpokePoolIndexer.ts
The fast relayer has recently been skipping its lookback. While here,
make it explicit when the external indexer skips the lookback.
> fix(relayer): Correctly resolve external lookbacks

- src/finalizer/index.ts
> improve(Finalizer): Only construct spoke pool clients for L2s we are finalizing

- src/monitor/Monitor.ts
> improve(Monitor): Ignore chains without pool rebalance leaves when logging about "stuck" rebalances

- src/finalizer/utils/scroll.ts
The current finalizer is outdated since it fetches info from an API which does not exist. This commit updates the URL to use the one which is currently maintained by Scroll.
> improve(finalizer): update scroll finalizer with new api

- src/utils/CCTPUtils.ts
Prompted by: https://github.com/across-protocol/relayer/pull/1726
We already throw out pending/finalized messages for CCTP. Because of this, we can avoid calling Circle's attestation API unless we know there's a chance we need to use the attestation. I.e. when a message is already finalized (which most of our finalizer runs will be in the scope of)
> improve: prevent attestations on finalized messages

- src/utils/ObjectUtils.ts
- src/utils/ProviderUtils.ts
Preliminary PR prior to migrating any caching provider logic into the SDK
> improve(any): remove implicit any

- package.json
- src/dataworker/DataworkerUtils.ts
- yarn.lock
This PR adds a new `error` log if the AR balance is too low, and also formats the balance logs better.
Additionally it sends logs to an across-arweave custom slack path if the webhook key is set
> improve(ArweaveClient): Log arweave details to custom slack channel, improve logs

- src/clients/ProfitClient.ts
- test/ProfitClient.ConsiderProfitability.ts
The operator can define MIN_RELAYER_FEE_PCT_\<SYMBOL\> to set a token-specific profitability configuration.
> improve(relayer): Permit per-token profitability config

- src/relayer/index.ts
> fix(relayer): Require at least one relayer loop

- src/clients/InventoryClient.ts
- src/clients/ProfitClient.ts
- src/clients/TokenClient.ts
- src/dataworker/Dataworker.ts
- src/dataworker/DataworkerUtils.ts
- src/dataworker/PoolRebalanceUtils.ts
- src/interfaces/index.ts
- src/relayer/Relayer.ts
- src/scripts/validateRunningBalances.ts
- src/utils/FillUtils.ts
- src/utils/MerkleTreeUtils.ts
- test/InventoryClient.RefundChain.ts
- test/ProfitClient.ConsiderProfitability.ts
- test/Relayer.BasicFill.ts
- test/utils/SpokePoolUtils.ts
- test/utils/utils.ts
No change in functionality - this is pure cleanup.
> chore: Drop V3 type shims

- test/TryMulticallClient.ts
In the tryMulticall tests, since we randomly determine if a transaction succeeds or fails, there is a chance that all the transactions in a bundle fail, meaning that we discard the bundle entirely and do not execute any transaction. Our checks assume that this does not happen, so this PR adds the edge case in our tests so we will no longer fail on these tests on occasion.
> fix(tests): handle edge case in probabilistic tests

- src/utils/TransactionUtils.ts
Permit operators to trigger a nonce reset in case of a queue of pending transactions.
> improve(TransactionUtils): Permit env-based nonce reset

- src/utils/EventUtils.ts
- test/EventManager.ts
This should have been added as part of the previous commit.
> fix(relayer): Log arguments are no longer an array

- src/relayer/RelayerClientHelper.ts
- src/relayer/RelayerConfig.ts
This can be used to test a viem-based or non-evm-based external listener.
> improve(relayer): Permit per-chain external listener customisation

- scripts/spokepool.ts
- src/interfaces/index.ts
This implementation is a bit hacky, but it works and is quite useful.
> improve(spokepool): Dump relayData hash on fill logs

- src/relayer/Relayer.ts
This skips an RPC call when the block number has not incremented beyond the last update cycle.
> improve(relayer): Make HubPoolClient update conditional

- src/adapter/BaseChainAdapter.ts
- src/clients/bridges/AdapterManager.ts
- src/clients/bridges/EthereumAdapter.ts
Adds lightweight Ethereum adapter that inventory client can use to wrap ETH. Has no other side effects
> feat(InventoryClient): Wrap ETH on Mainnet

- src/dataworker/README.md
- test/Dataworker.loadData.fill.ts
- test/Dataworker.loadData.slowFill.ts
Same idea as https://github.com/across-protocol/sdk/pull/762
> improve: Remove FundsDeposited and FilledRelay mentions

- scripts/spokepool.ts
- scripts/utils.ts
This ensures that providers have cache and fallback behaviour.
> fix: Use CacheProvider in script utils

- src/common/Constants.ts
- src/dataworker/Dataworker.ts
- src/dataworker/DataworkerUtils.ts
This reverts commit 0823a68f1f70bed68150e2064b3449e9df6418d5.
> Revert "improve(arweave): Change arweave data key from list of chain ID's to map (#1916)

- src/clients/ProfitClient.ts
Inspired by SDK changes in https://github.com/across-protocol/sdk/pull/801 but not blocked by it
> improve: Remove unused gasMarkup parameter

- package.json
- yarn.lock
Resolve Zora not being an OP stack + not having a multicall
> fix(zora): update constants/sdk

- contracts/AtomicWethDepositor.sol
This is necessary to support Ink chain in the immediate future.
This reverts commit e683053364d96d737e8c20f57b0a722ab7adc067.
> chore(AtomicWethDepositor): Revert to current prod version

- package.json
- scripts/zkSyncDemo.ts
- src/clients/ProfitClient.ts
- src/utils/TransactionUtils.ts
- yarn.lock
This reverts commit 03e990ddfdb178cd03458e642891dde08316bb46.
Backed out as a precaution against any stuck transactions across any of the bots.
> Revert "improve: Use base fee multiplier option in SDK to resolve gas fees (#1969)"

- src/relayer/Relayer.ts
We need to use the right bigNumber comparison function.
> fix: use correct comparison function

- test/Dataworker.buildRoots.ts
- test/Dataworker.executePoolRebalances.ts
- test/Dataworker.executeRelayerRefunds.ts
- test/Dataworker.executeSlowRelay.ts
- test/Dataworker.loadData.fill.ts
- test/Dataworker.loadData.slowFill.ts
- test/Dataworker.proposeRootBundle.ts
- test/Dataworker.validateRootBundle.ts
- test/utils/SpokePoolUtils.ts
This function is redundant with fillV3Relay
> improve(test): Remove redundant fillV3() test function

- package.json
- src/clients/InventoryClient.ts
- src/clients/ProfitClient.ts
- src/clients/SpokePoolClient.ts
- src/dataworker/PoolRebalanceUtils.ts
- src/relayer/Relayer.ts
- src/utils/RedisUtils.ts
- test/Dataworker.executePoolRebalances.ts
- test/Dataworker.loadData.fill.ts
- test/Dataworker.loadData.slowFill.ts
- test/InventoryClient.RefundChain.ts
- test/ProfitClient.ConsiderProfitability.ts
- test/Relayer.BasicFill.ts
- test/TokenClient.TokenShortfall.ts
- yarn.lock
I think the main change that might affect prod are changes in src/clients/SpokePoolClient
> improve: follow up fixes to treating depositId's internally as BN

- package.json
- test/Dataworker.loadData.fill.ts
- test/Dataworker.loadData.slowFill.ts
- yarn.lock
Imports dataworker improvements from https://github.com/across-protocol/sdk/pull/849
I've tested this locally and it produces agreeing bundles
> improve(dataworker): Import verify fill fix

- src/common/Constants.ts
Allows relayer to support new changes from https://github.com/across-protocol/sdk/commit/2e3fbe4108392d5716620eb8d18a61f22e5efa06
there are no breaking chnages for relayers, only the dataworker functions
> feat: Bump to version 5

- package.json
- test/Dataworker.loadData.fill.ts
- test/Dataworker.loadData.prefill.ts
- yarn.lock
If repayment chain is not valid for input token, fallback to destination chain if not lite chain deposit
> hotfix: Update SDK to implement fallback repaymentChain behavior

- src/common/Constants.ts
To be merged anytime before the version is updated on-chain
> feat: Bump to config store version 6

- src/dataworker/Dataworker.ts
Will prevent attempting to double execute relayer refund roots post-migration. These executions wouldn't succeed on-chain due to merkle leaves already being executed but they're creating noise that we should avoid with this legacy event check.
> hotfix: Temporarily check legacy executed refund root event

- src/dataworker/Dataworker.ts
- src/libexec/RelayerSpokePoolIndexer.ts
Reverts across-protocol/relayer#2058
> Revert "hotfix: Temporarily check legacy executed refund root event"

- src/finalizer/utils/opStack.ts
Needed for L2 -> L1 finalizations.
> chore: assign Dr. Who USDC to the cctp finalizer

- package.json
- src/adapter/bridges/UsdcCCTPBridge.ts
- src/common/Constants.ts
- src/common/ContractAddresses.ts
- src/finalizer/index.ts
- src/finalizer/utils/opStack.ts
- src/utils/CCTPUtils.ts
- test/AdapterManager.SendTokensCrossChain.ts
- test/generic-adapters/AdapterManager.SendTokensCrossChain.ts
- test/generic-adapters/Arbitrum.ts
- test/generic-adapters/OpStack.ts
- test/generic-adapters/Polygon.ts
- yarn.lock
Takes advantage of latest constants, sdk and contracts NPM packages
> improve: Rename DoctorWho to Unichain and read CCTP domain from PUBLIC_NETWORKS

- package.json
- src/common/Constants.ts
- src/common/ContractAddresses.ts
- yarn.lock
Needs the sdk bump here https://github.com/across-protocol/sdk/pull/891
> feat: support unichain sepolia

- src/adapter/bridges/ArbitrumOrbitBridge.ts
- src/adapter/bridges/PolygonWethBridge.ts
- src/common/Constants.ts
Last small change to make to better accommodate testnet.
> feat: fully support the rebalancer across testnet

- scripts/spokepool.ts
- Display both messageHash and relayDataHash on deposit.
- Skip relayDataHash on fill (not available due to missing message).
> improve(spokepool): Updates for new events

- src/scripts/validateRunningBalances.ts
Adds ~1.3 WETH known excess on Base
Adds page size and page count script flags
> improve(validateRunningBalances): Add support for pagination, add known excess

- package.json
- src/libexec/SpokePoolListenerExperimental.ts
- yarn.lock
This occasionally causes issues in production.
Also bump the viem version to include this fix for incorrect error handling on websockets:
https://github.com/wevm/viem/pull/3389
> improve(relayer): Log on empty block over websockets

- src/clients/ProfitClient.ts
- src/libexec/RelayerSpokePoolListener.ts
- src/libexec/RelayerSpokePoolListenerHTTPS.ts
- src/relayer/RelayerConfig.ts
- src/utils/EventUtils.ts
- src/utils/ProviderUtils.ts
...with support for custom headers. This is needed for Lens.
Having implemented this, 95% of the implementation is shared with the websocket variant. This can be refactored to make HTTPS or WSS transport configurable.
> feat: Add HTTPS-based external SpokePool listener

- package.json
- src/adapter/BaseChainAdapter.ts
- src/adapter/bridges/ZKStackBridge.ts
- src/clients/ProfitClient.ts
- src/clients/bridges/AdapterManager.ts
- src/clients/bridges/CrossChainTransferClient.ts
- yarn.lock
Requires `TOKEN_EQUIVALENCE_REMAPPINGS` to be set https://github.com/across-protocol/constants/pull/119
> improve: support wgho/lgho in the adapters

- package.json
- yarn.lock
> feat(Dataworker): Don't produce pool rebalance leaves for chains with no refunds but deposits

- src/finalizer/utils/cctp/l2ToL1.ts
This seems to be a quirk of cctpv2.
> fix(finalizer): Filter out ready (but pending) CCTP withdrawals

- src/finalizer/index.ts
Multicall chunk sizes are only set in Config.validate(), so make sure to call that after client initialisation.
> improve(finalizer): Respect finalizer multicall chunk size

- src/monitor/Monitor.ts
The bond token is monitored but not in `TOKEN_SYMBOLS_MAP`, so we need to query the contract directly to get its token information.
> fix: prefer obtaining monitored token info by querying contracts

- src/finalizer/utils/scroll.ts
- src/utils/ProviderUtils.ts
Description:
This pull request updates documentation and comments in two files for better clarity and consistency:
- In `src/finalizer/utils/scroll.ts`, the JSDoc comment for the `getScrollRelayContract` function is clarified to specify that the contract is "instantiated with the given signer".
- In `src/utils/ProviderUtils.ts`, the comment describing the backoff strategy is updated for improved readability, specifying an "exponential backoff" approach.
No functional code changes are included; these are purely documentation and comment improvements.
> Minor Documentation Improvements and Comment Clarifications

- src/common/Constants.ts
Description:  
This PR corrects the placement of the comment for the BSC chain in the CHAIN_CACHE_FOLLOW_DISTANCE object within Constants.ts.
> Minor Cleanup: Align BSC Comment in Constants File

- src/clients/InventoryClient.ts
- src/clients/bridges/CrossChainTransferClient.ts
- src/interfaces/InventoryManagement.ts
- src/monitor/Monitor.ts
- test/InventoryClient.InventoryRebalance.ts
- test/mocks/MockAdapterManager.ts
Duplicate of https://github.com/across-protocol/relayer/pull/2340
> fix: sync object keys across adapter clients

- src/interfaces/index.ts
- test/Dataworker.loadData.slowFill.ts
- test/Dataworker.loadData.unexecutableSlowFill.ts
- test/Relayer.BasicFill.ts
- test/Relayer.SlowFill.ts
- test/Relayer.UnfilledDeposits.ts
- test/utils/SpokePoolUtils.ts
- test/utils/utils.ts
Make tests use `Address` class more and better to prepare for upcoming [SDK change](https://github.com/across-protocol/sdk/pull/1131)
> improve: frontload test fixes to bump SDK

- src/dataworker/Dataworker.ts
Dynamically fetch SVM token programId
> feat: Dynamically fetch SVM token programId

- src/clients/BalanceAllocator.ts
- src/clients/TokenClient.ts
- src/common/ClientHelper.ts
- src/libexec/RelayerSpokePoolListenerSVM.ts
- src/relayer/RelayerClientHelper.ts
- src/utils/BlockUtils.ts
- src/utils/CCTPUtils.ts
- src/utils/ProviderUtils.ts
We don't currently pass in the redis client upon construction
> improve(SolanaProvider): Pass in redisClient

- src/clients/InventoryClient.ts
This on the margin might cause a withdrawal of L2 balances to be delayed but it also means we are less likely to cancel out pending L1 to L2 transfers by immediately withdrawing back to L1. That would cause a bad feedback loop.
> improve(InventoryClient): withdrawExcessL2Balances should ignore pending L1->L2 transfer amounts

- src/finalizer/utils/opStack.ts
> fix(OpStackFinalizer): Patch for OptimismPortal_Unproven revert custom error

- src/monitor/Monitor.ts
The SDK provides retry and error catching logic that we should not be skipping.
> fix: Make sure all svmProvider direct queries are wrapped by SDK utils

- package.json
- yarn.lock
> improve: Bump SDK to 4.3.36

- src/clients/SpokePoolClient.ts
In order to make a subsequent refactoring diff smaller.
> refactor(relayer): Frontload non-functional refactoring

- src/clients/bridges/AdapterManager.ts
Corrected Implementor → Implementer
> fix: typo in file

- src/adapter/bridges/OFTBridge.ts
Harden the formatting of address for OFT send a bit
> improve: make sure `EvmAddress`

- src/monitor/Monitor.ts
Better logging for ClosePDAs bot
> improve: Better logging for ClosePDAs bot

- src/relayer/Relayer.ts
Prefer to keep trying for a fill, rather than ignore it for up to 60 seconds.
> fix(relayer): Temporarily don't ignore Solana unprofitable fills

- src/libexec/RelayerSpokePoolListenerSVM.ts
SVM listener channels drop sporadically in production. Improve logging to diagnose why.
> improve(relayer): Catch and log errors on SVM listeners

- src/relayer/Relayer.ts
- src/relayer/RelayerClientHelper.ts
- src/relayer/RelayerConfig.ts
- test/Relayer.BasicFill.ts
- test/Relayer.SlowFill.ts
- test/Relayer.TokenShortfall.ts
- test/Relayer.UnfilledDeposits.ts
This lets us configure the message relay config based on destination chain.
> improve: choose which destination chains to send message relays

- src/scripts/validateRunningBalances.ts
Script has become out of date following the Address class changes
> fix(validateRunningBalances): Fix script

- src/finalizer/utils/cctp/l2ToL1.ts
- src/finalizer/utils/linea/l2ToL1.ts
Will give more info on unfinalized amounts.
> improve: log unfinalized amounts in more finalizers

- src/interfaces/index.ts
- src/monitor/Monitor.ts
Current logs of the invalid fills is hard to read. Trim down data that is logged for invalid fills.
> chore: Trim down data that is logged for invalid fills

- src/monitor/Monitor.ts
Log number of invalid fills per chain
> improve: Log number of invalid fills per chain

- scripts/hypercoreTransfer.ts
This script will be useful for demonstrating how Hypercore <> HyperEVM interactions work and help us build out production tooling. Its still a WIP but the PR contains the following useful flows:
- send token between HyperEVM <-> Hypercore
- query HyperEVM/Hypercore balances
> feat: start PoC script to facilitate hypercore <> hyperevm transfers

- src/utils/TransactionUtils.ts
Pulling this isolated change out of a larger PR to reduce the diff and ease review. The diff is disproportionately noisy relative to the change being made; no functional change intended.
> refactor(TransactionUtils): Minor cleanup

- src/relayer/index.ts
Observed today when Polygon had an oops.
> fix(relayer): Don't repeatedly log about degraded state

- src/clients/ProfitClient.ts
- test/ProfitClient.ConsiderProfitability.ts
- test/mocks/MockProfitClient.ts
- test/mocks/MockQuery.ts
- test/mocks/index.ts
Depends on https://github.com/across-protocol/sdk/pull/1232
> feat: account for `value_amount` in fill profitability estimation

- src/finalizer/utils/opStack.ts
The Blast bridge UI https://blast.io/en/bridge uses a special receive() function on the L2 Blast Bridge to withdraw ETH, instead of sending the ETH as WETH through the standard bridge.
This PR allows the finalizer to finalize such withdrawals, because they are emitted from a different contract than the L2 standard bridge.
> feat(Finalizer): Allow BlastFinalizer to finalize ETH withdrawals sent through L2 Blast Bridge

- src/dataworker/index.ts
Reverts across-protocol/relayer#2651
> Revert "log: Add more intense logging for debugging"
