across-protocol/relayer

src/clients/ClientHelper.ts
src/clients/ConfigStoreClient.ts
src/clients/DataworkerClientHelper.ts
src/clients/RelayerClientHelper.ts
src/clients/index.ts
src/dataworker/Dataworker.ts
src/interfaces/HubPool.ts
src/interfaces/SpokePool.ts
src/utils/AddressUtils.ts
src/utils/MerkleTreeUtils.ts
src/utils/index.ts
test/Dataworker.buildRoots.ts
test/Dataworker.loadData.ts
test/Relayer.BasicFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts
test/constants.ts
test/fixtures/Dataworker.Fixture.ts
test/utils/utils.ts

- Change key of `fillsToRefund` from `relayerAddress` to `destinationToken` since we need to group refunds for a given `repaymentChainId` by `destinationToken`
Follow up PR will implement:
- Implementing `amountToReturn` computation and logic

feat: Implement relayer refund root construction

---

src/clients/RateModelClient.ts

This PR adds a small temp workaround to enable bots to run without finding block numbers. See comment in code as to why this was done.

fix: add ability to run relayer for testnet

---

.eslintrc.js
src/clients/DataworkerClientHelper.ts
src/clients/HubPoolClient.ts
src/clients/RateModelClient.ts
src/clients/SpokePoolClient.ts
src/dataworker/Dataworker.ts
src/interfaces/HubPool.ts
src/interfaces/SpokePool.ts
src/utils/EventUtils.ts
src/utils/FillMathUtils.ts
src/utils/index.ts
test/Dataworker.buildRoots.ts
test/Dataworker.loadData.ts
test/HubPoolClient.DepositToDestinationToken.ts
test/HubPoolClient.RootBundleEvents.ts
test/RateModelClient.RealizedLpFeePct.ts
test/Relayer.UnfilledDeposits.ts
test/constants.ts
test/fixtures/Dataworker.Fixture.ts
test/fixtures/UmaEcosystemFixture.ts
test/utils/utils.ts

This PR does NOT fully implement `buildPoolRebalanceRoot`. It implements steps 1-3 in the list "To determine the amount to modify the running balances:" as described in the [ACROSS-V2 UMIP](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-157.md#constructing-the-poolrebalanceroot). 
This PR is already large so I'm going to stop here, and I've included a simple test to demonstrate how it works.
Checklist

Implement initial runningBalances computation in buildPoolRebalanceRoot

---

package.json
src/clients/MultiCallerClient.ts
src/utils/ContractUtils.ts
src/utils/TransactionUtils.ts
src/utils/index.ts
yarn.lock

A previous bad merge conflict resolution done in PR https://github.com/across-protocol/relayer-v2/pull/37/files removed a whole chunk of logic added in PR https://github.com/across-protocol/relayer-v2/pull/36. This PR adds this back.
Additionally, this PR updates how the contracts repo is used in accordance with the changes discussed in this https://github.com/across-protocol/contracts-v2/pull/155#discussion_r870087070 thread

feat: add back get target logic and update how we use `contracts-v2` export for `getContractInfoFromAddress`

---

src/clients/TokenClient.ts
src/utils/TransactionUtils.ts

**Changes:**
- WETH on Optimism should not have any approvals.
- polygon priority fee should scale more and only apply on that chain id.
- increase base fee scaler to ensure txs dont get stuck.

fix: skip WETH on optimism approval

---

src/utils/TransactionUtils.ts

Previous hot fix had an issue where maxPriorityFee was larger than base fee. This causes errors on mainnet. This pre reverts this to a more reasnoble setup.

fix: refine polygon fees

---

package.json
src/utils/EventUtils.ts
src/utils/index.ts

The Event util can sometimes make too manny parallel calls when dealing with a lot of events. This PR adds in a blue bird promise logic to limit the max concurrency to add stability to the bots.

fix: fix add blue bird work around

---

test/Dataworker.buildRoots.ts

Test that dataworker works in concert  with relayer to include 1 wei fills to slow relay root. Longer term we should consider allowing the dataworker to include zero fills. The reason we exclude zero fills at the moment is because to identify the "first" fill for a deposit, we sort fills by fillAmount. Instead, we should sort by fillAmount and then block number

improve: add "zero"/1 wei slow fill test to dataworker

---

src/clients/HubPoolClient.ts
src/dataworker/Dataworker.ts
src/dataworker/DataworkerClientHelper.ts
src/dataworker/index.ts
test/Dataworker.executePoolRebalances.ts
test/Dataworker.executeRelayerRefunds.ts
test/Dataworker.executeSlowRelay.ts
test/Dataworker.proposeRootBundle.ts
test/Dataworker.validateRootBundle.ts

I used this PR to execute leaves in prod (and propose a new bundle). It cuts down the number of spoke pool clients from 5 to 2
1 For the pending root bundle, used in validation and execution logic
1 For the next root bundle, used in propose logic

improve: Refactor leaf executor implementation

---

package.json
src/clients/ConfigStoreClient.ts
src/common/ClientHelper.ts
yarn.lock

Signed-off-by: Matt Rice <matthewcrice32@gmail.com>
THis error shows up if you install redis alongside @google-cloud/trace-agent.
```
uncaughtException: Cannot read property 'prototype' of undefined
TypeError: Cannot read property 'prototype' of undefined
at wrapCreateStream (/across-relayer/node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-redis.js:145:36)
at Object.patch (/across-relayer/node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-redis.js:167:13)
at /across-relayer/node_modules/@google-cloud/trace-agent/build/src/trace-plugin-loader.js:93:23
at Array.reduce (<anonymous>)
at ModulePluginWrapper.applyPlugin (/across-relayer/node_modules/@google-cloud/trace-agent/build/src/trace-plugin-loader.js:87:33)
at …
```

fix: fix trace-agent issue by renaming package

---

src/clients/SpokePoolClient.ts

We can't take advantage of the `SPOKE_ROOTS_LOOKBACK_COUNT` variable without this fix because we can't sort root bundle relays in descending order

Fix: Store root bundle relays with block

---

package.json
src/dataworker/Dataworker.ts

_buildPoolRebalance root was anecdotally a slow function, so this caches the return of that for a given block range input﻿

improve: Cache pool rebalance roots for block ranges

---

src/dataworker/PoolRebalanceUtils.ts

`constructPoolRebalanceLeaves()` does not currently handle case where 1 L1 token has realizedLpFees but the others are empty.

fix: Construct pool rebalance leaves from partially empty realizedLpFees/runningBalances

---

src/clients/SpokePoolClient.ts
src/clients/TokenTransferClient.ts
src/clients/index.ts
src/interfaces/Token.ts
src/interfaces/index.ts
src/monitor/Monitor.ts
src/monitor/MonitorClientHelper.ts
src/monitor/MonitorConfig.ts
src/utils/EventUtils.ts
src/utils/FormattingUtils.ts
test/Monitor.ts

Currently the monitoring report only takes into account Across V2 relays/refunds. This leads to unexplained changes in relayer balances from to time due to:
1. Interactions with Across V1 (relays, refunds)
2. Automated and manual inventory management.
3. V2 bond payments/refunds.
This PR adds logic to report the above interactions.
Notes: This can create noise when the monitor bot runs in non-looping mode (POLLING_DELAY = 0) because if there are mismatching v1 relays/refunds for example in the 30m window (current monitoring bot interval), the net transfer balance within that window would not be 0 (we lost some v1 relays or refunds from before the window). This problem should go away once we switch to looping mode as the TokenTransferClient's transfer cache would then contain all transfers …

feat: Report categorized non-v2 transfers from relayers

---

src/clients/SpokePoolClient.ts
src/interfaces/HubPool.ts
src/monitor/Monitor.ts
test/Monitor.ts

Current pending refunds calculation only checks if the bundle has been executed in HubPool (rebalance tree has been executed). This doesn't mean the actual refunds (leaves of relay refund tree) have been executed on destination chains.

fix: Fix pending refunds calculation in relayer report

---

src/monitor/MonitorConfig.ts

The relayer balance report depends on spokePoolBlocks but it's run in a separate bot that does not have unknown relayer alert enabled.

fix: Always populate spokePoolBlocks in monitor config

---

src/clients/TokenClient.ts
src/relayer/RelayerConfig.ts
test/TokenClient.Approval.ts

Current case will have bot runner send out a token allowance for each token for each chain, suboptimal

improve: Only set allowances for tokens with non zero balances

---

.gitignore
src/clients/BundleDataClient.ts

Currently the logic looks at the starting block of the next bundle, which only works if the current pending bundle has not been executed in HubPool. Once it has been executed, the starting block would be in the future while the ending block is still in the past.

fix: Look at the right starting block when calculating pending refunds

---

src/monitor/Monitor.ts
src/monitor/MonitorConfig.ts
src/utils/NetworkUtils.ts

symbol can't be called on the native token and there was a variable name mismatch between the config and implementation.

fix: fix minor bugs in balance monitor

---

src/clients/BundleDataClient.ts
src/clients/InventoryClient/InventoryClient.ts
src/monitor/Monitor.ts
test/Dataworker.loadData.ts
test/Monitor.ts
test/mocks/MockBundleDataClient.ts

JS passes objects by reference, so when we changed `loadData` to return data from the cache (when possible), we sometimes run into bugs when we mutate that return value, causing corrupted data to be loaded from the cache on the next run.
This PR changes `loadData` to always return a deep cloned data from the cache

fix: Deep clone data from cache before returning from loadData()

---

src/clients/BundleDataClient.ts
src/clients/InventoryClient/InventoryClient.ts
src/common/Config.ts
src/monitor/Monitor.ts
src/relayer/RelayerClientHelper.ts
test/Dataworker.loadData.ts
test/Monitor.ts
test/mocks/MockBundleDataClient.ts

There are now two types of possible pending refunds:
- Those contained in validated root bundles (i.e. the root bundle passed liveness and all root bundle leaves were executed)
- Those contained in unvalidated root bundles (i.e. the next potential root bundle to be proposed or contained in a pending liveness)
This makes it a bit easier to look up N validated root bundles into the past to find pending refunds. The main change with this is that refunds in the next potential root bundle are now grouped together with those in a pending bundle that has not passed liveness.

improve: Consolidate bundle refund calculations and look up to N root bundles into past for pending refunds

---

src/clients/BalanceAllocator.ts
src/clients/MultiCallerClient.ts
src/common/ClientHelper.ts
src/dataworker/Dataworker.ts
src/utils/ExecutionUtils.ts
src/utils/SignerUtils.ts
src/utils/TransactionUtils.ts
src/utils/index.ts
test/Dataworker.executePoolRebalances.ts
test/fixtures/Dataworker.Fixture.ts

This adds a way to include a value to a transaction sent to the multicaller client. Any value transactions are sent (in parallel) _before_ the multicall batches are sent.

feat: dataworker should send ETH to hub pool when executing arb transactions

---

src/utils/ProviderUtils.ts
src/utils/TypeGuards.ts

In the case where not enough providers succeed, this PR includes all error data from one of the errors so ethers can decode the information returned by the contract.
In the cases where the quorum is not met despite enough successful providers, this _does not_ change the behavior. In those cases, the assumption is that the error is primarily related to quorum and not related to an on-chain revert message.

fix: correctly pass back provider errors when all providers fail

---

src/clients/MultiCallerClient.ts

Right now, the bot is set up to pre-fund the hub pool with ETH for the arbitrum calls that it's about to make. However, this transaction is reverting due to a typo in the MulticallerClient. This was not caught in the tests because this error is caught and logged, so the tests don't see it as an error.

fix: fix error in eth funding transaction

---

src/monitor/Monitor.ts

When there are slow fills, BundleDataClient#loadData counts them as valid fills (but with repayment chain id = 0) but the refunds are skipped because they are for slow fills. This creates a weird entry for chain id = 0 with valid fills for a token but no refunds. We need to skip these.

fix: Skip empty refunds

---

.gitignore
src/clients/InventoryClient/InventoryClient.ts
src/clients/TokenClient.ts
test/InventoryClient.InventoryRebalance.ts
test/InventoryClient.RefundChain.ts
test/utils/utils.ts

Context: Currently inventory management can oversend funds to meet a shortfall. Consider the following scenario:
1. Polygon currently has a balance of 5 WETH with 20 WETH coming. The target allocation is 25 WETH so once refunds come in a few hours, the target allocation is still met.
2. There's a deposit of 10 WETH that needs to be filled on Polygon. This is a shortfall as we currently only have 5 WETH standing.
3. Currently inventory management would send 20 WETH total (triggered by the shortfall) to also meet the target alloc of 25 WETH. This means that after refunds, the final balance would be 45 WETH, which is almost double the target alloc.
4. This PR updates the logic so that it would only send 10 WETH over (exactly enough to cover the shortfall deposit). This will get refunded on …

feat: Consider upcoming refunds when calculating relayer fund rebalancing

---

src/clients/MultiCallerClient.ts
src/relayer/Relayer.ts
src/relayer/RelayerConfig.ts
src/relayer/index.ts
src/utils/FillUtils.ts

MAX_RELAYER_DEPOSIT_LOOK_BACK sets how far we look events up from, but this is a fixed number of blocks per chain, not a fixed number of time per chain. So, assuming the block lookback !== time lookback, there will be some false positive unfilled deposits seen by the relayer. Imagine a deposit on a chain that looks back 2 hours is filled by a relay on a destination chain that only looks back 1 hour, the relayer will think that deposit is unfilled when in fact it is.
This PR adds a cushion to the relayer to throw away any unfilled deposits older than half the block length of the `MAX_RELAYER_DEPOSIT_LOOK_BACK` value. This is a bit hacky but it works empirically for now and will allow us to speed up the bot a lot by limiting its lookback

fix: Add cushion to enable MAX_RELAYER_DEPOSIT_LOOK_BACK to work

---

index.ts
src/clients/SpokePoolClient.ts
src/common/ClientHelper.ts
src/dataworker/index.ts
src/finalizer/index.ts
src/interfaces/SpokePool.ts
src/monitor/MonitorClientHelper.ts
src/relayer/RelayerClientHelper.ts

- Finalizer shouldn't have to load Fill/Deposit events for example, while Relayer and Dataworker shouldn't have to load TokensBridged events
- This PR allows bots to define which events to lookup per SpokePoolClient update.
This PR also limits number of events searched in Finalizer, which is very slow since there is an async request per TokensBridged event to check on its finalization status

feat: Reduce number of events searched per bot

---

package.json
src/clients/InventoryClient/AdapterManager.ts
src/clients/InventoryClient/ArbitrumAdapter.ts
src/clients/InventoryClient/BaseAdapter.ts
yarn.lock

This [thread](https://github.com/ethers-io/ethers.js/discussions/2849) suggests that higher minor versions of hardhat-ethers and ethers will remove this error: "missing revert data in call exception; Transaction reverted without a reason string"

improve: bump ethers and hardhat-ethers packages

---

src/clients/SpokePoolClient.ts
src/common/ClientHelper.ts
src/dataworker/Dataworker.ts
src/dataworker/DataworkerConfig.ts
src/dataworker/PoolRebalanceUtils.ts
src/dataworker/index.ts
src/scripts/validateRootBundle.ts
test/Dataworker.blockRangeUtils.ts
test/Dataworker.validateRootBundle.ts

If follow distance exists, then look up events only until HEAD-follow. This can be used specifically in looping mode to avoid any issues where this client sees incorrect events near HEAD, but can't re-load them since the Dataworker is running in looping mode. This could ultimately cause the dataworker to propose an incorrect root bundle. Even worst, the same looping instance will never consider this root bundle invalid. So, to mitigate this, use a follow distance in spoke clients  specifically in the dataworker when loading spoke pool events.
The follow distance is set to replace the BUNDLE_BLOCK_RANGE_BUFFER. Both block buffers do the same thing, but this PR changes the SpokePoolClient to follow HEAD instead of the Dataworker endblocks to follow the SpokePoolClient.latestBlockNumbers. …

improve: Use configurable follow distance in SpokePoolClient

---

src/dataworker/Dataworker.ts

Log the L1 token symbol we're triggering `exchangeRateCurrent()` for instead of token address

improve: Make exchangeRateCurrent log more succinct

---

scripts/constructEmergencyRoot.ts
src/clients/HubPoolClient.ts
src/common/Constants.ts
src/dataworker/Dataworker.ts

- Should be able to skip over spoke bundles in Dataworker.execute logic. This is pretty simple, as the Dataworker can just ignore these bundles when executing leaves. Additionally, when proposing new bundles, the Dataworker never considers RootBundles relayed to the spoke pools, so there isn't any other logic to change besides adding a filter to the execute methods.
- HubPoolClient should be able to ignore admin root bundles. Imagine the case where a PoolRebalanceLeaf is manually constructed and proposed, and not disputed on purpose, even though its conventionally "invalid". How should the Dataworker deal with it? For now, I've filtered out Propose and Executed events but curious if this is sufficient or too much?

feat: Add logic to ignore admin bundles 

---

src/clients/bridges/ArbitrumAdapter.ts
src/clients/bridges/PolygonAdapter.ts

Currently UMA is not listed as one of the tokens that relayer's inventory management can bridge to Polygon

improve(inventory): support UMA bridging to Polygon

---

src/relayer/Relayer.ts
test/Relayer.BasicFill.ts

Currently when run in looping mode with POLLING_DELAY of 30s, the relayer bot sometimes double fill (second fill for the same deposit fails, which is a waste of gas). This happens very frequently for even smaller POLLING_DELAY such as 10s.
This solution keeps track of filled deposits in memory so that when run in looping mode, the relayer wouldn't try to do double fill when the first fill is still pending.

improve(relayer): Track which deposits the relayer has tried to fill so it doesn't double fill (waste of gas)

---

src/common/Config.ts
src/common/Constants.ts

Enables the user to avoid manually setting MAX_RELAYER_DEPOSIT_LOOK_BACK
in their environment, thereby making the overall configuration simpler. The default
values match the configuration recommended in the Across GitBook.
Ref: ACX-73

improve: Set defaults for relayer deposit lookback

---

src/clients/BundleDataClient.ts

Motivation: Proposer is disputing itself when current bundle is not correctly pulling back funds from L2 to account for "excess" tokens left on SpokePool following a slow fill payment sent in previous bundle that was fully filled before the slow fill leaf was executed. In particular, [this function](https://github.com/across-protocol/relayer-v2/blob/master/src/dataworker/PoolRebalanceUtils.ts#L163) contains the bug
Summary:
- `getFillDataForSlowFillFromPreviousRootBundle` is supposed to return the last fill that completed a slow fill, but it searches for that fill within `allValidFills` which contains all blocks up until HEAD.
- This is an issue because the bundle end blocks all lag HEAD by ~20-30 mins, so its possible that the last fill completing a slow fill was sent very recently …

fix: BundleDataClient.loadData should filter allValidFills younger than bundle end block

---

src/dataworker/Dataworker.ts

Dataworker needs to be aware of required L1 call value for executing pool rebalance leaves, not sure why 0.034 was set before that was a mistake it should have been 0.13 but setting this value too high doesn't cause errors its just capital inefficient

improve: Change gas requirement for Arbitrum l1 --> l2 messages

---

src/clients/BundleDataClient.ts
src/dataworker/Dataworker.ts
src/dataworker/DataworkerUtils.ts
src/dataworker/PoolRebalanceUtils.ts
src/scripts/validateRootBundle.ts

Same motivation and logic as https://github.com/across-protocol/relayer-v2/pull/221 but this filter on fillWithBlock is set higher in the function.
I don't know if this fixes the underlying bug, but the current situation is that sometimes proposer and disputer see the exact same deposits and fills in the range but construct different `netSendAmounts/runningBalances`, with the disputer consistently seeing lower values.
My guess is that there is some bug in `dataworker/PoolRebanceUtils.ts/subtractExcessFromPreviousSlowFillsFromRunningBalances()` which could only lower the net send amounts.

fix: Dataworker should filter out all deposits younger than bundle end block

---

src/clients/MultiCallerClient.ts
src/dataworker/Dataworker.ts
src/dataworker/PoolRebalanceUtils.ts
src/relayer/Relayer.ts
test/Relayer.IterativeFill.ts

Bug: uses most recent proposal instead of validated proposal.
This would cause problems if a proposal were to be disputed, then the next proposer would never propose again since there would never be a relayer refund root relayed to EthereumSpokePool with the matching root

fix: shouldWaitToPropose should use most recently validated proposal

---

src/dataworker/Dataworker.ts

This mitigates any timing issues with stuck leaves, oldest ones should be unstuck first

improve: execute leaves from oldest to newest

---

src/finalizer/index.ts

L2 block times are hard to predict so we shouldn't filter out events that are "too old", but we can continue to filter out TokensBridged events that are "too young" because eventually they'll be old enough

improve(finalizer): Don't filter out older token bridge events

---

src/dataworker/Dataworker.ts
src/dataworker/DataworkerUtils.ts
src/dataworker/PoolRebalanceUtils.ts

This is a bug but AFAICT did not lead to any issues in production. The following situation highlights the bug:
- There was some partial fill in bundle 1.
- Bundle 1 sends slow relay funds.
- Bundle 1 is executed.
- We’re now trying to build bundle 2.
- Our mainnet end block for bundle 2 is before the execution block for bundle 1 because of our buffer.
I think in this case, we consider bundle 1 as not valid yet (reasonable, since this bundle hasn’t really “seen” those blocks yet). This means [this check](https://github.com/across-protocol/relayer-v2/blob/587b9039d27cab2fd0775e08934dd78c8628413f/src/clients/HubPoolClient.ts#L189) returns false for the bundle that would have contained the first fill. This means [this call](https://github.com/across-protocol/relayer-v2/blob/587b9039d27cab2fd07 …

fix(dataworker): Check for executed pool rebalance leaves until proposal block, not bundle end block

---

package.json
yarn.lock

Keeping arbitrum-sdk version updated in anticipation of nitro upgrade to the AVM﻿

chore: Bump arbitrum-sdk version to 2.0.9

---

index.ts
src/dataworker/index.ts
src/finalizer/index.ts
src/monitor/index.ts
src/relayer/index.ts

This PR addresses two main observations:
1. The existing exception handling recursively calls into the same function that experienced the exception. With a non-zero POLLING_DELAY, this increase stack usage and will leak memory.
2. For some unknown reason, Redis client instances don't appear to be GC'ed after they have gone out of scope. This means that Redis connections are maintained indefinitely - even though they are not used. When an exception is caught by the top-level handler, this results in a new connection being established. At some point, the server will stop accepting new connections. I have seen the bot hang in this scenario.
The fix for (1) is easy enough - exceptions that are otherwise unhandled will now ripple all the way back to the top-level index.ts, which avoids …

improve: bot exception handling

---

src/dataworker/Dataworker.ts

The dataworker currently waits until after the most recently proposed bundle has been executed, and that means it not only waits for the PoolRebalanceLeaves to be executed but also for the subsequent
RelayerRefundLeaf to be executed on Mainnet. In serverless mode, this  means the dataworker will wait at least 2 iterations between proposing new bundles. In practice, the buffer is ~2 hours after
the newest RelayerRefundLeaf on Mainnet is executed, however this buffer can be a lot longer than expected if the leaf executions are delayed for some reason. It's reasonable to start this buffer
after the oldest RelayerRefundLeaf assuming the buffer is set to something reasonable like >30 mins.
﻿Signed-off-by: nicholaspai <npai.nyc@gmail.com>

improve(dataworker): Buffer between proposals should start at block of oldest executed relayer refund leaf, not newest

---

package.json
yarn.lock

Context: https://linear.app/uma/issue/ACX-129/lost-lines-in-slack-logs-from-across-bots
TLDR; the financial-templates-lib wasn't not updated in relayer-v2

fix(logging): Bump financial-templates-lib version to get updates to the logger library

---

index.ts
src/common/ClientHelper.ts
src/dataworker/DataworkerClientHelper.ts
src/dataworker/index.ts
src/finalizer/index.ts
src/monitor/MonitorClientHelper.ts
src/monitor/index.ts
src/relayer/RelayerClientHelper.ts
src/relayer/index.ts
src/scripts/validateRootBundle.ts

At very least this will leave fewer copies of the private key in memory.
For gckms configurations it should also save a few redundant connections
to Google on each run of the bot.
Ref: ACX-40
Ref: ACX-122

improve: Consolidate use of getSigner() during startup

---

src/clients/MultiCallerClient.ts
src/common/Constants.ts

This change modifies the bot's transaction handling when a chain has > x
relay fills to be submitted in a multicall transaction. The approach is to
basically give it a lobotomy, so it just truncates the list of transactions to
ensure that we will always fit within the configured chunk size limit.
The current implementation doesn't work as intended due to the fact that
successive chunks are submitted in parallel, so they all tend to get the
same nonce. This means that a maximum of one multicall txn can succeed
per chain. On top of this, the successful multicall seems to often be
the smallest, which means that a large number of fills are "blocked"
until demand slows down and the bot has a chance at submitting the same
multicall txn without any new Deposit candidates arriving.
The change …

improve: Drop excess per-chain multicall chunks

---

src/clients/ProfitClient.ts
test/ProfitClient.PriceRetrieval.ts

Today we had many incidents where various bots were unable to retrieve
prices from CoinGecko. In each incident, *all* requested token prices
were unavailable. This indicates either a network/transport issue, or
some error over at CoinGecko. Unfortunately I wasn't able to see any
logging of the underlying cause (maybe I wasn't looking in the right
place).
In any case, this change introduces the following modifications:
- Bundle token price requests, such that we perform one HTTP request
in total, instead of 1 per token (currently 7).
- When exceptions occur during retrieval and parsing, ensure that the
underlying cause is logged.
An additional part of this PR was to support retries on the CoinGecko HTTP
request (nominally 2), but that was stripped out after feedback from
David.
Ref: …

improve: Reduce overheads in CoinGecko price retrieval

---

src/clients/bridges/BaseAdapter.ts
test/AdapterManager.getOutstandingCrossChainTokenTransferAmount.ts

Details: https://linear.app/uma/issue/ACX-14/monitor-should-track-l1-l2-bridged-funds-from-hubpool-to-spokepool

improve(relayer inventory management): Match deposits and finalizations by amount

---

src/clients/SpokePoolClient.ts
test/SpokePoolClient.SpeedUp.ts

After a user performed a deposit ([SpokePool.sol#L246](https://github.com/across-protocol/contracts-v2/blob/b15ae29e6824cd058d6d5bba2ebe2c9a32389262/contracts/SpokePool.sol#L246)) via the `SpokePool` contract, they can additionally call `speedUpDeposit()` ([SpokePool.sol#L315](https://github.com/across-protocol/contracts-v2/blob/b15ae29e6824cd058d6d5bba2ebe2c9a32389262/contracts/SpokePool.sol#L315)) in order to increase the relayer fee they are willing to pay. `speedUpDeposit()` will then emit the `RequestedSpeedUpDeposit` event, notifying Spoke Pool clients that a deposit's relayer fee has changed ([SpokePoolClient.ts#L372](https://github.com/across-protocol/relayer-v2/blob/7290c3ce63e216f22a6b21f9ff2310b72c4dd4ed/src/clients/SpokePoolClient.ts#L372)).
The event is handled by adding the …

fix(spokepoolclient): invalid deposit IDs during speed up could cause denial of service

---

src/clients/SpokePoolClient.ts
test/Relayer.UnfilledDeposits.ts
test/SpokePoolClient.SpeedUp.ts

cc to @pleasew8t on this writeup:
After a user submitted a speed up request via `speedUpDeposit()` ([SpokePool.sol#L315](https://github.com/across-protocol/contracts-v2/blob/b15ae29e6824cd058d6d5bba2ebe2c9a32389262/contracts/SpokePool.sol#L315)) for a deposit, the Spoke Pool client will update the existing deposit with the new relayer fee. This is done by overwriting the updated deposit in the global `deposits` object, as shown below:
```ts
for (const destinationChainId of Object.keys(this.deposits))
for (const [index, deposit] of this.deposits[destinationChainId].entries()) {
const speedUpDeposit = this.appendMaxSpeedUpSignatureToDeposit(deposit);
// update this.deposits with sped up deposit, overwriting old deposit
if (speedUpDeposit !== deposit) this.deposits[destinationChainId][index] …
```

fix: Apply modified relayer fee pct to depositsWithBlocks

---

src/clients/ConfigStoreClient.ts
src/clients/SpokePoolClient.ts
src/common/ClientHelper.ts
src/common/Config.ts
src/utils/EventUtils.ts

Forks can happen on chains such as Polygon. We need to add support for following distances to make sure we only fill deposits that have been finalized (and not subject to forks being undone).

improve(relayer): Add a per-network following distance to spoke pool's event search config

---

package.json
src/clients/MultiCallerClient.ts
src/clients/ProfitClient.ts
src/clients/bridges/BaseAdapter.ts
src/common/ClientHelper.ts
src/relayer/Relayer.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts
test/Dataworker.blockRangeUtils.ts
test/ProfitClient.ConsiderProfitability.ts
test/ProfitClient.PriceRetrieval.ts
test/Relayer.BasicFill.ts
test/Relayer.IterativeFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/fixtures/Dataworker.Fixture.ts
test/mocks/MockProfitClient.ts
yarn.lock

Originally reviewed in https://github.com/across-protocol/relayer-v2/pull/212

feat(relayer): Consider gas cost when calculating profitability

---

src/clients/ProfitClient.ts
test/Monitor.ts
test/ProfitClient.PriceRetrieval.ts

**Breaking change:** https://github.com/across-protocol/relayer-v2/pull/261 introduced an enableProfitability flag that, when set to false, skip all prices and gas cost updates in ProfitClient#update(). This can be useful for the relayer when we want to disable profitability check.
**Problem:** However, the dataworker also needs to use the ProfitClient to calculate the current volume of deposits when deciding if the volume is big enough to propose a bundle. Since the dataworker has enableProfitability = false, this stops ProfitClient from fetching prices and thus breaks the dataowker's volume calculation (it's always 0).
**Solution:** Allow ProfitClient to fetch prices in update() regardless of the enableProfitability flag.
**Testing:** An extra unit test is added to ensure prices are …

fix(profit client): Allow fetching CG prices when relay gas profitability is disabled

---

src/dataworker/PoolRebalanceUtils.ts
src/utils/FormattingUtils.ts

1. Fee formatting is incorrect:
SlowRelay
root:0xc8a05438...
leaves:
0: {"depositor":"0xD275E5cb","recipient":"0xD275E5cb","amount":"15,000,000.00","depositId":50372,"originChain":10,"destinationChain":1,"destToken":"USDC","realizedLpFee":"754,528,997.61%","relayerFee":"727,688,639.33%"}
2. Slack message for new bundle currently prints out when there are no slow fills
SlowRelay
root:0x00000000...
leaves:
when there are no slow relay leaves which is confusing as it looks like an error. We should explicitly say "No slow relay leaves"

improve(bundle logging): Fix fee formatting and explicitly say when there are no slow relay leaves

---

src/common/ClientHelper.ts

After a recent change in ProfitClient, we became a bit too strict with CG price failures. We can tolerate these failures in monitor and dataworker bots. Dataworker would not try to propose any bundles if price fetches fail as the volume would be 0).

fix(dataworker, monitor): Don't throw errors on CG prfice fetch errors

---

src/common/ClientHelper.ts
src/dataworker/DataworkerClientHelper.ts
test/Monitor.ts
test/fixtures/Dataworker.Fixture.ts

I reexamined current uses of ProfitClient as it's automatically instantiated and updated as part of the common clients. This means all bots use it although only 2 really need it:
1. Dataworker needs ProfitClient to decide whether there's enough volume to propose a bundle
2. Relayer uses ProfitClient to decide whether a fill is profitable. But profitability is currently disabled so it doesn't need those prices really.
Since the other bots don't need ProfitClient, we can separate it from CommonClients and only specifically instantiate/call update() for the dataworker + relayer. This will significantly reduce the price fetch volume and subsequently alert noise.

fix(profit client): Only instantiate/update profit client for dataworker + relayer

---

src/clients/ProfitClient.ts
src/clients/SpokePoolClient.ts
src/interfaces/SpokePool.ts
src/relayer/Relayer.ts
src/relayer/RelayerConfig.ts
src/relayer/index.ts
src/utils/DepositUtils.ts
src/utils/TransactionPropBuilder.ts
test/Dataworker.buildRoots.ts
test/ProfitClient.ConsiderProfitability.ts
test/Relayer.BasicFill.ts
test/Relayer.IterativeFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts
test/SpokePoolClient.SpeedUp.ts
test/SpokePoolClient.ValidateFill.ts

By overriding `deposit.relayerFeePct`, the `SpokePoolClient` inadvertently leads to the `relayer` sending invalid fills with an incorrect `relayerFeePct`. This could lead to a double spend attack where a depositor receives their full deposit, requests a speedup on their deposit, and then receives another full deposit. In the second case, the fill is invalid, so this is a relayer bug.
The solution is:
- in `SpokePoolClient.appendMaxSpeedUpSignatureToDeposit` add a new field to deposit instead of overriding the `relayerFeePct`, name it `newRelayerFeePct`
- In `Relayer.fillRelay` if `fill.modifiedRelayerFeePct !== undefined` then call `fillRelayWithUpdatedFee()` instead of `fillRelay` on the `SpokePool` contract and pass in the `newRelayerFeePct` and `depositorSignature` params.
In the case …

fix: SpokePoolClient incorrectly overrides deposit.relayerFeePct when a RequestedSpeedUp event is emitted

---

src/dataworker/Dataworker.ts

https://github.com/across-protocol/relayer-v2/commit/2f3ee963eb6399b48fca4a0ecbfbf59d51b4df64 only changed the logging for slow relay leaves but not relayer refund leaves

fix(dataworker): Change missed logging for leave execution failure to warn

---

src/clients/InventoryClient.ts

Currently if bundle refunds calculation fails, fills will be blocked complete.y This allows gracefully falling back to Mainnet for refunds as it's always easier to rebalance from Mainnet to L2s if needed.

fix(relayer): Default to Mainnet for refunds if bundle calculation fails

---

src/clients/ProfitClient.ts

For some reason, the numbers in totalGasCosts are written to as BigNumber, but when they're read, they somehow become strings. No other code writes to it, so not sure where this weird BigNumber -> string conversion happens. I suspect this happens somehow at when TS is compiled into JS as TS would not allow such a type mismatch.
I discovered this when running the relayer and adding some logs:
2022-08-31 16:35:22 [debug]: {
"at": "ProfitClient",
"message": "totalGasCostWei",
"totalGasCostWei": "55022680789668",
"type": "string",
"correct_type": "object",
"totalGasCostWeiString": "55022680789668",
"bot-identifier": "kev-local"
}
The logging code I added:
this.logger.debug({
at: "ProfitClient",
message: "totalGasCostWei",
totalGasCostWei,
type: typeof totalGasCostWei,
correct_type: typeof …

fix(relayer): Convert gas cost to BigNumber explicitly

---

src/common/Constants.ts
src/relayer/RelayerConfig.ts

Third-party relayers should not need to configure this to avoid filling
unprofitable relays.

improve(ProfitClient): Safe default for minRelayerFeePct

---

src/utils/GckmsUtils.ts

This PR allows us to provide a custom configuration to the cloud storage initialization used for GCKMS retrieval. This should enable us to quickly deal with retry issues on the fly.

feat: add retries to cloud storage

---

src/clients/SpokePoolClient.ts
src/relayer/Relayer.ts
src/utils/FillUtils.ts
test/Relayer.BasicFill.ts
test/Relayer.UnfilledDeposits.ts

Currently the relayer could fill a deposit multiple times if their previous fills were considered invalid. This PR adds protection against potentially making multiple invalid fills for the same deposit.

feat(relayer): Skip deposits with invalid fills from the same relayer

---

src/clients/HubPoolClient.ts
test/Dataworker.validateRootBundle.ts
test/Relayer.UnfilledDeposits.ts

During the HubPool client update, it processes `ProposeRootBundle` events emitted by the `HubPool.sol` contract ([HubPoolClient.ts#L415](https://github.com/across-protocol/relayer-v2/blob/b73390d6955ceea77ec06c7ad62bc504668c8330/src/clients/HubPoolClient.ts#L415)). During this process, it attempts to cast each element in the `bundleEvaluationBlockNumbers` array of the proposed bundle to a `Number` using `toNumber()` ([HubPoolClient.ts#L425](https://github.com/across-protocol/relayer-v2/blob/b73390d6955ceea77ec06c7ad62bc504668c8330/src/clients/HubPoolClient.ts#L425)).
However, the `proposeRootBundle()` function in `HubPool.sol` types the `bundleEvaluationBlockNumbers` array as `uint256[]` ([HubPool.sol#L567](https://github.com/across-protocol/contracts-v2/blob/9656a972da602243943bd7e20c0654 …

fix(dataworker): Address HubPool Client Root Bundle Proposal Denial of Service

---

src/common/Constants.ts

Admin bundle 357 replaces bundles 322 and 321 that cannot be executed on current Ethereum_SpokePool. 357 is executed but won't be able to be reproduced by dataworker since its construction bypasses dataworker logic. When Ethereum_SpokePool is upgraded so that 322 and 321 could be executed, we should NOT execute these or it will result in a deficit of USDT and excess payment to the relayer

chore: Ignore bundles on chain 1 with USDT payments

---

src/clients/bridges/OptimismAdapter.ts

Our DepositFinalized event query logic in Optimism is fairly complex, as it needs to filter by the from address, which can be different for different cases:
1. For relayer inventory management, from is the relayer itself for ERC-20 tokens and a special atomic weth depositor contract for WETH.
2. For hub pool -> spoke pool, from is the hubpool
We have a bug in (1) where for weth transfer, we're missing events with from = atomic weth depositor. This causes the relayer to miss the finalization event and thinks WETH transfers are stuck.

fix(inventory): Fix the adapter event search config's from address or WETH transfer finalization on Optimism

---

package.json
yarn.lock

Arbitrum sdk's latest version is now 2.0.17 and was from before the Nitro upgrade. Their tutorials are all using 2.0.17 now so we should bump our version as well.

chore: bump arbitrum sdk to 2.0.17

---

src/clients/ProfitClient.ts
test/ProfitClient.ConsiderProfitability.ts

We would still error out if the total gas cost failed to fetch for any chain, but the error message would be more meaningful rather than a read property of undefined error.

fix(relayer): Correctly return 0 for total gas cost when it's not set

---

src/relayer/Relayer.ts
src/relayer/RelayerConfig.ts
test/Relayer.UnfilledDeposits.ts

There is a possibility that a Relayer has incorrectly submitted a fill, and then its code is patched, and then it is attempting to submit a valid fill, but the current logic would have the relayer skip this situation. This behavior should be able to be overridden manually by a bot runner.
Additionally, this PR fixes a false positive test that was succeeding for an unexpected reason

fix(relayer): Make decision to skip deposits with invalid fills from same relayer configurable by environment variable

---

package.json
yarn.lock

2.0.17 contains a bug that causes fetching the status of L2 -> L1 transfers to fail. 2.0.18 has the fix.

chore: Bump Arbitrum SDK from 2.0.17 to 2.0.18

---

src/common/Constants.ts

As the merge approaches, be a bit more conservative and
deliberate when selecting deposits to be filled.
FWIW these are ++easy to do, but it feels a bit cumbersome.
Still, if we've encouraged users to use the default values, and
if we have adjusted our own internal defaults, then it seems
like the right thing to do.

chore(constants): Align minimum default confirmations

---

src/dataworker/Dataworker.ts

Current log requires more work to understand which token is involved:
1-4. Executed RelayerRefundLeaf :herb:!: rootBundleId: 384
relayerRefundRoot: 0x1c4d6a3e3bc7fc3fc1f9e7d71333333a7673cb41892f098d24b7aa647bd4eeb4
Leaf: 16
chainId: 42161
token: 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8
amount: 908438221
tx: [0x9dc...edff4e](https://arbiscan.io/tx/0x9dc7bdb229c9907ff4f749dac789c41b52cae4a527a6114da85a12734dedff4e)
This PR would make it easier by printing out the token symbol instead of address.

improve(dataworker): Output token symbol in dataworker's leaf execution logs

---

package.json
src/clients/SpokePoolClient.ts
src/common/ClientHelper.ts
src/common/Config.ts
src/relayer/Relayer.ts
src/relayer/RelayerConfig.ts
src/utils/EventUtils.ts
src/utils/FillUtils.ts
test/Monitor.ts
test/Relayer.BasicFill.ts
test/Relayer.IterativeFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts
test/utils/utils.ts
yarn.lock

This PR was motivated by a finding that the Relayer was submitting duplicate partial fills because it could not see its own fills due to the follow distance applied to ALL events in the SpokePoolClient.
This PR (1) applies the follow distance only to Deposit events and (2) isolates the logic to the Relayer bot so other bots are not affected

improve(relayer): Move follow distance logic to Relayer

---

src/clients/SpokePoolClient.ts
src/common/ClientHelper.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts
test/Relayer.UnfilledDeposits.ts

The motivation for this is:
1) We should reduce number of configuration variables where possible
2) The specific "invalid fills found" log can be summarized by grouping invalid fills per relayer rather than logging once per invalid fill found
3) I believe we should always log invalid fills found. If this gets super noisy as number of external relayers goes up we can look into changing this logic, but for now we should be aware of invalid fills sent
I think 3 is most contentious point, open to suggestions!

feat(relayer): Improve log for invalid fills and always log them

---

src/utils/ProviderUtils.ts

Since ethers v5, all RPC requests have been preceed by an eth_chainId lookup. This is described by ethers as a safety feature to mitigate being "RPC rugged" - i.e. where a wallet silently changes RPC without notifying the provider.
Inspecting the Across logs, eth_chainId is the second-most popular RPC call, after only eth_getLogs. Over the past 30 days, Infura usage has been:
```
eth_getLogs                264M
eth_chainId                 30M
eth_call                    24M
eth_getTransactionReceipt   11M
eth_blockNumber              3M
Total                      336M
```
Given that the Across bots maintain a 1:1 relationship between provider instance and back-end RPC provider, there's no obvious way for the chainId to ever change. It's therefore worth considering using …

improve(ProviderUtils): Avoid redundant eth_chainId rpc calls

---

src/clients/MultiCallerClient.ts

This PR ignores the following revert reason:
> "missing revert data in call exception; Transaction reverted without a reason string"
Ignoring this reason potentially includes false positives of reverts that we should be alerted on, however there is something likely broken in how the provider is interpreting contract reverts. Currently, there are a lot of duplicate transaction sends that are reverting with this reason, for example, sending a transaction to execute a relayer refund leaf takes a while to execute and ends up reverting because a duplicate transaction mines before it. This situation leads to this revert reason which is spamming the Logger currently.
So, this PR reduces alert noise at the cost of introducing false positive ignored errors

improve: Ignore "missing revert data..." reason

---

src/clients/HubPoolClient.ts

In prod, the HubPoolClient is correctly fetching the `HubPool.rootBundleProposal()` but not saving it into memory correctly until some amount of time after the proposal.
This log should help debug what's being stored.

fix: Temporarily log out saved pendingProposal

---

src/clients/HubPoolClient.ts

I don't think the `rootBundleProposal` stored in the `HubPoolClient` is being corrupted, but I do think that the timing of dataworker runs causes the `HubPoolCLient` to update first, well before the `Dataworker` run completes, causing some issues
Reverts across-protocol/relayer-v2#311

Revert "fix: Temporarily log out saved pendingProposal"

---

src/common/ClientHelper.ts
src/utils/ProviderUtils.ts

This change simply adds logging of 429 (too many requests) responses from RPC providers. The logging is intended to be temporary, and should aid enable additional data about rate-limiting to be collected.
Based on local testing against free-tier RPC plans, rate-limiting responses seem very common once NODE_MAX_CONCURRENCY exceeds 2. The v2 bots are primarily using Infura, but Infura unfortunately has extremely little to report on 429 responses. Alchemy, in contrast, provides excellent logging information and guides on tuning.
My gut feeling is that Across bots are probably subject to quite a bit of rate-limiting.

improve(ProviderUtils): Temp. logging of 429 replies

---

src/utils/FormattingUtils.ts

Remove the opportunity for errors to creep in over time due to duplicate implementations. The sdk-v2 implementation of toBN() allows optional decimal scaling, which is nice to have.
Without going on too much of a yak-shaving odyssey, we should also probably migrate some of the extra implementations from here over into the SDK.
For reference, the SDK implementations are available here: https://github.com/across-protocol/sdk-v2/blob/f77190132d3fb8cb88fb34f3141d397942816bdb/src/utils.ts
Ref: ACX-325

chore(FormattingUtils): Use sdk-v2 implementations

---

index.ts
package.json
src/clients/bridges/AdapterManager.ts
src/clients/bridges/ArbitrumAdapter.ts
src/clients/bridges/BaseAdapter.ts
src/clients/bridges/CrossChainTransferClient.ts
src/clients/bridges/OptimismAdapter.ts
src/clients/bridges/PolygonAdapter.ts
src/common/Constants.ts
src/utils/EventUtils.ts
src/utils/Help.ts
src/utils/LogUtils.ts
src/utils/TypeGuards.ts
src/utils/index.ts
test/AdapterManager.getOutstandingCrossChainTokenTransferAmount.ts
test/mocks/MockAdapterManager.ts
tsconfig.json
yarn.lock

This is the first PR in what will hopefully be a series of PRs to address type issues that are blocking us from enabling the `strict` setting in our tsconfig.
The idea behind this change is to make our bots safer and more error-proof by expanding the sort of type-checking we're getting from typescript.
I've created this by enabling strict locally and working through the errors manually. Since there are hundreds of errors, I've decided to start working through them folder-by-folder and doing PRs as I go so these can be carefully reviewed.

improve: improve typing in src/clients/bridges/

---

src/clients/SpokePoolClient.ts
src/utils/RedisUtils.ts

When updating deposits following speed ups, the Dataworker cached deposit does not get updated. There is no inherent risk. It does just mean when the Spokepool client updates, and loads deposits from cache, it won't be the most up-to-date version containing the new relayerFeePct.
In practice, deposits are only loaded from the cache if they are older than the most recently validated root bundle, and most deposits are fully filled well before then, but this PR will enhance UX for the edge cases where deposits only get partially filled and are not fully filled for a long time.

improve: Store sped-up relayer fee % in cache

---

src/clients/ProfitClient.ts
test/ProfitClient.ConsiderProfitability.ts

This is a single commit containing a collection of minor changes that were accrued whilst updating the ProfitClient profitability logic. They are separated out here to avoid cluttering the main PR.
- Use constants for minRelayerFeePct.
- Reorg. token data in ProfitClient test.

chore(ProfitClient): Misc. cleanup before update

---

package.json
yarn.lock

This pulls in an update to the logger that stops it from converting BNs to strings in objects that are passed to it by reference.

fix(logger): fix logger bug that converts BNs to strings

---

src/clients/HubPoolClient.ts

Should _never_ happen in practice, but if it did then it would break a lot of assumptions in the bot. This therefore saves consumers of these L1Tokens from having to explicitly check.

improve(HubPoolClient): Warn on unexepcted token decimals

---

src/clients/ProfitClient.ts
test/ProfitClient.ConsiderProfitability.ts
test/ProfitClient.PriceRetrieval.ts
test/mocks/MockProfitClient.ts

Addresses 14 warnings raised by the linter:
```
across-protocol/relayer-v2/src/clients/ProfitClient.ts
91:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
95:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
133:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
137:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
194:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
270:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
279:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types …
```

chore(ProfitClient): Lint

---

src/clients/ProfitClient.ts
src/relayer/Relayer.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts
test/ProfitClient.ConsiderProfitability.ts
test/Relayer.BasicFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts
test/mocks/MockProfitClient.ts

This commit enables the new profitability logic that has been introduced in recent ProfitClient work.
The env var MIN_RELAYER_FEE_PCT is now more strict, and enforces a minimum fee as a percentage of the amount to be relayers _after_ taking the gas cost into account.
Additionally, more logging/diagnostic information is now available via the DEBUG_PROFITABILITY env var.

improve(ProfitClient): Activate profitability logic

---

src/common/Constants.ts
src/relayer/Relayer.ts
src/relayer/RelayerConfig.ts
test/Relayer.BasicFill.ts
test/Relayer.IterativeFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts

Adds a deposit quote timestamp buffer to protect relayer from edge case where a quote time is > HEAD's latest block. Currently, the relayer is exposed to the risk that HubPool utilization changes between `now` and the eventual block mined at that timestamp, since the ConfigStoreClient.computeRealizedLpFee returns the current lpFee % for quote times >HEAD

fix(relayer): Ignore deposits with quote time in future

---

src/clients/ProfitClient.ts
src/common/Constants.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts
test/ProfitClient.ConsiderProfitability.ts

Default to 1.2, to allow some headroom for gas price changes between
when the profitability is calculated and when the txn is submitted.
This won't impact the behaviour of the RL bot, but will make any third-
party bots more conservative.
One thing to note is that this change introduces a single, global multiplier.
The SDK has a per-chain configurable multiplier...so there is some difference
with the SDK, which might be relevant, since it typically computes the fees.

improve(ProfitClient): Add relayer gas multiplier

---

src/clients/ProfitClient.ts
src/common/Constants.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts
test/ProfitClient.ConsiderProfitability.ts

This reverts commit dfb877b7b9e0ec05a53bc5e38be005376678fc98. The gas multiplier addition introduced a non-critical bug that should be fixed within the next 24 hours. Until then, back it out.

Revert "improve(ProfitClient): Add relayer gas multiplier (#342)"

---

.eslintrc.js
package.json
src/clients/ProfitClient.ts
test/Dataworker.buildRoots.ts
test/Dataworker.loadData.ts
test/ProfitClient.ConsiderProfitability.ts
yarn.lock

Prevents the case where an `expect(...)` without an assertion (e.g. `to.be.true`) suppresses an error or contains something `false` in the inner expression. This is because `expect(...)` returns true if the inside statement is truthy which includes Errors and `false`

improve: Add es-lint rules to prevent chai "expect" statements without assertions

---

index.ts
src/common/Config.ts
tsconfig.json

Could alternatively be bundled into the global config within src/common/Config.ts, so it would be automagically logged by the respective "{Dataworker,Relayer} started" log messages.

improve: Log package version on startup

---

src/finalizer/index.ts
src/finalizer/utils/optimism.ts

New optimism sdk 1.6.x has a different Signer type than that exported by ethers.Signer that we use as dependency. I was able to run this code locally and it works in run time so the main issue seemed to be compile time. For example I finalized this optimism L2 message using this code: https://etherscan.io/tx/0x22e80cd98823c47f6949e08429f97cf6e0e95ee0ae793d7a931acb4ef435a333

fix: Use typecasting to fix optimism finalizer

---

package.json
yarn.lock

See https://github.com/across-protocol/sdk-v2/pull/124 for explanation of bug fix making Optimism gas costs too high

fix: Upgrade sdk-v2 version to 0.1.32 to fix Optimism gas cost computation

---

test/ProfitClient.PriceRetrieval.ts

Math.random() can occasionally produce a random number that can't be promoted to 18 decimals by BigNumber.
This should address the failure seen here: https://github.com/across-protocol/relayer-v2/actions/runs/3376746366/jobs/5604840582

fix(ProfitClient): Clamp test token prices

---

test/ProfitClient.PriceRetrieval.ts

The previous commit that attempted to fix this issue was ineffective because it misunderstood the behaviour of Math.random(). The maximum number of decimal places returned by Math.random() is apparently implemenation-defined, and on occasion it seems that our implementation wants to return more than the minimum.

fix(ProfitClient): Properly clamp test price decimals

---

src/common/Constants.ts

The existing config isn't long enough to catch withdrawals on Optimism. This is
a band-aid to allow withdrawals to resume, to be addressed properly once we
understand more.

chore(finalizer): Increase lookback for Optimism

---

src/finalizer/utils/optimism.ts

If direction is not defined, then the SDK will (per current implementation) perform an L1 -> L2 lookup before an L2 -> L1 lookup. By specifying the direction we can avoid the redundant lookup.
Description is here: https://sdk.optimism.io/classes/crosschainmessenger#getMessagesByTransaction
Relevant code in the SDK is here: https://github.com/ethereum-optimism/optimism/blob/8f531f201c9d400acd7a4bc4a54db9a094b0778f/packages/sdk/src/cross-chain-messenger.ts#L283

improve(finalizer): Specify direction on Optimism

---

src/clients/BalanceAllocator.ts
src/clients/bridges/OptimismAdapter.ts
src/dataworker/Dataworker.ts

Ovm_SpokePool will deposit ETH into WETH before executing any leaves, so both the ETH and WETH balances should be counted together when deciding whether a leaf can be executed. Without this logic, the dataworker mistakenly skips executing leaves that it does have balance for but the balance is split between eth and weth

fix(balance-allocator): Count WETH and ETH for OVM spoke chains

---

src/clients/AcrossAPIClient.ts
src/clients/MultiCallerClient.ts
src/relayer/Relayer.ts

- Typo in Relayer in AcrossAPIClient log
- Increase default timeout in AcrossAPIClient to 60s, the full length of the vercel API timeout
- Typo in MultiCallerClient

fix: Various relayer fixes

---

src/clients/AcrossAPIClient.ts
src/finalizer/index.ts
src/finalizer/utils/arbitrum.ts
src/finalizer/utils/optimism.ts
src/finalizer/utils/polygon.ts

Currently only batches Polygon and Optimism finalizations because Arbitrum's calldata is a bit harder to extract. I will work on this as a follow up to this PR once we are happy with the structure.
Example txn I sent with this:
- https://etherscan.io/tx/0x26ad50ff8bd6a81e36251838c222067da39bb0f0156deb152d31de0c2f8cf29d (this one I had a bug in the code that didn't correctly include the `PolygonTokenBridger.retrieve()` txns but the second txn includes this bug fix and correctly calls `retrieve()`)
- https://etherscan.io/tx/0xc852ab8dedcdc8909e84377e1266cdf9c9f413199daa97330a8e9e74d746b425

feat: Use Multicall to batch Finalizer transactions

---

src/clients/MultiCallerClient.ts

The "at" key/value pair is mandatory.

fix(MultiCallerClient): Correct log message

---

package.json

**Scope**
This change updates the `package.json` license to GPL-3.0. 
**Motivation**
The original SPDX-identifier for the GNU Affero GPL 3.0 license (`AGPL-3.0`) has been deprecated. 
The more current SPDX identifier for the Affero GPL 3.0 is `AGPL-3.0-only`

chore(license): update license

---

src/clients/MultiCallerClient.ts

Very minor tweak to reduce the scope of the try/catch clause in the executeTransactionQueue() method. This has no functional impact and is done in isolation to avoid future a megadiff against this file.

improve(MultiCallerClient): Reduce try/catch scope

---

src/clients/ProfitClient.ts
src/dataworker/DataworkerClientHelper.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts
test/ProfitClient.ConsiderProfitability.ts
test/ProfitClient.PriceRetrieval.ts
test/Relayer.IterativeFill.ts
test/fixtures/Dataworker.Fixture.ts

This variable seems pretty redundant now. Price lookup failures are very
rare these days because we have fallback from the Across API to
CoinGecko Free/Pro, and DefiLlama exists as a third option if we choose
to use it. Additionally, the ignoreProfitability option is another good
proxy for whether we want to be strict about price lookup failures.

improve(ProfitClient): Remove ignoreTokenPriceFailures option

---

src/clients/MultiCallerClient.ts

Reduce the size/complexity of the executeTransactionQueue() method by
factoring out the transaction simulation component. There is no
functional impact as part of this change - the relocated code performs
the same function as before.
Follow-up commits might make tweaks to improve transaction simulation
now that it is confined to a separate private method.

improve(MultiCallerClient): Factor out txn simulation

---

src/clients/AcrossAPIClient.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts
test/Relayer.BasicFill.ts
test/Relayer.IterativeFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts

AcrossAPI fails to return data for l1 tokens not enabled in hub pool, so relayer should construct the APIClient only with enabled L1 tokens
﻿Signed-off-by: nicholaspai <npai.nyc@gmail.com>

improve: Construct AcrossAPIClient with only L1 tokens enabeld in HubPool

---

src/common/ClientHelper.ts
src/common/Config.ts
src/common/Constants.ts
src/dataworker/DataworkerClientHelper.ts
src/finalizer/index.ts
src/monitor/Monitor.ts
src/relayer/Relayer.ts
src/utils/FillUtils.ts
test/Relayer.BasicFill.ts
test/Relayer.IterativeFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts
test/constants.ts

These functions currently require caller to pass in lookback per chain in terms of blocks. Can now specify in seconds which willl be same for all chains.
Dataworker currently sets lookback based on bundle end blocks, so that implicitly standardizes time across chains.

improve: Use lookback based on time for all chains in Finalizer, Relayer and Monitor

---

src/clients/ConfigStoreClient.ts
src/clients/SpokePoolClient.ts
src/interfaces/ConfigStore.ts
test/ConfigStoreClient.ts

Supports the ability for Across to charge different LP fees based on route.
Follow up PR will add feature to `sdk-v2` and the API in `frontend-v2`.
There is no risk to merging this now since `AcrossConfigStore` does not currently contain any `routeRateModels`

feat: Enable route-specific rate model in ConfigStoreClient

---

src/clients/HubPoolClient.ts
src/dataworker/Dataworker.ts
src/scripts/validateRootBundle.ts
src/utils/EventUtils.ts
src/utils/UmaUtils.ts
src/utils/index.ts

This PR makes the validation script more robust when handling atomic disputes (i.e. disputes sent in same block as subsequent proposals) by querying the PriceRequestAdded event emitted by the disputed root bundle event. The script now throws if the
found proposal and filtering out events that don't precede the dispute---by block number, transaction index, or log index.
Additionally, the hub pool client's getMostRecentProposedRootBundle now uses a < comparison instead of a <= to find a root bundle earlier than a block number. This 
function is only used in one place by the Dataworker where it does not change behavior.

fix(validation-script): Handle case where dispute is atomically bundled with new proposal

---

src/utils/ProviderUtils.ts

We want to know anytime a provider disagrees with another. Currently we only know this if we don't reach quorum. So this PR logs any time we do reach quorum but have disagreeing providers

improve(ProviderUtils): log about disagreeing providers

---

src/monitor/Monitor.ts

This wasn't caught because we haven't used the `token` field in the MONITORED_BALANCES config yet

fix(monitor): Remove unnecessary cast in _getDecimals()

---

src/scripts/validateRootBundle.ts
src/utils/UmaUtils.ts

This is used in validateRootBundle script
h/t @chrismaree for pointing this out

improve: Replace hardcoded DVM address

---

src/utils/ProviderUtils.ts

The default ethers implementation is very aggressive and will regularly retry immediately after a 429 response. This might be OK for serialised requests, but is not very compatible with the heavily-parallel request load of this bot.
This change sets a new minimum delay of (1000 * failure) ms, where failure is [1, 2, 3, ...]. An additional random delay between 0 and (1000 * failure) ms is subsequently added to the minimum delay. This is an aggressive backoff that also delivers some randomisation in order to avoid further rate-limiting as a result of retries being submitted in batches.
There are some limitations with this approach:
- Each RPC provider has different recommendations for handling 429 responses.
- If the 429 response includes a retry-after header, this new custom delay will be …

improve(ProviderUtils): Override ethers 429 backoff

---

src/utils/FillUtils.ts
test/Dataworker.buildRoots.ts

Right now there unknown behavior if dataworker can't find the first fill associated with a slow fill (i.e. the one that triggered the slow fill). We should loudly throw when this happens.
I think what would happen is that `getFillDataForSlowFillFromPreviousRootBundle` would throw: `Cannot read properties of undefined (reading 'blockNumber')`
I don't think this has caused any self-disputes but its possible?

improve: Dataworker should throw explicitly when it can't construct a slow fill excess

---

src/clients/MultiCallerClient.ts
src/clients/ProfitClient.ts

This reduces warnings about missing return-type annotations, and removes a comment
relaying to an odd number->string conversion that was occurring in the logging module.
That issue was resolved here: https://github.com/UMAprotocol/protocol/commit/e7cd6c52e4cb8a18041dac1046bb0c78649fc945

improve(MultiCallerClient): Lint

---

src/clients/MultiCallerClient.ts

Simplify the code and make it more modular by returning an AugmentedTransaction. This permits it to be reused without imposing that the resulting multicall bundle is submitted.
A test to use this change (and fix a bug) will follow in the next commit.

improve(MultiCallerClient): De-scope buldMultiCallBundle()

---

src/clients/MultiCallerClient.ts
test/MultiCallerClient.ts

Makes the code a bit more compact and more clearly separates between simulation and logging. This also allows for the logging function to be verified in test by mocking it out.
As a minor benefit, the existing implementation performs 3 complete loops over the array of transaction simulation results. This change performs only one complete loop, and then a secondary loop over the list of failures to determine which to log. It should be marginally faster, and probably more memory efficient.

improve(MultiCallerClient): Simplify sim failure logging

---

src/clients/ProfitClient.ts

The recent CoinGecko blip led to a short period of relayer unavailability. DefiLlama have a price feed that is primarily backed by CoinGecko, but which can also fall back to on-chain sources for the major tokens.
Resolves ACX-597.

improve(PriceClient): Add DefiLlama as a backstop

---

src/clients/MultiCallerClient.ts
test/MultiCallerClient.ts

The existing implementation incorrectly checks that _each_ enqueued transaction has the wrong contract address. This is impossible because the contract address used as a reference is sourced from the first transaction in the queue.
While here, add a test for this and expand the logic to validate that all enqueued transactions are destined for the same chain ID as well..

fix(MultiCallerClient): Correct multicall txn validation

---

src/clients/ConfigStoreClient.ts
src/scripts/validateRootBundle.ts
src/utils/RedisUtils.ts
src/utils/UmaUtils.ts

RedisClient currently stores two keys:
- block for timestamp
- utilizations at block
These are used by ConfigStoreClient to compute a realized lp fee % and by dataworker to construct spoke pool clients' `fromBlocks`. They're also used by the validateRootBundle script which shouldnt ever be used to validate bundles older than 90 days
Expiring these keys after 90 days seems very safe assuming bundle block ranges stay steady
RedisJS [documentation](https://github.com/redis/node-redis#redis-commands)
Redis.API [documentation](https://redis.io/commands/set/)

improve: Set 90 day expiry on redis keys

---

src/clients/MultiCallerClient.ts
src/common/Constants.ts
test/MultiCallerClient.ts

Makes it possible to supply the chunkSize from within test cases. Also allows for multiple concurrent instances of the MultiCallerClient to use different chunk sizes, if that should ever be desirable.

improve(MultiCallerClient): Caller-supplied chunksize

---

src/clients/ConfigStoreClient.ts
src/relayer/Relayer.ts
src/utils/FillUtils.ts

Per the comment on line 221 "Drop value and key before passing args." we should be constructing cumulative l1 token config updates with `passedArgs` not `args` which includes the full key-value string which is unused after parsing it

improve: Remove extra properties from cumulative l1TokenUpdate objects

---

src/clients/MultiCallerClient.ts
src/common/ClientHelper.ts
src/common/Config.ts
src/common/Constants.ts

Identified as a requirement when we detected that Optimism RPCs were
not accepting the default chunk size of 100 txns. At that point it would
have been really convenient to override via the environment rather than
forcing a new bot revision...but this wasn't supported by the bots.
Fixes ACX-437.

improve(multicaller): Env-configurable chunk sizes

---

src/clients/MultiCallerClient.ts
src/clients/TransactionClient.ts
src/clients/index.ts
test/MultiCallerClient.ts
test/TransactionClient.ts
test/mocks/MockTransactionClient.ts
test/mocks/index.ts

This factors out some of the transaction submission functions from the MultiCallerClient implementation. As a result, the MultiCallerClient can become more compact and focused on the task of sorting transactions and bundling the eligible ones.
Note that this PR does not introduce use of the TransactionClient into the MultiCallerClient at this stage, since the TransactionClient includes new behaviour around nonces.
More to come.

feat: Add TransactionClient

---

src/clients/HubPoolClient.ts
src/dataworker/Dataworker.ts
src/scripts/validateRootBundle.ts
src/utils/UmaUtils.ts

Script  essentially figures out the latest events it should need to query to reconstruct an older bundle, so the range of events to query is fixed based on DATAWORKER_FAST_LOOKBACK_COUNT

improve(validate-script): Script can efficiently reconstruct very old bundle

---

src/utils/ProviderUtils.ts

Some RPC provider errors that we see are transient, so it's hard to debug them any further unless we capture the actual response that was issued.
This will generate fairly lengthy logging when we do have provider issues, but will also enable us to diagnose and report errors much more quickly.
Fixes ACX-755.

improve: Dump mismatched RPC provider responses

---

src/clients/SpokePoolClient.ts

The existing message logs only the deposit ID and the block range that was searched.

improve(SpokePoolClient): Include network names in exception

---

src/dataworker/Dataworker.ts
src/scripts/validateRootBundle.ts

Imagine we only want to execute leaves from the last 10 bundles. Intuitively this should only include leaves from the last 10 root bundles, but currently this means we count the latest 10 relayed root bundles for a chain. This means that some chains like Boba which have infrequent relayed root bundles, the lookback needs to be much larger.
This results in a lot of warnings: "Cannot validate bundle with insufficient event data. Set a larger DATAWORKER_FAST_LOOKBACK_COUNT". We should quiet these warnings

improve: If `spokeRootsLookbackCount` is set, only try to execute root bundles from N most recent proposed root bundles rather than root bundle relays

---

src/clients/BundleDataClient.ts
src/dataworker/Dataworker.ts
src/dataworker/PoolRebalanceUtils.ts
src/scripts/validateRunningBalances.ts
test/Dataworker.buildRoots.ts
test/Dataworker.proposeRootBundle.ts

When a slow fill is executed, its `unfilledAmount` is sent to the `recipient` minus any fees where `relayerFeePct == 0` and `lpFeePct >= 0`. Therefore, this fixes an issue where every slow fill executed is leaving the `lpFee` in the SpokePool.
I discovered this bug while running the `validateRunningBundle` script and noticed that the `excess` amount increases after slow fill. This is corroborated by looking at spoke pool balances over time, for example the BAL balance of the EtheruemSpokePool which recently had some slow fills: https://etherscan.io/token/0xba100000625a3754423978a60c9317c58a424e3d?a=0x4d9079bb4165aeb4084c526a32695dcfd2f77381#tokenAnalytics

fix(dataworker): amount to send to SpokePool for slow fill should be unfilled amount minus LP fee

---

src/clients/ProfitClient.ts
test/ProfitClient.ConsiderProfitability.ts

This change permits relayer operators to specify source- & destination-specific minimum
fees per token. The existing global config is retained as a fallback for any combinations
that do not match on a more specific configuration.
Also, make isFillProfitable(..., ..., l1Token, ...) a mandatory argument, since the only caller
of this method always supplies l1token.
Fixed ACX-850.

feat(ProfitClient): Permit route-based minimum relayer fees

---

src/common/Constants.ts
src/dataworker/Dataworker.ts

We don't need this anymore as we only try to execute leaves from bundles that are linked to a validated root bundle proposal (sent on Mainnet). So if an admin bundle was relayed directly to the Spoke the executor will never try to execute it.
This constant was a part of legacy code in the executor that looked up root bundle ID's in descending order and tried to execute them, regardless of their relationship to a mainnet root bundle proposal

feat: Delete IGNORED_BUNDLES constant

---

src/utils/ProviderUtils.ts

Currently we log only mismatched provider data but we should log the expected quorum result

improve: Log quorum result data

---

src/common/ClientHelper.ts
src/finalizer/index.ts
src/finalizer/utils/arbitrum.ts
src/finalizer/utils/polygon.ts
src/utils/ProviderUtils.ts

This fixes an issue where the order in which `getProvider()` is called determines which kind of provider is cached: either one with redis or without. However, `getProvider` should always return the expected "cached" provider, with redis or without as the caller expects.
This PR fixes the issue by caching the provider with its redis flag.
Additionally, any calls in the repo to `getProvider` are all modified to be called the same way, with `redis` enabled.

feat: Cache providers by chainId and cache/noCache flag

---

src/clients/AcrossAPIClient.ts
src/relayer/RelayerClientHelper.ts
test/Relayer.BasicFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts

For example, BOBA has no destination chains besides 1 so there is no need to call /limits on it

fix: Filter out tokens that don't have any non-mainnet destination chains before calling /limits

---

src/clients/ConfigStoreClient.ts
src/dataworker/DataworkerUtils.ts
src/dataworker/PoolRebalanceUtils.ts

Currently dataworker only treats a chain as disabled if it disabled for entire block range, this is a bug as it should be disabled as soon as the bundle's end block is greater than the time the chain was added to the disabled list

fix: Dataworker should count a chain as disabled if it is disabled at mainnet bundle end block

---

src/dataworker/Dataworker.ts

This opens the dataworker to slight chance that "latest" disabled chain list isn't valid for a bundle because the bundle lags `latest` by 100 blocks

fix: Subtract buffer from mainnet bundle end block when proposing new  bundle

---

src/relayer/Relayer.ts

This should include the bare minimum that we need to find the deposit. Additionally,
logging the deposit amount vs. unfilledAmount makes it easy to quickly see whether
a slow fill has been initiated.

improve: Quieter logs for deposits over limit

---

src/clients/BundleDataClient.ts
src/dataworker/Dataworker.ts
src/dataworker/PoolRebalanceUtils.ts
src/scripts/validateRootBundle.ts
src/scripts/validateRunningBalances.ts
test/Dataworker.blockRangeUtils.ts

Also includes a refactor to pass in `enabledChains` into `getWidestPossibleBlockNumbers` which means we don't need to pass in `mainnetBundleEndBlock` to the function because its only used to get enabled chains
This will also make it easier to unit test `getWidestPossibleBlockNumbers`

fix: Should pass in latestMainnetBlock into `hubPoolClient.getLatestBundleEndBlockForChain`

---

src/clients/BalanceAllocator.ts
src/utils/BigNumberUtils.ts
test/BalanceAllocator.ts

There are a few bugs in the BalanceAllocator.
1. If you send a request containing two requested allocations for the same token, it will not account for the first allocation impacting the second.
2. If you send a request with multiple tokens and it needed to use multiple tokens to fulfil it, it would ignore the previously used amount when deciding how to increment used.
These two scenarios are the last two tests added in the test file. I verified that these failed in the previous version, but succeed after these changes.

fix: fix multiple bugs in BalanceAllocator

---

src/utils/ProviderUtils.ts

Logging the complete accepted response tends to be very spammy.

Remove logging of quorum (accepted) RPC response

---

src/common/Constants.ts

The most important buffer to try to reduce is the mainnet one since sometimes the mainnet bundle end block is passed as a proxy for the "latest" blocks into various functions. This sometimes can be done accidentally, like it was in a bug that 56353f89406f122153526a0b9e38e6f55e3a3fbc fixed. Nevertheless, we should try to reduce the gap between bundle end blocks and "latest"

improve: Change default bundle end block

---

src/clients/SpokePoolClient.ts

These events increase with every bundle so I imagine the lookback is starting to take up noticeable time

improve: Fix lookback for SpokePool relayed root-related events

---

src/clients/BundleDataClient.ts

Logging the details of the fills we deem invalid will make it a lot easier to investigate when they appear.

improve(BundleDataClient): Log exact invalid fills

---

src/utils/EventUtils.ts

Testing the relayer with a deposit lookback of 7 days and no concurrency shows no identifiable performance impact. Lower-layer constraints seem to be applying the necessary rate-limiting anyway.

improve(EventUtils): Remove concurrency constraint

---

src/clients/SpokePoolClient.ts

- Relocate searchConfig validation so it follows immediately after
constructing searchConfig.
- Warn about instances of searchConfig.fromBlock > searchConfig.toBlock.
Ultimately, I think that SpokePoolClient should throw an error if it is
requested to update with an invalid searchConfig, but would like to
detect any instances of it in production before applying that change.

improve(SpokePoolClient): Adjust searchConfig validation

---

src/finalizer/index.ts
src/finalizer/utils/arbitrum.ts
src/finalizer/utils/polygon.ts

This change corrects for eslint and typescript strict in the finalizer directory

refactor: :recycle: enable strict on `finalizer` directory

---

test/ProfitClient.ConsiderProfitability.ts

Math.random() will occasionally produce a random number with _so_ much precision
that it underflows on promotion to 18 decimals.

fix(test): ProfitClient ConsiderProfitability

---

index.ts
scripts/unwrapWeth.ts

This PR ensures that there are no type casting, among other fixes per @mrice32 comments in https://github.com/across-protocol/relayer-v2/pull/559

fix: resolve type casting comment

---

src/clients/MultiCallerClient.ts

This change adds a logging and exit condition to the multicaller txn execution. In the event that the transactions fail, the new logic will collate failed txn states and produce an error log. Additionall this fn will propagate the error and lead to an eventual (caught) stack unwind to prevent any further logic

fix: :bug: improve logging support for failed multicall txns

---

src/utils/ProviderUtils.ts

This moves TTL resolution into the constructor of the cache provider so the default is defined by the time it runs.

fix: fix TTL resolution bug

---

src/monitor/Monitor.ts

Slow fills can trigger "unknown relayer" alerts now that multicall3 is used to fill slow
relays. The address of the relayer is perceived to be the multicall3 contract address,
and the address of tx.origin is not available directly in the FillWithBlock event (would
need to look it up via transaction hash instead).
We can't include multicall3 in the list of known relayers, so given that slow relays are
trusted to the extent that they have cleared liveness and have been sent out of the
HubPool, simply suppress alerts on slow fills from unknown relayers.

fix(Monitor): Suppress "unknown relayer" alerts on slow fills

---

test/SpokePoolClient.RefundRequests.ts
test/mocks/MockSpokePoolClient.ts

- The ethers Event type is a weird hybrid of an array _and_ an Object with k/v pairs. Internally in relayer-v2 EventUtils, we ignore the array members and focus on the named k/v pairs. Therefore, switch the args type from an array to an Object. This enables the named args to be properly extracted and transformed into a proper "...WithBlock" object.
- Consolidate MockSpokePoolClient event generation, such that the event name is passed in as part of the EthersEventTemplate. This makes it easier to use and reduces repetitive code fragments.
- Minor optimisation to the way events are fed into the base SpokePoolClient during mocked _update().
- Increase randomness in transactionHash generation.

improve(MockSpokePoolClient): Fixes & simplifications

---

scripts/disableDepositRoutes.ts
src/clients/AcrossAPIClient.ts
src/clients/ConfigStoreClient.ts
src/common/ClientHelper.ts
src/common/Config.ts
src/dataworker/DataworkerClientHelper.ts
src/dataworker/DataworkerConfig.ts
src/dataworker/index.ts
src/monitor/MonitorClientHelper.ts
src/monitor/MonitorConfig.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts

Pulled across from Nick's across-2.5 branch. This change permits the supported chains to be overridden by the environment. It has no impact unless overridden by the environment, so it should be safe to go into prod.
Co-authored-by: nicholaspai <9457025+nicholaspai@users.noreply.github.com>

chore(across-v2.5): Make CHAIN_ID_LIST_INDICES user-configurable

---

src/utils/TransactionUtils.ts

Seems like we sometimes hit error codes known to be benign even after running out of retries. In which case we still shouldn't send an `error` level log + page.

improve(TransactionUtils): If we're out of retries and transaction fails, don't log `error` level if error code is expected

---

src/clients/SpokePoolClient.ts

The function validateFillForDeposit never evaluates the blockNumber member, so there's no need drop that member from the input object. This removes two lint suppressions.

refactor(SpokePoolClient): Simplify validateFillForDeposit usage

---

src/utils/ProviderUtils.ts

Per current implementation, we log every 100th 429 response, so we need to receive 100 429s before we log for the first time. This makes it more difficult for third-parties to troubleshoot their RPC setups. Instead, log on the first, and every 100th thereafter.
Also, adjust the wording of the log message emitted to make it more obvious to third-party operators.

improve(ProviderUtils): Log first 429 response

---

test/UBA.SpokePoolClient.ts

The updated FilledRelay type (with updatableRelayData field) breaks the existing tests. These tests relate to future functionality, so disable them until we are over the SpokePool upgrade hurdle.

chore(UBA): Temporarily disable UBA SpokePoolClient tests

---

src/common/ClientHelper.ts
src/common/Config.ts

This can be used for example to make sure that the `finalizer` continues to finalize events for deprecated spoke pools by setting `TO_BLOCK_OVERRIDE_1=<block-before-spoke-pool-was-deprecated>`.
This is because the function `constructSpokePoolClientsWithLookback` used to create `SpokePoolClient`'s  looks up the enabled SpokePools as of the `toBlock` for chainId=1. Currently the `toBlocks` default to "latest", so this PR allow these to be overridden.

feat: Let bot runner set `toBlockOverride` to construct clients for deprecated SpokePools

---

src/clients/SpokePoolClient.ts
src/dataworker/Dataworker.ts

Doesn't handle case where there are no root bundles yet

fix: Handle executor for first root bundle ID

---

src/monitor/Monitor.ts

The conditional logic was broken since its initial introduction a few weeks ago. The intention is that slow relays should not trigger alerts.

fix(Monitor): Correct slow fill alerting logic

---

package.json
src/clients/ConfigStoreClient.ts
src/clients/HubPoolClient.ts
src/clients/SpokePoolClient.ts
src/clients/bridges/ArbitrumAdapter.ts
src/utils/EventUtils.ts
test/UBA.SpokePoolClient.ts
test/mocks/MockSpokePoolClient.ts

The Ethers Event 'args' field is an unusual Array/Object hybrid, so we can dereference its members directly, rather than using their array indices. However, EventUtils doesn't handle recursion down into args members that are themselves Objects, so add that capability in.
This broader event unpacking functionality seems ripe for some re-work in order to address some previously discussed type that's necessary to appease the various type checkers.
Fixes ACX-1057

fix(UBA): Restore tests

---

src/utils/Help.ts

I believe we're now using `node ./dist/index.js` instead of `ts-node ./index.ts`

feat: :bug: correct help cmd text

---

src/finalizer/utils/optimism.ts

I've noticed that we suffer from intermittent timeout errors when querying the Optimism [cross domain messenger on 
L1](https://etherscan.io/address/0x25ace71c97b33cc4729cf772ae268934f7ab5fa1#readProxyContract). The optimism finalizer code is the only one where we don't use the cache+retry provider, and instead use a 
vanilla JSONRpcProvider. I think using the more robust bespoke provider should mitigate these issues.
The reason why I originally used this vanilla provider was to make TS compile.

improve(finalizer): Use Retry provider in Optimism finalizer

---

package.json

In practice, relayer-v2 won't run on node 12.x, and supporting older versions makes it difficult to support the relayer because some users see weird issues on older versions.

chore(package): Bump minimum nodejs version

---

src/clients/MultiCallerClient.ts

This  PR tries to filter out any errors that occur when a transaction is successfully simulated but then fails when it is mined. This can happen for the relayer commonly if they get front-run by another 
relay, which is expected behavior

improve(multicallerclient): Log multicaller execution failures

---

package.json

This workaround is necessary after a recent regression. It's a bandaid, pending a proper fix.

fix(package): Explicitly define HARDHAT_CONFIG

---

src/clients/MultiCallerClient.ts

This PR removes a simulation of the batch sent to `Multicall3`. This was originally included because technically its possible that individually transactions will succeed when batched together, they can revert.
This extra simulation has downsides:
- Extra RPC request to simulate transaction ends up leading to slow down in transactions being mined which opens up to ultimate failures like nonce-reuse and front-running
- More logic
With some upsides:
- Catches case where batch fails while individual txns succeed
Ultimately, the dataworker and relayer functions using this code should never be batching together transactions that would fail in a batch but succeed individually, so I think its safe to remove to mitigate the downsides above. Moreover, if the batch fails, we'll hear about it …

improve(MulticallerClient): Remove extra simulation

---

src/clients/HubPoolClient.ts

This log message was mostly copy/pasted from the SpokePoolClient, but the SpokePoolClient implements a wrapper for logger that handles the message structuring.

fix: Correct log message

---

src/monitor/MonitorClientHelper.ts
test/Monitor.ts

No need to re-update the common clients since `constructMonitorClients` will ultimately do this

improve(monitor): Remove redundant common client update

---

src/clients/BundleDataClient.ts
src/dataworker/Dataworker.ts

Protects dataworker from executing fill for deposit with very expensive message

improve: Refuse to execute SlowFill leaves for deposits with messages

---

.prettierrc

When this option is defined, it spams the console with `Ignored unknown option [...]` messages during test. explicitTest was removed from prettier in September 2022; Dependabot recently upgraded us to ^1.1.3, which is from March 2023.
https://github.com/prettier-solidity/prettier-plugin-solidity/pull/730

fix: Remove redundant explicitTypes config

---

src/clients/ProfitClient.ts
src/relayer/Relayer.ts
test/ProfitClient.ConsiderProfitability.ts

In  practice we find it would be helpful to link directly to deposit transaction hashes in order to debug why a deposit was sent with unprofitable parameters

improve: Log deposit txn hashes for unprofitable deposits

---

src/clients/MultiCallerClient.ts

Improvement following up on https://github.com/across-protocol/relayer-v2/pull/637 that doesn't increase run-time by sending extra RPC requests in best case scenario where batch simulation succeeds.
Additionally, handles the case addressed by https://github.com/across-protocol/relayer-v2/pull/681 where simulations can fail individually but succeed in a batch

improve(MulticallerClient): First try to simulate txns as a batch before individually simulating them

---

src/clients/ConfigStoreClient.ts

This method seems surprisingly unused by any other code in this repository!
It's proposed for removal because it introduces a dependency on the HubPoolClient, which seems like an inversion. Per a pending change to the HubPoolClient in the sdk-v2 repository, the HubPoolClient will instead become dependent on the ConfigStoreClient when validating the runningBalances member of the ExecutedRootBundle.
See https://github.com/across-protocol/sdk-v2/pull/213#discussion_r1197043597 for reference.

refactor(ConfigStoreClient): Remove getUtilization override

---

src/clients/BundleDataClient.ts
src/clients/SpokePoolClient.ts
src/utils/DepositUtils.ts
src/utils/FillUtils.ts
test/Dataworker.loadData.ts
test/SpokePoolClient.ValidateFill.ts

Split queryHistoricalDepositForFill() into two, factoring out the on-chain paginated lookup from the caching logic.
The on-chain paginated lookup (SpokePoolClient.findDeposit()) can probably be relocated to the parent SpokePoolClient class in the sdk-v2 repository as a result.
This is an enabler for future work to shuffle the relationship between the SpokePoolClient, HubPoolClient and ConfigStoreClient, which is needed for the pending UBA rollout.

refactor(SpokePoolClient): Simplify deposit lookup

---

src/common/ClientHelper.ts

The HubPoolClient must now be updated _after_ the ConfigStoreClient.

fix: Ensure ordering of client updates

---

src/clients/BundleDataClient.ts
src/dataworker/Dataworker.ts
src/dataworker/DataworkerUtils.ts
src/scripts/validateRootBundle.ts
src/scripts/validateRunningBalances.ts
src/utils/FillUtils.ts
test/Dataworker.blockRangeUtils.ts
test/Dataworker.executePoolRebalances.ts
test/Dataworker.validateRootBundle.ts
test/Monitor.ts
test/fixtures/Dataworker.Fixture.ts
test/utils/utils.ts

Removes the so-far identified constraints that would prohibit running with a HubPool
deployed to a network with a chainId other than 1.
Fixes ACX-1152

improve(Dataworker): Dynamic HubPool chainId

---

yarn.lock

Somehow the recent dependabot PR to bump contracts-v2 to 2.2.3 did not include removing contracts-v2 2.2.2.

fix: Sync yarn.lock

---

src/dataworker/PoolRebalanceUtils.ts
test/Dataworker.blockRangeUtils.ts
test/mocks/MockHubPoolClient.ts
test/mocks/index.ts

Adds one additional check to function that returns next bundle block range to propose to handle case where the `latest` block has stopped advancing.

improve: Handle case where chain has stopped advancing

---

src/relayer/RelayerClientHelper.ts

There is no need to call /limits on disabled destination chains

fix(relayer): Don't construct API client with disabled destination chains

---

README.md
src/dataworker/Dataworker.ts

Handles very unlikely edge case where proposer proposed when chain was halted but chain restarted during challenge window. In this case, the proposer might have proposed block range [100, 100] because the chain was halted at block 100, while disputer now thinks chain has advanced to block 150 and believes the "widest possible" block range is now [101, 150].

fix(disputer): Should evaluate pending block range from previous `bundleEndBlock` rather than previous `bundleEndBlock+1`

---

package.json
src/finalizer/index.ts
src/finalizer/utils/optimism.ts
yarn.lock

https://community.optimism.io/docs/developers/bedrock/how-is-bedrock-different/#two-phase-withdrawals
Supports the new two phase withdrawal process:
- Submits proofs to L1 for recent Withdrawal events

fix: Support Bedrock finalizations

---

src/monitor/Monitor.ts

This alert was a lot more important when Across first started and we did not expect _any_ third-party relayers. Now that these are very much expected, we should still be alerted on them but at a lower severity log level.

improve(monitor): Change log level for unknown relayer to `warn` from `error`

---

src/finalizer/utils/optimism.ts

eth-optimism SDK can't handle them. I've raised an issue with their team [here](https://github.com/ethereum-optimism/optimism/issues/5983)

fix: Temporarily filter out optimism with L2 txns with multiple withdrawals

---

src/common/Constants.ts
src/utils/TransactionUtils.ts

Resolve  the issue where we are over scaling the Optimism priority fee. The priority fee returned by Optimism gas estimator is already scaled quite aggressively.
Fixes ACX-1208

improve(utils): Add reasonable gas fee scaler defaults for Optimism and Ethereum

---

src/clients/ProfitClient.ts
src/relayer/Relayer.ts
test/Monitor.ts
test/ProfitClient.ConsiderProfitability.ts

This change permits the ProfitClient to incorporate the cost/benefit of taking refunds on a particular chain. This is necessary for the UBA model, but the implementation is backwards-compatible with pre-UBA fees by setting the refund fee to 0.
A follow-up change will set the refundFee correctly from within the Relayer class, depending on the version applicable to the deposit.
Fixes ACX-1201

feat(ProfitClient): Consider refund fees

---

package.json
src/finalizer/index.ts
src/finalizer/utils/optimism.ts
yarn.lock

Temporary fix that uses a fork of @eth-optimism/sdk that supports multiple messages within a withdrawal L2 txn.
[This commit](https://github.com/across-protocol/optimism/commit/2bbdb4dc69d8b563b14fdc498f68ef9e71dc71e1) adds a `logIndex` modeled after how @arbitrum/sdk handles multiple messages. Requires caller to pass in the relative log index of the message that they want to prove and finalize into the sdk.

fix(finalizer): Use fork of @eth-optimism/sdk that supports withdrawing multiple messages

---

src/utils/TransactionUtils.ts

Polygon added a new endpoint a while ago and have recently
deactived the pre-existing matic.network.

fix(getGasPrice): Use new Polygon gasstation URI

---

package.json
yarn.lock

The SDK recently migrated to using EIP1559 pricing for Arbitrum, but this is misleading because the priority fee is always refunded (and Ethers hardcodes it to 1.5 Gwei). This caused deposits destined for Arbitrum to be considered unprofitable.

fix: Bump SDK for better Arbitrum gas pricing

---

src/clients/MultiCallerClient.ts

Sometimes the error is returned as `execution reverted: <reason>`, so add detection for that. Additionally, refactor the detection logic to be more concise (no intended change in behaviour).

improve: Suppress additional "relay filled" errors

---

src/clients/ProfitClient.ts

Recent testing has been difficult because third-party relayers are eager to make fills, and are sometimes doing so at a loss. This means it can be surprisingly difficult to set a relayer fee low enough to be ignored by others. This change permits a 0x gas multiplier to be used, thereby instructing the relayer to ignore the cost of gas entirely. Deposits can thus be set with a 0% relayerFeePct, which is good enough to be ignored by most third parties. The pre-existing profitability protections are still in place, and control remains in the hands of the user as to how they want to configure their relayer.

improve(ProfitClient): Permit gas costs to be ignored

---

src/clients/UBAClient.ts
src/relayer/RelayerClientHelper.ts

Simple change; the UBA client isn't actively used yet but that will follow shortly. The relayFeeCalculatorConfig is stubbed out because there's currently no need for it, but that may change later.
Closes ACX-1211

chore(UBA): Instantiate ubaClient in relayer clients

---

src/clients/bridges/OptimismAdapter.ts

As per the recent change in the MultiCallerClient, when submitting transactions destined for the Optimism deposit contract on Ethereum, it's necessary to pad the gas that is estimated via estimateGas(). The TransactionClient class has been used for this because it's a drop-in replacement for runTransaction(), and the MultiCallerClient offers limited benefits in this case because coincidental rebalancing to multiple chains seems unlikely.
Test deposits and fills here:
https://etherscan.io/tx/0xe4802ea7f5c3f0f6b3234fc69d718850df6f11598d36413eec4e9600196e9020
https://optimistic.etherscan.io/tx/0x03aca8577d58391b6051086dac47a3785c16d03d7bfdf8028bba7dd8b4b7e13e
https://etherscan.io/tx/0x94f70a778270a94e242c7463044b73bded6f45e5c122e0cb65709eb7384b904c …

fix(AdapterManager): Pad gas for deposits to Optimism

---

src/clients/bridges/OptimismAdapter.ts

Since we're now using the TransactionClient() for bridging from mainnet to Optimism, use it for wrapping Ether on Optimism as well. This avoids having mixed dependencies for transaction submission.
Test transaction here:
https://optimistic.etherscan.io/tx/0x2a4dac0612330eaa4c5dd1ad327d0a88cd037cd2ea3b13a916df643c511661d8

refactor(AdapterManager): Deprecate Optimism runTransaction()

---

src/clients/MultiCallerClient.ts

Today  the Multicaller client ignores known revert reasons when simulating individual transactions but not batch transactions. We should do the same for batch txns because this handles the common case where 
the batch contains only 1 txn and that has a clear revert reason that we expect.

improve(multicaller-client): Ignore expected revert reasons for batch txns

---

src/relayer/Relayer.ts
src/relayer/RelayerConfig.ts
test/Relayer.BasicFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts

Enables relayer to mark certain depositors as slow-fill only. Could also use this pattern for a depositor "blacklist"

feat: Add slow fill "grey" list mode to Relayer

---

src/clients/ProfitClient.ts
src/relayer/Relayer.ts
test/ProfitClient.ConsiderProfitability.ts

This implements the "Repayment Chain Choice Module" described in
ACX-977. It prefers to take refunds on the chainId suggested by the
Inventory Manager, then the destinationChainId, and then the HubPool
chainId, before reverting to an ordered list of the most profitable
refund chains. In each case, it must be profitable for the relayer to
take a refund there for it to use that chainId.
Some minor tweaks were needed in the ProfitClient to make this more
cohesive.
Closes ACX-977.

improve(Relayer): More intelligent UBA refund chain selection

---

src/finalizer/utils/optimism.ts

We fixed this for `proveMessage` but not `finalizeMessage`

fix: Include logMessage to finalize messages that are contained in same L2 withdrawal txn

---

package.json
src/clients/bridges/PolygonAdapter.ts
src/relayer/Relayer.ts
yarn.lock

Bumps contracts-v2 and sdk-v2 to latest version with fixed POOL token addresses. Also, add support for POOL in `PolygonAdapter`.
There was a breaking change in `@across-protocol/sdk-v2@0.10.4`. The fix is here https://github.com/across-protocol/relayer-v2/pull/779/commits/661ad21aaab448d1839515b461a110ebbde7ca56. Let me know if this is not correct

feat: add support for POOL token

---

src/utils/BlockUtils.ts
src/utils/RedisUtils.ts
src/utils/index.ts

This function uses Redis in the back-end to cache block timestamps; it's not inherently a part of Redis utilities. Also, export getBlockFinder() so that it can be used directly.

refactor: Relocate getBlockForTimestamp()

---

src/common/ClientHelper.ts
src/finalizer/index.ts
src/scripts/validateRootBundle.ts
src/utils/BlockUtils.ts
src/utils/UmaUtils.ts

Two improvements here:
- Remove the need to supply the HubPool chain ID to this function. I've been unable to find any other places in the code where the HubPool chain ID block numbers are accessed via the key `block_number_<timestamp>`, so just normalise all keys to be `<chainId>_block_number_<timestamp>`. This frees the caller from having to know what the HubPool chainId is.
- Remove the need to supply the externally-supplied `currentChainTime`. This argument was _always_ supplied with the output of `getCurrentTime()`, which is not necessarily the current chain time anyway, and goes against the naming of the variable `currentTimeTime`. Instead, use the timestamp of the latest block to determine whether it's old enough to be cached.
As background, the motivation for this change is that …

improve(BlockUtils): Simplify getBlockForTimestamp()

---

src/common/ContractAddresses.ts
src/dataworker/Dataworker.ts

When executing OVM SpokePool leaves we need to request both ETH and WETH balances together
Alternative implementation to #785

fix(dataworker): Add ETH to list of tokens we should request balance allocations for

---

package.json
yarn.lock

This change bumps the SDK-V2 to v0.12.3

chore: bump sdk-v2

---

test/ConfigStoreClient.ts
test/HubPoolClient.Utilization.ts

- Factor the computeRealizedLpFeePct test out to a separate file, since it's directly related to the HubPoolClient and only indirectly related to the ConfigStoreClient.
- Remove a lot of init cruft from the ConfigStoreClient test. As it turns out, this  was only necessary for the computeRealizedLpFeePct test.
As background, there have historically been ghosts in the ConfigStoreClient test, as evidenced by the existing need to reset the hre state prior to commencing the test. It seems possible to drop that bodge now, so this consolidation _might_ actually be hinting at the underlying issue.

refactor: Relocate computeRealizedLpFeePct test

---

src/utils/EventUtils.ts
src/utils/index.ts

delay() exists in src/utils/TimeUtils.ts and was already exported via src/utils/index.ts.

refactor: Use local delay function

---

src/dataworker/Dataworker.ts
test/Dataworker.executePoolRebalances.ts

- Call `exchangeRateCurrent` when token hasn't been updated within past 2 hours rather than 24 hours
- Call `exchangeRateCurrent` before exiting early because challenge period hasn't passed yet for bundle. This increases chances that token exchange rate is synced before leaves are executed.

improve(Dataworker): Call `exchangeRateCurrent` more frequently

---

src/common/ClientHelper.ts
src/common/Config.ts
src/dataworker/Dataworker.ts
src/scripts/validateRootBundle.ts

This allows individual operators to opt in to UBA pricing in advance of the default supported version being incremented.
This commit includes some very minor refactoring as a result of dereferencing a couple of objects adjacent to the configStoreClient within the CommonClients instance. 
Note that this doesn't change the active version - that's still read from the ConfigStore.

feat: Allow configuration of max supported config version

---

src/dataworker/Dataworker.ts

blockRangeEndBlockBuffer is a map that's addressed by chainId. These cases are otherwise tricky to spot, since we often lookup position 1 in an array of [startBlock, endBlock], and that is a valid case of hardcoding the index.

improve: Remove sneaky hardcoded chain ID

---

package.json
src/caching/RedisCache.ts
src/utils/RedisUtils.ts
yarn.lock

This PR uses the SDK-V2's agnostic caching interface to wrap a Redis client. We can now use an instance of this caching class in the SDK without the SDK needing to know anything about redis except that it can `set` and `get` keys of a specific type.

feat: add cache agnostic redis cache

---

src/utils/ProviderUtils.ts

This will be needed if the we become dependent on knowing the timestamp of the various {FundsDeposited, FilledRelay, RefundRequested} events.
Closes ACX-1344

feat: Cache eth_getBlockByNumber calls

---

package.json
test/Dataworker.loadData.ts
test/Relayer.UnfilledDeposits.ts
test/SpokePoolClient.RefundRequests.ts
test/SpokePoolClient.SpeedUp.ts
test/SpokePoolClient.ValidateFill.ts
yarn.lock

Tests updated to reflect that a few `...WithBlock` objects now include a
`blockTimestamp` member.

chore: Bump SDK

---

package.json
src/finalizer/index.ts
src/finalizer/utils/optimism.ts
yarn.lock

This PR removes the dependency on a cloned version of the `@eth-optimism/sdk-2.1.3` repo that added a bug fix to handle multiple withdrawal messages in the same L2 transaction post-bedrock.
The `eth-optimism/sdk` as of version 3.1 now includes this logic
Resolves ACX-1203

feat(finalizer): Upgrade eth-optimism/sdk version to take advantage of updated cross-chain messenger

---

src/utils/ObjectUtils.ts
src/utils/ProviderUtils.ts

We've seen QuickNode add in a `transactionLogIndex` field which isn't in the spec and is causing quorum agreement issues

improve(ProviderUtils): Add filtered key to eth_getLogs

---

index.ts

My previous change accidentally dropped the `await` statement and broke the bot.

fix: await on getSigner()

---

package.json
src/clients/BundleDataClient.ts
src/clients/bridges/AdapterManager.ts
src/common/ClientHelper.ts
src/dataworker/Dataworker.ts
src/dataworker/DataworkerClientHelper.ts
src/dataworker/DataworkerUtils.ts
src/dataworker/PoolRebalanceUtils.ts
src/dataworker/index.ts
src/monitor/Monitor.ts
src/monitor/MonitorClientHelper.ts
src/scripts/testUBAClient.ts
src/scripts/validateRootBundle.ts
src/scripts/validateRunningBalances.ts
test/Monitor.ts
test/UBAClientUtilities.ts
test/mocks/MockAdapterManager.ts
yarn.lock

- We need to update the config store client before constructing BundleDataClient
- We need to handle the fact that BundleDataClient and Dataworker might have a longer chainIdIndices list than the actual number of block ranges they will handle
- Fix logic in `blockRangesAreInvalidForSpokeClients` that assumed that `chainIdIndices` length is always equal to `blockRanges` length

fix(dataworker): Add changes found after integration testing Dataworker

---

contracts/AtomicWethDepositor.sol
src/common/ContractAddresses.ts

feat: Add ZkSync function to AtomicWethDepositor

---

src/clients/ProfitClient.ts

Rather than trying to correctly translate testnet ERC20 addresses to mainnet addresses, just accept token prices of zero on testnets. This simplifies the code and removes a few potential sources of error.
While here, sub out a couple of toBN(0) for the ethers constant Zero.

fix: Remove ProfitClient testnet incompatibilities

---

src/common/Constants.ts

The default MDCs should reflect the most conservative block
confirmation requirements for the chain.

chore: Shadow MDC defaults for Base and Optimism

---

src/finalizer/index.ts
src/finalizer/utils/index.ts
src/finalizer/utils/opStack.ts

This modifies the optimism finalizer to support base. Changes are very simple. Will modify the client slightly to test on goerli to ensure this works as expected.
I've verified that the version of @eth-optimism/sdk is [3.1.0](https://github.com/across-protocol/relayer-v2/blob/f83e9ee6c9ca4e20c224cbd45601784c220e0996/package.json#L17), which includes base support in the optimism sdk.

feat: add base finalizer

---

src/clients/bridges/ZKSyncAdapter.ts
src/utils/RPCUtils.ts
src/utils/chains/index.ts
src/utils/chains/zkSync.ts
src/utils/index.ts

Makes it easier to use the `convertEthersRPCToZKSyncRPC()` helper.

improve: Consolidate RetryProvider cast in RPCUtils

---

src/clients/bridges/AdapterManager.ts
src/clients/bridges/BaseAdapter.ts
src/clients/bridges/op-stack/OpStackAdapter.ts
src/clients/bridges/op-stack/WethBridge.ts
src/clients/bridges/op-stack/base/BaseChainAdapter.ts
src/clients/bridges/op-stack/optimism/OptimismAdapter.ts
src/clients/bridges/op-stack/optimism/SnxOptimismBridge.ts
src/monitor/MonitorClientHelper.ts
src/relayer/RelayerClientHelper.ts

I tracked the following deposits which the current production `monitor` is alerting on and this branch does not warn on it:
- Example L1 deposit initiated transaction
- Log index 95 here: https://etherscan.io/tx/0x2d59cbf45b78f9bd0a936d3826e112d0147c02f66c971b0ddcc010438c81cbbb#eventlog
- Example L2 finalization
https://basescan.org/tx/0xdc232909267c0290ffeef37d27047b8c1632c912e333cf05e0962fedc065d060#eventlog
We should be tracking the hub pool's address in both events but the `AdapterManager` uses the spoke pool addresses instead. So I resolve this by adding hub pool address to list of monitored addresses.
Additionally, the EthDepositInitiated doesn't set the `fromAddress` to the correct event parameter.

fix(opStackAdapter): WETH deposit initiated event filter fixes

---

src/utils/ProviderUtils.ts

We don't _directly_ depend on the block hash, so if all of the other fields in the response agree then don't discard the response simply because the of the blockHash field. This is introduced now because there are upstream disagreements from various providers as to which blockHash applies to the current set of events.
Fixes ACX-1515

fix: Ignore block hash in eth_getLogs responses

---

src/clients/TransactionClient.ts

The logging subsystem doesn't handle Error objects properly.

fix: Avoid logging entire Error object

---

.env.example
src/relayer/Relayer.ts
src/relayer/RelayerConfig.ts
test/Relayer.BasicFill.ts

This is a simple relayer-specific config to permit ignoring deposits based on their origin chain ID.
Note: This is implemented at the relayer level because the anticipated UBA rollout will require relayers to validate events on _all_ supported chains, not only the ones they wish to support.
Closes ACX-1516

improve(relayer): Permit ignoring origin chains

---

package.json
yarn.lock

This change is motivated by a need to properly map `0xdead....` (raw ETH address) to WETH. This issue is resolved in the newest SDK revision.

chore: bump sdk-v2 version

---

src/utils/ProviderUtils.ts

Testing shows that these fields can be updated shortly after the block has been produced.

improve: Don't trigger quorum fights on zkSync l1 fields

---

.eslintrc.js
src/clients/bridges/op-stack/OpStackBridgeInterface.ts
src/scripts/testUBAClient.ts
src/scripts/validateRootBundle.ts
src/scripts/validateRunningBalances.ts
src/utils/RedisUtils.ts
test/MultiCallerClient.ts
test/SpokePoolClient.ValidateFill.ts
test/UBAClient.validateFlow.ts
test/UBAClientUtilities.ts
tsconfig.eslint.json
tsconfig.json
tsconfig.test.json

This PR adds ESLinting for floating promises. Floating promises are defined as any function that resolves an unhandled promise. A handled promise can either be returned directly, awaited, then/catch'd, or voided.
This change would have immediately solved https://github.com/across-protocol/relayer-v2/commit/723bdcfae365051fcb05a089ebf4e6fc998bb2b0. We can now enforce that un-awaited promises will never be uncaught again.

feat: enable linting for floating promises.

---

src/dataworker/PoolRebalanceUtils.ts

Temporary fix to resolve an issue with future quoteTimestamps. We need a more robust solution than this in the long run.

fix(Dataworker): Dereference originChainId by index, not key

---

package.json
src/caching/RedisCache.ts
yarn.lock

This PR enabled the ability for the hubpool client to utilize caching. Additionally, this change sets the RedisClient to use the default 2 week TTL if not provided.

improve: leverage default TTL & leverage caching

---

package.json
yarn.lock

Neccessary to get this in before we can bump the VERSION field in the config store contract before going back to https://github.com/across-protocol/relayer-v2/pull/937

chore: Update SDK-v2 version so that UBA min version is bumped

---

src/common/Constants.ts

This needs to match the latest version in the config store, which is now 2

fix: Bump config store version

---

src/utils/SignerUtils.ts

The type is correctly filtered within getSigner(), but it causes unnecessary type annoyances when reading the key type from the environment or on the command-line.

improve: Simplify wallet key type

---

src/utils/ProviderUtils.ts

This change deprecates the ability to configure RPC providers with the old NODE_URL[S]_<CHAIN-ID> syntax. Instead, the newer RPC_PROVIDERS format is enforced.
Both formats have been supported for over 4 months now, but we have long since migrated to the new format in the bots.

refactor: Deprecate NODE_URL[S]_<CHAIN-ID> config

---

test/TokenClient.Approval.ts
test/fixtures/UmaEcosystemFixture.ts

These names change very rarely, and we only have need for a small number of the complete set.

refactor: Remove UMA interfaces lookup

---

src/finalizer/index.ts

The previous change to the finalizer incorrectly assumed that there would be a 1:1 relationship between a txn and a withdrawal or proof. This is incorrect on Polygon, where 2 txns are needed to finalize a single withdrawal.
This change seems like a manageable way of establishing a 1:many relationship between withdrawal/proof logging and the necessary transaction(s), without imposing any changes on the underlying chain adapters. Ultimately it would be nice to backport this into the adapters themselves, but that's invasive and it's not worth prioritising now.

fix(finalizer): Handle 1:many withdrawal:calldata

---

src/relayer/Relayer.ts

No change in behaviour, but a but less code duplication between the normal and sped-up fillRelay code paths.
This is a precursor to supporting messaging.

refactor: Consolidate relayer fillRelay method

---

src/utils/CLIUtils.ts

fix: Restore privateKey wallet validation

---

src/clients/InventoryClient.ts
src/clients/bridges/AdapterManager.ts
src/clients/bridges/ArbitrumAdapter.ts
src/clients/bridges/BaseAdapter.ts
src/clients/bridges/ZKSyncAdapter.ts
src/clients/bridges/op-stack/OpStackAdapter.ts
src/common/ContractAddresses.ts
src/interfaces/InventoryManagement.ts
src/relayer/RelayerConfig.ts
src/utils/CLIUtils.ts

We expect ETH to be sent to the relayer address on Arbitrum because its 
[hardcoded](https://github.com/across-protocol/contracts-v2/blob/3634df5ec327326ce030629aa0a089f651f20bc0/contracts/chain-adapters/Arbitrum_Adapter.sol#L158) as a refund address for all HubPool messages 
that get sent to the ArbitrumSpoke.

feat(inventory-manager): Wrap ETH on Arbitrum

---

src/clients/AcrossAPIClient.ts
src/relayer/RelayerClientHelper.ts

AcrossAPIClient.update() currently only tries to query the first available route for a token. In instances where the RPC provider for this chain is unavailable, this results in the client resolving a maxDeposit of 0.
Instead, iterate over the set of all available chains for this token until one route results in a usable response. This should boost robustness in the bots.
While here, tweak the instantiation of the AcrossAPIClient. The existing implementation requires RELAYER_DESTINATION_CHAINS to be defined. Per this PR, if RELAYER_DESTINATION_CHAINS is not defined, just use the full set of available SpokePoolClient instances.
Fixes ACX-1593

improve: Retry Across API /limits on failure

---

src/clients/ProfitClient.ts
test/Relayer.BasicFill.ts
test/Relayer.RefundRequests.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts
test/mocks/MockProfitClient.ts

Done in preparation for follow-on changes relating to Across messaging:
- Automatically setup gas tokens for known test chains, rather than requiring the user to call MockProfitClient.testInit().
- Add singular setter-like methods for token prices and gas costs.
- Remove some redundant type annotations.

improve: Update MockProfitClient ahead of changes

---

src/relayer/RelayerClientHelper.ts

The AtomicWethDepositor contract isn't deployed on testnets, so only include it as a monitored address if it is defined on the HubPool chain.

improve: Remove relayer testnet incompatibility

---

src/clients/InventoryClient.ts
src/relayer/RelayerConfig.ts
src/relayer/index.ts
test/InventoryClient.InventoryRebalance.ts

The  `TokenClient` fetches ERC20 balances for the relayer prior to carrying out Relayer duties. This means that there could be a multiple minute delay between balances between fetched and the inventory 
manager executing, exposing the relayer to the risk of sending a duplicate rebalance.
This PR adds a simple check for the ERC20 balance as close to sending the inventory rebalance as possible. The downside is a slower inventory manager run, which is mitigated by a side effect of allowing the bot-runner to refactor the inventory manager out of the relayer. This can be done by setting the new environment variable `SKIP_RELAYS` which will skip the relayer portion of the `relayer/index.ts` run.
Fixes ACX1595

improve(inventory-manager): Check ERC20 balance before submitting cross chain bridge

---

src/clients/InventoryClient.ts
src/clients/TokenClient.ts
src/clients/bridges/ArbitrumAdapter.ts
src/clients/bridges/ZKSyncAdapter.ts
src/clients/bridges/op-stack/OpStackAdapter.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts

Based on an issue we're seeing where L1 to L2 rebalances are still getting duplicated, even after wrapping ETH, perhaps suggesting that the `tokenClient` is using stale data
the logic written [here](https://github.com/across-protocol/relayer-v2/blob/master/src/relayer/RelayerClientHelper.ts#L159) should be reading updated balances post-ETH-unwrap but it may not.
This PR adds more logs we can use to better debug

improve(relayer): Clear out token data explicitly and log token balances

---

src/scripts/validateRunningBalances.ts

Various  fixes to script:
- Tracks correct event on OPStack L2's to account for missing PoolRebalance deposits to the SpokePool. Without this, the excess balance looked too high
- Make excess check less sensitive and ignore dust

fix(validateRunningBalances): Change events we track to perform accounting

---

src/caching/RedisCache.ts

This change prevents the redis cache layer from performing a double JSON.parse( )

fix: :ambulance: avoid double parse

---

src/utils/ProviderUtils.ts
src/utils/RedisUtils.ts

In light of recent cache changes, it was noted that we have an outstanding amount of k/v pairs with infinite expiration. This must be avoided because all data should become stale over time. 
This change alerts GCP if we detect any infinite caching. It is a pass-through warning because we don't have any catching logic in place to handle these errors.

improve: warn on infinite redis ttl expiration

---

src/utils/RedisUtils.ts

This will resolve the failure we were seeing when we connected to Redis, then immediately failed. 
A note: there are no checks for this and it should be a compilation error to attempt to reference a function on a potentially undefined type.
An error sample that is now resolved:
```
2023-10-14 18:45:34 [debug]: {
"at": "RedisUtils#getRedis",
"message": "Connected to redis server at redis://xxxxxxxxxx successfully!",
"dbSize": 37236,
"bot-identifier": "xxxxxxxxxx"
}
2023-10-14 18:45:34 [debug]: {
"at": "RedisUtils#getRedis",
"message": "Failed to connect to redis server at redis://xxxxxxxxxx",
"bot-identifier": "xxxxxxxxxx"
}
```

fix: let debugger gracefully not execute if undefined

---

package.json
src/utils/BlockUtils.ts
src/utils/SDKUtils.ts
yarn.lock

This change migrates from the UMA BlockFinder to the Across-local variant and enables us to drop @uma/sdk as a direct dependency. We still inherit it from other packages, though.

refactor: Use BlockFinder from SDK

---

src/finalizer/index.ts

In the case where multiple Polygon withdrawals for a single token have accrued, the existing logic can break down. This is because the bridge adapter retrieve() call is a catch-all that evacuates the entire balance to the HubPool, so multiple finalisation transactions can map to a single retrieve() call. This is gas-efficient, but makes it borderline impossible for the finalizer to expect a clean 1:n withdrawal:txn mapping.

fix(finalizer): Revert Polygon txn:withdrawal expectations

---

package.json
yarn.lock

After discussing w/ Reinis, UMA had also noticed that the Slack
transport is prone to bombing out on long, complex JSON objects, and 
had independently made some improvements over the past couple of months.
Bumping to financial-templates-lib 2.34.0 makes the transport more
robust in that it doesn't die on the first badly-formatted log message.
It also supports notifying of transport errors via a dedicated logging
transport, which might be useful. 
I think it makes sense to jump to this new version immediately. There
are some residual issues - i.e. per our current config, this would
simply drop the log message that we'd like to log. We can try to work
out a common solution w/ the UMA team for that.

chore(across-v2): Bump @uma/financial-templates-lib

---

src/relayer/Relayer.ts
test/Relayer.BasicFill.ts
test/Relayer.TokenShortfall.ts
test/mocks/MockProfitClient.ts

Checking for existing fills in the pending transaction queue is only necessary because of some test cases that instrument the relayer in specific ways result in the relayer enqueueing multiple fills for the same deposit. This is not how the relayer works in production.
Flushing the transaction queue at the start of each run allows for the relayer to assume that it has no previously-enqueued fills.

refactor: Simplify relayer partial fill handling

---

package.json
yarn.lock

This includes an ABI change for the SpokePool contract to pick up the depositNow() function.

chore: Bump contracts-v2

---

test/Relayer.BasicFill.ts

Factor out a repetitive test pattern into the beforeAll() call.

refactor: Simplify Relayer BasicFill test cases

---

package.json

This negates the need to modify env vars when switching between the various dataworker personalities (and finalizer).
Usage:
- yarn run-disputer --wallet <wallet>
- yarn run-executor --wallet <wallet>
- yarn run-proposer --wallet <wallet>
- yarn run-finalizer --wallet <wallet>

feat: Add shortcuts for running dataworker and finalizer

---

package.json
src/clients/ProfitClient.ts
src/dataworker/DataworkerClientHelper.ts
src/relayer/Relayer.ts
src/relayer/RelayerClientHelper.ts
src/utils/DepositUtils.ts
test/ProfitClient.ConsiderProfitability.ts
test/ProfitClient.PriceRetrieval.ts
test/Relayer.SlowFill.ts
test/mocks/MockProfitClient.ts
yarn.lock

This PR gets relayer-v2 over the hurdle of a new SDK bump. The behaviour implemented here should be unchanged - the main impact is to supply a Deposit object to the relayFeeCalculator getGasCosts() method, rather than a simple chain ID.

chore: Bump SDK for composable bridging updates

---

src/common/Constants.ts

This buffer is added to force the proposer to use `bundleEndBlocks` that lag the latest blocks seen by `SpokePoolClients`. This is used to create a minimum distance between proposals. For disabled chains, like 288, this buffer should be 0 since the end blocks should not advance between bundles

improve(dataworker): Change 288 buffer to be 0

---

src/clients/HubPoolClient.ts
src/clients/UBAClient.ts
src/common/ClientHelper.ts
src/dataworker/index.ts
src/relayer/RelayerClientHelper.ts

We have existing logic that utilizes caching in the Hub & UBA Client. This change will pass a Redis instance to them directly so that we can better leverage caching in the DW.
Suggested PR before merging: https://github.com/across-protocol/sdk-v2/pull/436

improve: leverage caching interface

---

package.json
src/clients/HubPoolClient.ts
src/common/ClientHelper.ts
src/common/Config.ts
src/utils/BlockUtils.ts
src/utils/UmaUtils.ts
yarn.lock

Should see speed ups in dataworker by:
- reducing time to cache utilization in HubPoolClient
- use redis cache for block finder getBlockForTimestamp functions

improve: Upgrade to sdk-v2 version with optimized caching logic

---

src/clients/ProfitClient.ts

It's invalid to use the current relayer's EOA because that address may not hold USDC on all chains. Instead, default to the main RL address.
The relayer's own address will be used for dynamic message-based simulation.

fix: Use RL relayer address for basic gas cost estimation

---

src/utils/ProviderUtils.ts

This adds a simple method to make sure we don't accept a null or undefined response. In the future, we can enhance this logic by validating that it contains the fields, etc that we expect.

feat: add basic response validation to the RetryProvider

---

src/clients/ProfitClient.ts

This was missed in the previous commit. tsc isn't complaining about it and the code runs OK locally, but better to apply this fix now.

fix: Correct ProfitClient type annotation

---

src/dataworker/index.ts
src/finalizer/index.ts
src/monitor/index.ts
src/relayer/index.ts
src/scripts/testUBAClient.ts
src/scripts/validateRootBundle.ts
src/scripts/validateRunningBalances.ts
src/utils/RedisUtils.ts

Our disconnect logic currently only handles the default `redis` URL. (logic below). We ignore all the clients held in the  `redisClients` singleton.
```
export async function disconnectRedisClient(logger?: winston.Logger): Promise<void> {
const redisClient = await getRedis(logger);
if (redisClient !== undefined) {
// todo understand why redisClient isn't GCed automagically.
logger.debug({ at: "disconnectRedisClient", message: "Disconnecting from redis server." });
await redisClient.disconnect();
}
}
```
In addition, we're calling `getRedis` to find the client we want to disconnect. The issue is that if the following logic fails (within `getRedis()`), then we have created a redis connection that isn't stored to the `redisClients` singleton. We can never close this because it isn't saved. …

improve: disconnect all clients

---

src/utils/ProviderUtils.ts

Alchemy have been disagreeing with other providers on Arbitrum for a few days now; it causes higher RPC usage and unnecessary log noise. Disable it for now, with the option of reverting in future (if they fix it) or retaining it indefinitely, since we don't actually rely on this field.

improve(ProviderUtils): Temporarily ignore block size field

---

src/relayer/Relayer.ts

This is a condition that should ideally be readily observable for bot
operators.

fix: Log aborted zero-fills (w/ message) at warn

---

package.json
src/clients/ProfitClient.ts
yarn.lock

- Use the correct relayFeeCalculator query handlers for the various testnets.
- When selecting the HubPool token to map to a SpokePool token for test, be sure to use the HubPool's chain ID, rather than defaulting to mainnet.
- Simulate the fill with WETH, rather than USDC. Testnet tokens are annoying to configure because there are too many random ERC20s claiming to be WETH and USDC (and others). Since WETH is required as part of most SpokePool deployments, if we pick the wrong address on a testnet then at least we'll be "wrong" consistently.
Fixes ACX-1647

fix: Restore relayer testnet support

---

package.json
src/finalizer/index.ts
src/utils/TransactionUtils.ts
test/MultiCallerClient.ts
yarn.lock

This replaces the version from contracts-node and permits contracts-node to be dropped as a direct dependency.

chore: Use sdk-v2 getABI()

---

src/relayer/Relayer.ts
test/Relayer.BasicFill.ts

The relayer doesn't need to have have enough of the token to complete a                                                                                                                        
fill when its own address is the recipient of the transfer.

improve: Support relayer self-filling despite insufficient balance

---

src/clients/AcrossAPIClient.ts

Most API queries should resolve in under 1 second, but there are occasions where we log that we hit the 60s timeout. This is a major slowdown for the bots. Since we now rotate to the next available route, if the first query doesn't resolve shortly after it was sent, we should just fail quickly and rotate instead.

chore: Drop Across API timeout from 60s to 3s

---

src/clients/ProfitClient.ts
test/ProfitClient.ConsiderProfitability.ts
test/mocks/MockProfitClient.ts

Specify the gas token for a chain by its symbol, and then dynamically resolve the underlying token on mainnet. Also, remove some hardcoding around the lookup of MATIC for Polygon. This is part of some cleanup to make it easier to run the relayer on a testnet.

refactor(ProfitClient): Overhaul gas token resolution

---

src/clients/MultiCallerClient.ts
src/utils/TransactionUtils.ts
test/MultiCallerClient.ts

This change modifies the MultiCallerClient such that it will be more respectful of an enqueued transaction that has had a gasLimit applied.
There is one edge case that's not handled here: when an enqueued transaction with gasLimit is bundled together with other transactions that do not have a gasLimit, the gasLimit on the individual transaction reverts to undefined. This is because it's not possible to accurately set a gasLimit on the bundle without simulating each transaction on the fly, and that's actually what we try to avoid by bundling in the first place.
The caller can avoid this by ensuring that all enqueued transactions are simulated in advance. The relayer itself should implement this once some residual issues with higher-than-average ERC20 gas consumption on specific tokens has …

feat(MultiCallerClient): gasLimit plumbing

---

src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts

Can be used to split up relayer functionality into two bots:
- fast bot that sends relays and doesn't rebalance
- slow bot that runs entire relayer logic but doesn't execute anything and does rebalance

feat(rebalancer): Add toggle to send rebalances.

---

src/dataworker/Dataworker.ts
src/dataworker/DataworkerClientHelper.ts
src/dataworker/PoolRebalanceUtils.ts
src/utils/SDKUtils.ts
test/fixtures/Dataworker.Fixture.ts

The Dataworker only relies indirectly on the ProfitClient for its ability to query token prices. This imposes some test/mock burden on the ProfitClient. This change hoists the ProfitClient out of the Dataworker and instead subs in the underlying PriceClient, which the ProfitClient also uses directly.
As a side benefit, the proposer is currently the only component dependent on token prices, so token price lookups can be relegated to the code that actually needs it.

refactor(Dataworker): Replace ProfitClient with PriceClient

---

src/clients/ProfitClient.ts
test/ProfitClient.PriceRetrieval.ts

In cases like ETH/WETH, the underlying mainnet contract address used to resolve the token price is the same. Therefore, mapping from contract address to L1Token doesn't work very well for this purpose. Invert the token mapping so that the token symbol is unique, allowing for multiple symbols to map to a single address. This also helps in the case of test tokens that are temporarily mapped to an existing token.

fix(ProfitClient): Support non-unique token addresses

---

src/finalizer/index.ts
src/finalizer/utils/arbitrum.ts
src/finalizer/utils/opStack.ts
src/finalizer/utils/polygon.ts
src/finalizer/utils/zkSync.ts
src/utils/EventUtils.ts

The current code doesn't handle the case where there are multiple `TokensBridged` events within a single ZkSync transaction. This is because it always returns the `withdrawalIdx = 0` for all batched `TokensBridged`.
I believe this is because the `.reverse()` always causes the subsequent `.find()` to return index 0.
This PR simplifies the logic a lot and simply:
- Find all `L1MessageSentEvents` preceding the `TokensBridged` event.
- Return `withdrawalIdx` equal to the # of above preceding `L1MessageSentEvents`. This should return a unique withdrawal index per TokensBridged

fix(zksync-finalizer): Identify correct log index of ZkSync withdrawal when there are multiple withdrawals in same L2 transaction

---

src/clients/InventoryClient.ts
src/clients/bridges/CrossChainTransferClient.ts
src/relayer/Relayer.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/mocks/MockCrossChainTransferClient.ts
test/mocks/MockInventoryClient.ts

I think this can address the failure case where we submit a zero fill and send an inventory rebalance to an L2 in the same Relayer run when we're short balance there.
This PR introduces a new logical branch to the relayer when it sees a deposit that it can't fast full on the destination chain:
- First capture the token shortfall in the TokenClient. This is important so that the inventory client can accurately determine if it will need to rebalance.
- Load all possible rebalances: this is based on the relayer balances per chain, the outstanding cross chain transfers, and any shortfalls
- See if there is a rebalance that would fast fill this deposit.
- If there is, then check if the new destination chain balance plus this rebalance would be enough for the relayer to fast fill the deposit
- …

improve(relayer): Don't zero-fill when relayer expects to rebalance to fast fill deposit

---

src/common/ClientHelper.ts
src/finalizer/index.ts
src/relayer/Relayer.ts
src/utils/BlockUtils.ts
src/utils/FillUtils.ts

Without this we don't cache the timestamp -> blocknumber mappings, so we rely on the underlying RPC caching to retain the responses to the eth_getBlock queries that we issue. The are two reasons this is less desirable:
- Cached RPC queries are typically ejected much more regularly (default 1 hour, vs 1 week for cached block timestamps).
- Timestamp to block number resolution usually takes a different search path on each query, so there is a high chance of RPC cache misses even when trying to resolve the same timestamp.
This is one of the underlying reasons for the elevated RPC consumption of late.

fix: Supply cache instance to getCachedBlockForTimestamp()

---

test/Relayer.SlowFill.ts

Addresses the following:
dev/across-protocol/relayer-v2/test/Relayer.SlowFill.ts
204:19  warning  Unexpected any. Specify a different type
204:42  warning  Unexpected any. Specify a different type

fix: Resolve lint warnings

---

src/utils/ObjectUtils.ts
src/utils/ProviderUtils.ts

This fixes an issue where we weren't actually dropping the field from the array elements of the eth_getlogs response. We were operating on the array, itself, which doesn't contain the fields we are trying to remove.

fix: fix the eth_getLogs field ignore

---

src/dataworker/PoolRebalanceUtils.ts

This change ensures that Dataworker proposal block range identification is set realistically relative to the event search config for each SpokePoolClient.
HubPoolClient and SpokePoolClient instantiation was recently updated such that their search configs are now synchronised, and determined close to startup. Previously, the SpokePoolClient's search config would be determined much later because it had to wait for the initial HubPoolClient update to complete, and that can span several mainnet blocks. This meant that there was typically a 0 delta between the `toBlock` search config for each SpokePoolClient and its recorded `latestBlockNumber`. After the recent update, these values are now divergent.
This divergence can result in a situation where each SpokePoolClient may not have sufficient …

fix(Dataworker): Set SpokePool end blocks more conservatively

---

src/utils/ProviderUtils.ts

The 60s timeout is a source of latent notification storms during provider outages. This often results in a high number of long-running bot instances.
Improve notification time and recovery time by dropping the timeouts.

chore(ProviderUtils): Drop timeout 60s -> 10s

---

scripts/hubpool.ts
scripts/sendTokens.ts
scripts/spokepool.ts
scripts/unwrapWeth.ts
scripts/zkSyncDemo.ts
src/clients/MultiCallerClient.ts
src/common/ClientHelper.ts
src/dataworker/DataworkerClientHelper.ts
src/dataworker/index.ts
src/finalizer/index.ts
src/finalizer/types.ts
src/finalizer/utils/arbitrum.ts
src/finalizer/utils/opStack.ts
src/finalizer/utils/polygon.ts
src/finalizer/utils/zkSync.ts
src/monitor/MonitorClientHelper.ts
src/monitor/index.ts
src/relayer/RelayerClientHelper.ts
src/relayer/index.ts
src/scripts/testUBAClient.ts
src/scripts/validateRootBundle.ts
src/scripts/validateRunningBalances.ts
src/utils/CLIUtils.ts
src/utils/ContractUtils.ts
src/utils/SignerUtils.ts
src/utils/TransactionUtils.ts

tldr there are various scripts that don't need a real signer, so don't require a private key or mnemonic to be loaded in these cases. This makes life easier for people who just want to pull down the repo and run a script (i.e. validateRootBundle.ts).
The ethers Wallet type inherits from Signer, but it imposes additional requirements like having a private key. By deferring to the Signer type, we also permit void signers. This is nice for scenarios where a private key is not needed, which is in fact the vast majority of the usage in the bot.

feat: Support instantiating void signers

---

src/scripts/validateRootBundle.ts

The validateRootBundle script inherits a lot of core functionality, including the TokenClient. The TokenClient automatically seeks to put the necessary token approvals in place for handling the ABT token, but that's not strictly required for the validateRootBundle script since it never actually makes any transactions. Work around this by specifying the proposer address when instantiating the VoidSigner instance.

fix: Use disputer address in validateRootBundle script

---

src/clients/bridges/ArbitrumAdapter.ts

Infura are currently under-estimating the gas cost of deposits into the Arbitrum contracts on mainnet. This is causing OoG failures when the transactions are executed. Offchain Labs recommend to pad the gas by 5%, but there are limited downsides to padding by more.
Fixes ACX-1763

fix: Pad gas for mainnet deposits to Arbitrum

---

src/clients/BundleDataClient.ts
src/clients/ProfitClient.ts
src/clients/TokenClient.ts
src/clients/bridges/BaseAdapter.ts
src/clients/bridges/CrossChainTransferClient.ts
src/dataworker/DataworkerUtils.ts
src/dataworker/PoolRebalanceUtils.ts
src/dataworker/RelayerRefundUtils.ts
src/monitor/Monitor.ts
src/relayer/Relayer.ts
src/scripts/validateRunningBalances.ts
src/utils/DepositUtils.ts
src/utils/FillMathUtils.ts
src/utils/FillUtils.ts
src/utils/TransactionUtils.ts

ethers provides predefined BNs for 0 and 1, and we import these via the Across SDK. Roll these out as far and wide as possible, so as to reduce the unnecessary instantiation of new short-lived BNs. This will admittedly only have a small impact on memory and CPU consumption, but is still worth doing (especially in cases where the BNs were previously instantiated in a tight loop).

refactor: Reduce use of disposable BigNumber instances

---

src/common/ClientHelper.ts

https://github.com/across-protocol/sdk-v2/pull/475 resets the eventSearchConfig.toBlock to undefined after the update so we shouldn't read it directly

fix(ClientHelper): Use latest searched HubPoolClient block instead of eventSearchConfig.toBlock

---

scripts/spokepool.ts

We can now search an arbitrary deposit id on a given chain to find all of its information. This has been very helpful to resolve deposits when looking at fills.

feat: search for deposit id by chain

---

src/finalizer/utils/zkSync.ts

A recent update to the way Hub -> Spoke tokens are resolved broke the zkSync finalizer. This only shows up now because it's the first time in several weeks.
Re-proposing https://github.com/across-protocol/relayer-v2/pull/1140

fix: Correct zkSync finalizer

---

src/dataworker/Dataworker.ts
src/dataworker/index.ts
test/Dataworker.executePoolRebalances.ts
test/mocks/MockHubPoolClient.ts

feat(Dataworker): Skip exchangeRateCurrent updates for pooled tokens whose liquid reserves wouldn't increase

---

yarn.lock

This PR uses a popular tool to deduplicate our Yarn.lock file. Among other indicators, a duplicate package entry is a package that appears on multiple nodes of the dependency tree with overlapping version ranges but is resolved to different versions.
Package: https://www.npmjs.com/package/yarn-deduplicate
Command: `npx yarn-deduplicate yarn.lock`

improve: deduplicate yarn.lock

---

.env.example
src/dataworker/DataworkerConfig.ts
src/finalizer/index.ts

This PR adds a new ENV variable that allows the user to toggle whether to submit finalization transactions to an RPC. When `SEND_FINALIZATIONS` is set to false, our call to execute the multicall queue is done in simulation mode.
**Note: this will require bot config changes.**

feat(CLI): allow togglable finalizations

---

package.json
yarn.lock

This is required for https://github.com/across-protocol/relayer-v2/pull/1156 to be merged.

chore(sdk): bump version to v0.20.2

---

src/relayer/Relayer.ts
src/relayer/RelayerClientHelper.ts
test/Relayer.BasicFill.ts
test/Relayer.UnfilledDeposits.ts

UBA support is hampering updates for v3. Drop it for now; we can re-introduce it later once we're over the v3 hump.

refactor: Remove Relayer UBA functionality

---

src/interfaces/index.ts

This type is not used anywhere in this repository.

refactor: Remove redundant type definition

---

src/scripts/validateRootBundle.ts
src/scripts/validateRunningBalances.ts

Token approvals are incidentally needed via the TokenClient, but since the proposer/disputer address already has those in place it's possible to use a voidSigner with that address.
This is the same pattern as used in the validateRootBundle script.

improve: Use voidSigner in validateRunningBalances script

---

test/Relayer.SlowFill.ts

These were identified when adding v3 slowFillRequest support to relayer tests.

refactor: Misc driveby relayer test improvements

---

src/relayer/Relayer.ts
test/Relayer.BasicFill.ts
test/Relayer.TokenShortfall.ts

The comment attached to this ordering says that it's done to prioritise the most profitable deposits first. This is only a very coarse way of sorting because it ignores the amount being bridged. In practice it will probably tend to prioritise low-value transactions (which indirectly _may_ be the most profitable due to gas padding).
Sorting this early isn't compatible with v3 deposits because their profitability is determined later in the relayer run. In any case, ordering deposits by profitability doesn't seem to have much benefit in practice because it should only take effect at the absolute margins where the relayer can fill each deposit individually, but not the sum of them. So...remove it for now.

refactor: Remove relayerFeePct ordering in relayer

---

src/utils/FillUtils.ts

This linear search is extremely slow if there are a lot of partial fills (i.e. we created 400+ slow fills in a recent bundle) in a bundle that we have to evaluate as a possible unexecutable slow fill that was replaced by a fast fill.
With this many slow fills, it was taking 50 seconds to find the first partial fill for each slow fill, which would effectively make this function never able to complete with 400+ slow fills.
Early exiting means each search goes down to 5 ms, a massive speedup

fix: Early exit when searching for unexecutable V2 slow fills

---

.env.example
package.json
src/dataworker/Dataworker.ts
src/dataworker/DataworkerClientHelper.ts
src/dataworker/DataworkerConfig.ts
src/dataworker/DataworkerUtils.ts
src/dataworker/index.ts
src/interfaces/Arweave.ts
src/interfaces/index.ts
yarn.lock

This PR adds a persisted state to Arweave based on configurations in the data worker.
Three new environment variables have been added to the dataworker, these include:
1. PERSIST_BUNDLES_TO_ARWEAVE
2. ARWEAVE_WALLET_JWK
3. ARWEAVE_GATEWAY
New JWK wallets can be generated with the following snippet:
```
node -e "require('arweave').init({}).wallets.generate().then(JSON.stringify).then(console.log.bind(console))" > wallet.json
```
For testing, it is recommended to set
```
ARWEAVE_GATEWAY='{ "url": "localhost", "port": 1984, "protocol": "http" }'
```
and use `npx arlocal` to simulate an arweave-like server.
The wallet generated can be funded for use with `arlocal` via the following GET calls:
```
curl http://localhost:1984/mint/{arweave address}/{amountToMint}
curl http://localhost:1984/mine …
```

feat(proposer): store bundle to arweave

---

src/clients/BundleDataClient.ts
src/dataworker/Dataworker.ts
src/dataworker/DataworkerUtils.ts
src/relayer/Relayer.ts
test/Dataworker.blockRangeUtils.ts
test/Dataworker.loadData.ts

Reverts across-protocol/relayer-v2#1214

fix: Dataworker shouldn't call fillDeadlineBuffer for bundles whose start block is before V3 upgrade block

---

src/relayer/RelayerClientHelper.ts

These events are no longer relevant to the production relayer.

improve(relayer): Stop automatically querying for v2 events

---

src/clients/BundleDataClient.ts

This is currently causing bugs where future events (such as fast fills replacing slow fill requests) are affecting bundle data originally proposed before these events were known

fix(BundleDataClient): Throw away events before bundle end blocks

---

src/clients/BundleDataClient.ts

This way the bundle contents shouldn't change depending on the fill status changing of an expired deposit

improve: query fillStatuses as of bundle end block

---

src/clients/ProfitClient.ts
src/relayer/Relayer.ts

If preferred chain is not destination chain and destination chain is not 1 and preferred chain is not profitable, then try checking profitability of destination chain. If destination chain is profitable, still use preferred chain as repayment, and log the loss. This avoids penalizing honest depositors who set lp fee according to quote API which assumes payment chain is dest. chain.
This should allow the suggested-fees API to go back to quoting just the destination chain for quotes, which is usually the case for relays unless we're overallocated on a chain

improve(Relayer): Fallback to destination chain when resolving repayment chain ID

---

src/clients/SpokePoolClient.ts
src/clients/bridges/ZKSyncAdapter.ts
src/clients/index.ts

Extending and exporting a the SpokePoolClient class frequently causes tsc warnings to be flagged when running with a locally linked sdk-v2. The errors seem to be anchored in tsc not resolving the inherited parts of the SpokePoolClient correctly - it seems to view the SpokePoolClient as an opaque class that only contains the locally-overridden methods.
Now that it's physically impossible for an early v2 deposit event to occur, remove the override and revert to simply exporting directly.

improve(SpokePoolClient): Fix re-export

---

src/clients/MultiCallerClient.ts

This gets emitted when a slow fill request has already been sent for a relay hash.
Also adds case insensitivity to multicaller client

improve: Add InvalidSlowFillRequest known reason to MultiCallerClient

---

src/clients/BundleDataClient.ts
src/clients/InventoryClient.ts

We should save matched deposits into the dictionary, otherwise we violate an assumption that fiulls/slow fill requests that matched deposits have those deposits stored in memory

fix(BundleDataClient): When historical deposit is found, save into v3RelayHash

---

src/clients/MultiCallerClient.ts

Ignoring "execution reverted" is supressing some legitimate warnings like SpokePool being out of funds to execute a leaf

fix(MulticallerClient): Remove error reason that is produces false positives

---

src/dataworker/DataworkerClientHelper.ts

The Dataworker lookbacks are now short enough that they won't see any FundsDeposited events. RequestedSpeedUpEvents actually seem irrelevant here as well. We can technically still see these, but they're not used for validating fills.

chore: Drop Dataworker v2 deposit-related events

---

package.json
scripts/utils.ts
src/clients/ProfitClient.ts
src/common/Constants.ts
src/dataworker/DataworkerConfig.ts
src/relayer/Relayer.ts
yarn.lock

This PR (https://github.com/across-protocol/relayer-v2/pull/1185) was merged into `npai/v3Dataworker`. It was not automatically rebased like GitHub does when `npai/v3Dataworker` was merged.
This current PR aims to reinstate the logic that should've been added to master.
Note: please refer to these comments as the code should be the same https://github.com/across-protocol/relayer-v2/pull/1185

fix: reinstate logic for testnets

---

src/clients/ProfitClient.ts

Identified during the hackathon - a reverting deposit was incorrectly being bundled into a multicall and forcing the entire multicall to fail.

fix(ProfitClient): Don't attempt to fill reverting testnet txns

---

src/common/Constants.ts
src/utils/ProviderUtils.ts
src/utils/RedisUtils.ts

This changes the behavior of the provider caching system s.t. after a certain per-chain block distance in the past, we add no TTL so the cache stores it forever until it is forcibly evicted by redis's max mem eviction policy.

feat: add a block distance after which we set no TTL in redis

---

package.json
yarn.lock

Required to support Fault proofs on OP mainnet. Fault proofs going live on testnet this month so this PR is required to make finalizer work on testnets

improve: Update eth-optimism sdk to 3.2.x

---

src/clients/ProfitClient.ts
test/ProfitClient.ConsiderProfitability.ts

This change upgrades all ProfitClient tests to v3. It's submitted in advance of a subsequent PR to remove all v2 support from the ProfitClient.

refactor(ProfitClient): Update tests for v3

---

src/clients/ProfitClient.ts

The ProfitClient has, until now, used v2 fill estimates for its profitability calculations. This change upgrades to using v3 fills, which are slightly less expensive and should improve the relayer's perceived profitability when evaluating fills.
This is a pre-requisite for deprecating fillRelay() in the contracts.

improve(ProfitClient): Simulate v3 fills

---

src/clients/ProfitClient.ts

Gas estimation for fills on most chains has been on the low side and has not been representative of the actual cost of filling. This has been traced to the fill amount being set to 1 unit of the destination token, which leads to fee rounding in the SpokePool, in turn producing a lower than expected gas estimate. This is not representative of the true cost of a fill.
Having addressed the first issue, the use of WETH on mainnet destined for a recipient with 0 balance has proven to produce over-estimates for the fill cost. This seems to be due to the marginal cost of initialising a recipient's ETH balance to a non-zero value, with the delta being about 25k gas for doing so (verified by testing against an "unused" EOA vs. one with an ETH balance). WETH additionally incurs the marginal …

fix(ProfitClient): Correct gas estimation errors

---

src/clients/ProfitClient.ts
src/common/Constants.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts
test/mocks/MockProfitClient.ts

This change permits the relayer to have a separate gas multiplier for fills. This is desirable since fills with messages will typically have much higher gas consumption, so heavily discounting them is quite risky. However, ethers seems to over-estimate quite a bit, so it can be helpful to wind some of that back in some cases.

improve(ProfitClient): Permit applying gas multipler on message fills

---

src/relayer/RelayerClientHelper.ts

These events are not required by the relayer, so there's no need to query them.

improve(relayer): Drop unused SpokePool events

---

src/monitor/Monitor.ts
src/relayer/Relayer.ts
src/utils/FillUtils.ts
test/Relayer.UnfilledDeposits.ts

This is an incremental change to drop some unneeded members from the return type, and to return an Object of destination chain => unfilled deposits array. This permits the caller to keep the unfilled deposits segregated, which fits future use cases pretty well.
This is take #2 at this change, since the original commit incorrectly handled the deposit filtering based on the block lookback by applying the wrong "low block" for each chain Id.

refactor: Simplify FillUtils getUnfilledDeposits()

---

package.json
src/common/ClientHelper.ts
src/dataworker/DataworkerClientHelper.ts
src/monitor/MonitorClientHelper.ts
src/relayer/RelayerClientHelper.ts
yarn.lock

The relayer has no obvious need to query root bundle events, so skip them.
Note: Tests all pass, and I've also tested this on mainnet. It just needs the corresponding SDK-v2 PR to be merged, and a new package to be built (https://github.com/across-protocol/sdk-v2/pull/581).

improve(relayer): Don't query irrelevant HubPool events

---

src/relayer/RelayerClientHelper.ts

The InventoryManager does actually rely on HubPool events for repayment chain selection, so add this back in. We'll need to optimise elsewhere.

fix(relayer): Revert to querying the full set of HubPool events

---

src/relayer/index.ts

Use a random number to identify the start and end points for each relayer run, and record the time required to complete the run.

improve(relayer): Add execution time logging

---

package.json
src/common/ClientHelper.ts
src/relayer/RelayerClientHelper.ts
yarn.lock

The HubPoolClient now has logic to override the requested lookback for specific events if it has not previously been updated. This is the same logic that is implemented for the SpokePoolClients. As a result, it's now possible to be much more restrictive on the lookback for the HubPoolClient. The relayer can benefit from this be only querying RootBundle events for the past ~12 hours, which should be sufficient for the InventoryManager to determine repayment chains.

improve(relayer): Limit HubPoolClient lookback

---

src/clients/BundleDataClient.ts
src/clients/InventoryClient.ts
src/clients/bridges/ArbitrumAdapter.ts
src/clients/bridges/ZKSyncAdapter.ts
src/clients/bridges/op-stack/OpStackAdapter.ts
src/common/Config.ts
src/monitor/Monitor.ts
src/relayer/RelayerClientHelper.ts

We never practically need to look back more than 1 bundle, and trying to look back too many bundles leads weird errors in InventoryClient because it tries to compute bundle data using events its missing due to shortened HubPoolClient and SpokePoolClient lookbacks
Also, changes InventoryClient behavior that defaults taking repayment on mainnet if the BundleDataClient fails for some reason. We've seen in practice that taking repayment on mainnet for extended periods of time locks up bridge liquidity, so we'd actually rather take extra repayment on the spokes than on mainnet because we can always manually rebalance using external fast bridges or slow fills, rather than locking it up in 7 day ORU bridges

improve: Hardcode bundle refund lookback for relayer and monitor

---

src/clients/InventoryClient.ts
src/finalizer/index.ts

d35608d1b5522c4f12b0d018c8de173d1cbe8f02 changed behavior of this try-catch such that if catch is called, code continues rather than short circuiting. Therefore we need a default value for totalRefunds≈

fix: InventoryClient should set default values for `totalRefundsPerChain`

---

src/clients/InventoryClient.ts
src/finalizer/index.ts

Finalizer doesn't need HubPoolClient for most part except for latest data. This saves ~20-60s updating the hub pool client

improve: decrease finalizer HubPoolClient lookback

---

src/finalizer/index.ts
src/finalizer/utils/opStack.ts

A lot of the finalizer slowdown currently is querying withdrawl status information about TokenBridgedEvents. Optimize the lookback settings with the following changes
- OpStack: Don't submit proofs for any transaction older than 1 day. Don't try to withdraw any withdrawal earlier than 6.5 days old
- Polygon: Don't try to withdraw anything younger than 0.75 days
- ZkSync: Don't try to withdraw anything younger than 2 days

improve(finalizer): Optimize lookback windows

---

src/dataworker/Dataworker.ts

This copies the logic from `validatePendingRootBundle` that also should be used in executePoolRebalanceLeaf

improve(Dataworker): Don't send error-level log if invalid bundle reason is expected to be benign

---

package.json
src/common/ContractAddresses.ts
src/dataworker/Dataworker.ts
yarn.lock

Linea adds a constraint in the L2->L1 direction where we need to pass a payable `minimumWeiFee` to the `executeRelayerRefundLeaf`. 
We need to query this fee & pass it accordingly to the multicaller client.

improve(dataworker): allow linea to execute relay leaves

---

src/utils/ProviderUtils.ts

We should collect warnings that we want to see but don't want to pollute other channels in a new `across-warn` channel

improve: Send quorum warning to across-warn channel

---

package.json
yarn.lock

Bumps the SDK-V2 to use the updated slack logging format.

chore(sdk): bump to `v0.22.13`

---

package.json
yarn.lock

Version 3.2.2 of `@eth-optimism/sdk` removes the pre-install build script for `only allow pnpm`. This should resolve the outstanding issue we've been facing with intermittent CircleCI build failures in the relayer-v2.
In order to resolve this, @evaldofelipe and I have been working on the following steps after we identified the faulty package:
1. Bump the SDK's @eth-optimism/sdk version
2. Bump the Relayer's @eth-optimism/sdk version & bump the SDK-v2

fix(circle): mitigate circle-ci build failure

---

src/relayer/RelayerClientHelper.ts

The recent change to limit the relayer lookback in production did not consider that root bundles are not proposed every couple of ours on testnet. This rendered the relayer unable to complete a run.

fix(relayer): Reinstate testnet support

---

src/clients/BundleDataClient.ts
src/dataworker/Dataworker.ts
src/dataworker/DataworkerUtils.ts

There  are errors when trying to access block ranges at indices that exist in chain IDs but not in the block ranges list

fix: Dataworker and BundleDataClient should only use chain ID indices from HubChain bundle start block

---

src/dataworker/DataworkerUtils.ts
test/Dataworker.blockRangeUtils.ts

This  happens for the first bundle proposed containing a new chain

fix(blockRangesAreInvalidForSpokePoolClients): Handle case where bundle range start block is 0

---

contracts/AtomicWethDepositor.sol

Atomic WETH deposits aren't supported on Linea. We should use the Atomic depositor to unwrap/send WETH to Linea.
An item to note:
1. By only passing the `value` equal to the `amount` we're effectively preventing the AtomicWETHDepositor from allowing automatic executions to Linea. This is how the `LineaChainAdapter` performs its transfer.
2. To allow optional automatic filling, we'd need to be able to pass payable value such that `lineaL1MessageService.send{ value: amount + msg.value }(...)`

feat(linea): add entry for atomic depositor

---

src/relayer/RelayerClientHelper.ts

This allows relayer to ignore chains that haven't implemented the full inventory manager function set
This is not a bug seen in prod because RELAYER_DESTINATION_CHAINS is set to not include linea

fix: Relayer should only add chains to CrossChainTransferClient that are supported in AdapterManager

---

src/clients/AcrossAPIClient.ts

Lots of relayers running at same time is stressful on API requests

feat: Cache limits for 5 mins from Across API

---

src/utils/ProviderUtils.ts

The [previous PR](https://github.com/across-protocol/relayer-v2/pull/1315) for log sampling included the function, but didn't call it. This PR fixes that omission.

fix: call sample-wrapping function

---

src/relayer/RelayerClientHelper.ts

This reverts commit d3a614d581c09aeb744a7508f81299688ef9d31a.
These events were incorrectly dropped in a commit that aimed to reduce RPC overheads. In practice it neglects that that Relayer relies on these events via the InventoryClient and indirectly via the BundleDataClient.

Revert "improve(relayer): Drop unused SpokePool events (#1272)"

---

src/utils/ProviderUtils.ts

Previously these samples didn't include chainId, but this will be useful to filter for.

fix: add chainId to rpc samples

---

src/dataworker/Dataworker.ts
test/Dataworker.executePoolRebalances.ts

- Add details to logs
- Fix one bug to skip duplicate tokens in `_updateOldExchangeRates`.

improve(Dataworker): Make logs more clear when choosing to skip exchange rate updates

---

src/clients/BundleDataClient.ts
src/dataworker/Dataworker.ts
src/dataworker/index.ts

alternative solution to problem described in https://github.com/across-protocol/relayer-v2/pull/1350

feat: restructure loadData and rebalanceRoot cache to disallow parallelism

---

src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts
src/utils/fsUtils.ts

The recent change to support externally-defined inventory configs neglected to post-process the imported config. It's important to scale each configured amount before taking the config into use.

fix(relayer): Post-process external inventory config

---

src/relayer/Relayer.ts

Relayer fills are currently processed as a flat array. When messages are involved this requires simulation of the fill on the destination chain, thus incurring delay. In these cases, take the opportunity to process other fills whilst awaiting the outcome of the simulation. This is also another step towards containing RPC misbehaviour to the affected chain and preventing contagion to other destinations.

improve(relayer): Parallel processing for destination chain fills

---

package.json
src/clients/BundleDataClient.ts
src/clients/ProfitClient.ts
src/dataworker/Dataworker.ts
src/dataworker/DataworkerUtils.ts
src/dataworker/PoolRebalanceUtils.ts
src/interfaces/BundleData.ts
src/interfaces/index.ts
src/scripts/validateRunningBalances.ts
src/utils/FillUtils.ts
test/Dataworker.buildRoots.ts
test/Dataworker.loadData.ts
test/Relayer.BasicFill.ts
test/Relayer.SlowFill.ts
test/Relayer.UnfilledDeposits.ts
test/utils/utils.ts
yarn.lock

A follow-up change would drop all references to V3 types in favour of the vanilla variants. That hasn't been done here to keep this change on the smaller side.
(nb. requires a new sdk-v2 package so it's expected to fail build)

refactor: Drop v2 types

---

src/common/Constants.ts

Linea reduced the block time from 4s to 3s, so update all constants accordingly. Note also that the 10k block request range has proven incompatible with a few third-party providers, so drop the default range to 5k.

fix(Linea): Update constants after 3s block time update

---

src/clients/ProfitClient.ts

This fires on every run on testnet and pollutes the logs. It's a harmless issue and doesn't really need to be a warning; if someone encounters it in production they'll quickly figure it out anyway.

chore(ProfitClient): Reduce token warning to debug

---

src/utils/FillUtils.ts

This seems to be almost the only change required to support handling SpokePoolClients that fail to complete their update.

improve(FillUtils): Filter SpokePoolClients by update state

---

src/dataworker/DataworkerClientHelper.ts

A pending update to the sdk will allow the SpokePoolClient to continue in an un-updated state. The relayer is OK with this but the Dataworker requires a complete set of updated SpokePoolClient instances. Pre-empt this pending change by requiring explicitly that all Dataworker SpokePoolClient instances updated successfully. This is a case where it's OK (and expected) to fail hard.

chore(Dataworker): Explicitly require SpokePoolClient update

---

src/relayer/Relayer.ts
src/utils/FillUtils.ts
src/utils/TransactionUtils.ts

If the deposit fill status cannot be queried on the destination chain, revert to slower methods to determine the status. This fallback method is less accurate due to timing, but it allows execution to continue and the complete set of resulting deposits with unknown status will likely be reduced by subsequent filtering anyway (i.e. based on supported token, number of deposit confirmations, profitability, ...). The ultimate fill status for the residual deposits will be inferred at the time of fill simulation on the destination chain.

improve(FillUtils): Protect getUnfilledDeposits() against RPC error

---

src/clients/bridges/BaseAdapter.ts
src/common/Constants.ts

USDT on mainnet requires a spender's allowance to be zero prior to approving more value. 
This PR adds a zero'd approval if the token attempting to be approved is USDT.

fix(USDT): allow BaseAdapter to support approving USDT

---

src/clients/InventoryClient.ts
test/InventoryClient.RefundChain.ts
test/mocks/MockHubPoolClient.ts

For example, when `getBundleRefunds()` is called with `l1Token = USDT address`, then this function fails because USDT doesn't exist on Base, which is one of the enabled chains.

fix: Avoid error where we try to compute refunds for a {l1Token, chainId} combination that doesn't exist

---

src/clients/BundleDataClient.ts

Not every spoke pool client will be defined, therefore no need to check if one that doesn't exist is "updated"

fix(BundleDataClient): Filter chains based on which spoke pool clients are passed in to loadData

---

src/clients/BundleDataClient.ts

One more instance where spoke pool could be undefined, because the client for a destination chain for an expired deposit might not exist
Follow up to #1384

fix(BundleDataClient): Catch undefined SpokePoolClient

---

index.ts
src/utils/CLIUtils.ts
src/utils/Help.ts

This allows the various bot personalities to masquerade any arbitrary EOA and will make it significantly easier to test inventory configuration as another relayer.
The default read-only address is set to the main RL relayer, so to it's now possible to simulate it with the following incantation:
yarn relay --wallet void

feat: Support specifying read-only address for void signers

---

src/clients/BundleDataClient.ts

Cache the arweave request as a Promise so that we only make 1 request to Arweave per bundle block range. If these requests are sent in parallel, then the cache should be set to a Promise by the first request to send, and then when this request resolves, all parallel requests can use its response.

improve(BundleDataClient): Cache Arweave requests

---

index.ts
src/utils/ExecutionUtils.ts

The bot currently has 2 independent checks on POLLING_MODE - once at the top-level `index.ts` and once at `src/relayer/Relayer.ts`. A pending change will update `src/relayer/Relayer.ts` to support exiting gracefully after a SIGHUP request. The upper-layer check in `index.ts` prevents this by determining whether to loop or exit based on `config.pollingDelay`. There doesn't seem to be a strong justification for applying this looping at both levels, so remove the top-level of encapsulation for simplicity. Any bot personalities that require special looping behaviour can implement it locally, and if we see a common pattern emerge then it can bubble up to the top level once more.

refactor: Remove top-level bot loop

---

src/monitor/Monitor.ts
src/relayer/Relayer.ts
src/utils/FillUtils.ts

The `getUnfilledDeposits()` function invokes a BlockFinder instance on each chain and proceeds to resolve the lookback time delta to a block. It can be expensive to do this on chains where the average block times are not super consistent, so it sometimes causes longer-than-necessary delays.
All deposits sourced from each origin SpokePool subsequently have their fill status verified via the destination SpokePool contract, so the marginal cost for including additional deposits is quite small.
Note also that deposit lookbacks are still enforced on the SpokePoolClient search config, so looping mode is the only case where this filtering would have been effective. The current direction of looping mode is however to completely refresh the SpokePoolClient on each update, so there shouldn't be any …

refactor(relayer): Drop redundant unfilled deposit lookback filtering

---

src/clients/BundleDataClient.ts
src/clients/InventoryClient.ts
src/dataworker/Dataworker.ts
src/dataworker/DataworkerUtils.ts
src/dataworker/PoolRebalanceUtils.ts
src/dataworker/index.ts
src/monitor/Monitor.ts
test/Dataworker.executeRelayerRefunds.ts
test/Dataworker.loadData.ts
test/Dataworker.proposeRootBundle.ts
test/Monitor.ts
test/mocks/MockBundleDataClient.ts

- Fixes regression introduced in [#1362](https://github.com/across-protocol/relayer-v2/issues/1362) where refunds sent after proposed bundle are no longer computed and accounted for in `InventoryClient.resolveRepaymentChain` in favor of loading pendling bundle data from Arweave
- Removes `loadData` calls from all InventoryClient flows and replaces it with a function `getApproximateRefundsForBlockRange()` that filters on fills sent by relayer within the bundle block range and assumes all fills are valid which is a fair assumption and greatly speeds up the inventory client run
- Removes try-catch in InventoryClient since we should not expect any failures anymore when computing bundle refunds
- Adds Promise.all and promise caching to speed up overall inventory client call to …

fix(BundleDataClient): Handle refunds sent after pending bundle

---

src/clients/InventoryClient.ts
test/InventoryClient.RefundChain.ts

Simple change for now to start considering origin chain when considering post-relay allocations. The destination chain is preferred over origin chain but the latter is considered if (1) the origin chain token config is set and (2) the destination chain is over the target allocation
Fixes ACX-2040

feat(InventoryManager): Consider origin chain when computing post-relay allocations

---

src/relayer/Relayer.ts
test/Relayer.BasicFill.ts

I  manually comment out this line a lot when testing the relayer locally because I want to see how the relayer would evaluate a 
deposit's 
profitability and pick a repayment chain without sending a deposit.

improve(Relayer): Allow user to skip early exit for "un-finalized" deposits if in simulation mode

---

index.ts
src/utils/ExecutionUtils.ts

This change was previously merged and backed out shortly after because it was seen to result in some bot instances hanging. This is almost certainly because the original commit removed two instances of process.exit(), and replaced them with prococess.exitCode = <X>. There appear to be some instances where the bot can have some dangling promises that take a long time to resolve, or that don't resolve for some reason. Replaying the change, but without removing the process.exit() calls should be OK.

refactor: Remove top-level bot loop (take two)

---

src/utils/ProviderUtils.ts

This change tweaks env parsing to permit websocket providers to be defined. Websocket providers are identified by the _WS tag embedded in the name of the env var. This change is compatible with the existing syntax. For example:
Normal HTTPS provider: RPC_PROVIDERS_<chain-id>
Websocket provider:    RPC_WS_PROVIDERS_<chain-id>
Longer example:
\# Identify the default providers to be used.
RPC_WS_PROVIDERS=INFURA,ALCHEMY
\# Identify a specific provider to be used for zkSync.
RPC_WS_PROVIDERS_324=BLOCKPI
\# Define all websocket endpoints for INFURA
RPC_WS_PROVIDER_INFURA_1=wss://...
RPC_WS_PROVIDER_INFURA_10=wss://...
RPC_WS_PROVIDER_INFURA_137=wss://...
\# Define all websocket endpoints for ALCHEMY.
RPC_WS_PROVIDER_ALCHEMY_1=wss://...
RPC_WS_PROVIDER_ALCHEMY_10=wss://... …

feat(ProviderUtils): Support websocket provider definitions

---

src/dataworker/index.ts
src/finalizer/index.ts

This PR aims to parallelize the finalizer code using `Promise.all( )`. Instrumentation that breaks down speed of spokes & finalizer/dataworker functions has also been added to capture improvements of this change. 
A draw of this PR is that it makes logs produced by the finalizer less linear.
Timings **prior** to optimization
```
2024-04-12 17:46:24 [debug]: {
"at": "Finalizer#index",
"message": "Time to loop: 85.80977033400535s",
"timeToUpdateSpokeClients": 23.340696208953858,
"timeToFinalize": 62.4690741250515,
"bot-identifier": "not-james"
}
2024-04-12 17:49:17 [debug]: {
"at": "Finalizer#index",
"message": "Time to loop: 85.8968901669979s",
"timeToUpdateSpokeClients": 23.311546999931334,
"timeToFinalize": 62.585343167066576,
"bot-identifier": "not-james"
}
```
Timings **post** …

improve(finalizer): improve finalizer performance

---

src/dataworker/Dataworker.ts
test/Dataworker.executePoolRebalances.ts

There is one missing case not handled:
- HubChain Leaf for a token has a negative net send amount, so no exchange rate needed
- RelayerLeaf for token has a positive amount to return. This adds virtual balance for the token
- non-HubChain leaf for the token has a positive net send amount. The `liquidReserves + amountToReturn` is still `< netSendAmount`. This throws an error. However, we should be checking if calling `exchangeRateCurrent` on the `liquidReserves` sends liquid reserves above the required amount. This follows the pattern in the other two exchange rate update cases

fix(executor): Handle edge case when executing non-hub-chain pool leaves

---

src/clients/bridges/ArbitrumAdapter.ts
src/clients/bridges/PolygonAdapter.ts
src/clients/bridges/ZKSyncAdapter.ts

We should use the more dynamic `this.hubChainId` and `bnZero` instead of hardcoding 1 & BigNumber.from(0)

improve(adapters): make adapter more dynamic

---

src/dataworker/Dataworker.ts
src/dataworker/index.ts
test/Dataworker.executePoolRebalances.ts

`executePoolRebalanceLeaves` sends `.error` level logs if it tries to execute pool rebalance leaves but gets front-run. SpokeLeaf execution failures do not send `.error` level logs because I believe they are allowed to fail in simulation (except HubChain leaves which get batched with pool leaf executions).
This PR adds a return value to `executePoolRebalanceLeaves` so the index.ts runner can know if any pool leaf executions have been enqueued. If any have been, then run a similar check to https://github.com/across-protocol/relayer-v3/pull/1425 and exit early if the root bundle has already been executed

feat(Dataworker#index): Catch PoolRebalanceLeaf execution collisions

---

src/relayer/Relayer.ts

The motivation here is that the rebalancer should not log about unprofitable deposits. The fix is to reduce the log level of this message if relaying is off. This way local testing can still produce this log but running the rebalancer is less noisy.

improve(Relayer): Don't log about unprofitable deposits if not relaying

---

package.json
src/utils/RedisUtils.ts

Redis has unintentionally been used in the TokenClient tests when tested in a local development environment. It hasn't affected CI because there's no redis cache available there.

fix(test): Prevent Redis from being used in test

---

src/libexec/RelayerSpokePoolIndexer.ts

SetPoolRebalanceRoute events are now used to infer SpokePool token addresses, so EnabledDepositRoute events are no longer required. This should enable the fast relayer to consistently resolve its token balances on first loop, and should reduce its average fill times.

improve: Don't scrape EnabledDepositRoutes in external indexer

---

src/dataworker/index.ts

When the executor runs very slowly, say ~10 mins, then its possible that its run can start while a root bundle proposal is still pending, but in the middle of its run, the pending root bundle can be executed and the next bundle can be proposed.
The proposal would cause the current logic for detecting an `executorCollision` to give a false negative, resulting in an error suffered in the MulticallerClient.
This PR adds a check to `executorCollision` that the pending root bundle challenge timestamp is in the future in addition to its unclaimedLeafCount being positive.
An alternative implementation I considered was comparing the pending root bundle's `poolRebalanceRoot` with the one stored in the `HubPoolClient`. I think that would work as well.

improve(Dataworker#index): Handle executor run not completing before subsequent proposal is sent

---

src/dataworker/DataworkerClientHelper.ts
src/finalizer/index.ts
src/monitor/MonitorClientHelper.ts
src/relayer/RelayerClientHelper.ts
src/scripts/validateRunningBalances.ts

These are no longer necessary for the relayer. This change has already been implemented in the fast relayer.
This event is by far the most request-intensive in the relayer, so I'm hopeful of a nice speed-up once it goes into prod.

improve(relayer): Skip querying EnabledDepositRoute events

---

src/clients/AcrossAPIClient.ts
src/relayer/Relayer.ts
src/relayer/RelayerClientHelper.ts
test/Relayer.BasicFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts

When querying limits, the API client current uses mainnet as the origin chain. The buffers applied on deposits originating from mainnet are typically negative, implying that Across can support _more_ volume than is available as liquid reserve in the HubPool. This effectively renders the limits check redundant and could cause the relayer to overcommit the HubPool by incorrectly making a fill.
While here, apply a slight refactor in recognition that API client doesn't need require SpokePoolClient instances anymore, so drop them in favour of a simple chain ID list. This removes the current constraint that mainnet needs to be defined as a destination chain. This adjustment makes the relayer more flexible and should be popular with third-parties.
Fixes ACX-2100

fix(AcrossAPIClient): Reverse limits query direction

---

src/clients/MultiCallerClient.ts

We don't want to pollute relayer logging channels that are not sending relays. For example, the rebalancer runs the full relayer run in order to get an accurate count of its inventory but it shouldn't care about whether the relays succeed or not in simulation.

improve(MulticallerClient): Don't log sim failures as "error" level if simulate=true

---

test/Dataworker.executePoolRebalances.ts

The use of smock in the Dataworker executePoolRebalances test means that multicall output needs to be predefined. This is needed in advance of an sdk-v2 update, which uses multicall() in HubPoolClient.update().

fix(test): Prime multicall in Dataworker test

---

src/clients/TokenClient.ts

This is the minimum change required to unconditionally query USDC aliases on non-mainnet chains.
Post-CCTP I could imagine that we return to refactor this, such that we have a more common/central handling of token aliases. That would also be useful if Tether ever does something similar.

feat(TokenClient): Support querying additional USDC deployments

---

package.json
src/scripts/validateRunningBalances.ts
src/utils/index.ts
tasks/integration-tests.ts
test/utils/index.ts
test/utils/utils.ts
yarn.lock

This PR does two things:
1. It pulls in the new logger, which should allow all Across bots to use the new `run-identifier` [feature](https://github.com/UMAprotocol/protocol/pull/4745) added in the upstream `@uma/logger` package.
2. It replaces the `@uma/financial-templates-lib` package with the `@uma/logger` package, since we only use the re-exported logger portion of the FTL package.

feat: add run-id compatible logger and replace FTL with logger package

---

src/clients/InventoryClient.ts

The WETH address is known separately from the HubPoolClient so its token address can be queried directly. This eliminates a few uses of getDestinationTokenForL1Token().

refactor(InventoryClient): Drop unnecessary token resolutions

---

src/clients/InventoryClient.ts
test/InventoryClient.InventoryRebalance.ts

InventoryClient._getPossibleRebalances() accepts a TokenDistributionPerL1Token type, but actually only uses the set of L1 tokens defined. This can be sourced elsewhere in order to simplify the implementation and allow TokenDistributionPerL1Token to be updated.
Note that this commit doesn't attempt to make any functional changes to the InventoryClient - it's moreso decoupling the code so that different parts can be updated to support multiple L2 tokens.

refactor(InventoryClient): Simplify possible rebalances check

---

src/clients/bridges/ArbitrumAdapter.ts
src/clients/bridges/BaseAdapter.ts
src/clients/bridges/PolygonAdapter.ts
src/clients/bridges/op-stack/OpStackAdapter.ts

When we attempt to approve tokens, we have to be sure that the l1Tokens and their associated bridges have the same length. The CCTP change made the bridge list longer than the L1 token list.

hotfix(adapter): correct length of parallel arrays

---

src/clients/bridges/PolygonAdapter.ts
src/clients/bridges/op-stack/DefaultErc20Bridge.ts
src/clients/bridges/op-stack/OpStackAdapter.ts
src/clients/bridges/op-stack/OpStackBridgeInterface.ts
src/clients/bridges/op-stack/UsdcCCTPBridge.ts
src/clients/bridges/op-stack/UsdcTokenSplitterBridge.ts
src/clients/bridges/op-stack/WethBridge.ts
src/clients/bridges/op-stack/optimism/DaiOptimismBridge.ts
src/clients/bridges/op-stack/optimism/SnxOptimismBridge.ts

- If `bridges` is type string, we can't call .length on it otherwise we'll inadvertently use the char count of the string
- Must add WETH to l1Token list before early exiting

fix(bridges): Rename l1Gateway to l1Gateways and return string[] always

---

src/monitor/Monitor.ts

- this.clients.hubPoolClient.hubPool.getCurrentTime() returns a Promise, so the comparison was never returning true
- the grace period of 4 hours is no longer useful for a bundle period of 1 hour and an 80 minute bundle frequency. This is shortened to 45 mins, meaning don't look for stuck rebalances until we're 45 mins through since the last bundle was executed

fix(monitor): Fix stuck rebalance report grace period logic

---

src/monitor/Monitor.ts
test/Monitor.ts

This function contains logic to handle Across V1 bond transfers and in general is not super useful. It adds a ton of overhead to the monitor and is currently buggy. I'd prefer to just remove it.

feat(Monitor): Remove unknown transfers tracking

---

src/clients/bridges/AdapterManager.ts
src/clients/bridges/ArbitrumAdapter.ts
src/clients/bridges/BaseAdapter.ts
src/clients/bridges/LineaAdapter.ts
src/clients/bridges/PolygonAdapter.ts
src/clients/bridges/ZKSyncAdapter.ts
src/clients/bridges/op-stack/OpStackAdapter.ts

We forgot to include this filter line that we have in other adapters.

fix(OpStackAdapter): Filter out available l1 tokens when computing outstanding transfers

---

src/relayer/Relayer.ts

Will be useful when new chains are added. It should be hard to miss this since it logs noisily, but it otherwise defaults to a safe value that permits the relayer to continue to operate until the config is fixed.

improve(relayer): Warn on incomplete MDC config

---

src/utils/ProviderUtils.ts

These fields are not set for zksync eth_getLogs responses returned by Alchemy. They are not used in our code so we don't need to compare them for quorum purposes

improve(ProviderUtils): Add fields we can ignore when requesting eth_getLogs

---

package.json
src/clients/HubPoolClient.ts
src/clients/ProfitClient.ts
src/monitor/Monitor.ts
src/relayer/Relayer.ts
src/utils/TokenUtils.ts
yarn.lock

Currently we sometimes use the function to grab L2 token info rather than L1 token info.
It doesn't really have any impact because we mostly want just the `symbol` and `decimals` but there is one place in the `Relayer` where we do want the actual L1TokenAddress. I've changed this to call a new function `getL1TokenInfo` instead of `getTokenInfo` which we can use along with the l2 token address already given to query outstanding cross chain transfers correctly following #1469
`getL1TokenInfo` assumes that each token symbols map entry has an L1 token address so this PR also bumps the constants-v3 version that has l1 token addresses for all USDC variants

improve: Make it clear when we want the L2 versus L1 token info when querying TOKEN_SYMBOLS_MAP

---

src/monitor/Monitor.ts

Dong-Ha identified that a deposit on Arbitrum incorrectly used the Arbitrum USDC.e address as the outputToken for a fill on Base. In case the outputToken can't be resolved, fall back to symbol "unknown" and log the raw amount.

fix(Monitor): Be robust to whacky output tokens

---

src/clients/InventoryClient.ts

The set of rebalance chainIds was incorrectly changed from `getEnabledL2Chains()` to `getEnabledChains()` in the previous commit.

fix(InventoryClient): Ignore mainnet in rebalance evaluation

---

src/clients/InventoryClient.ts
test/InventoryClient.InventoryRebalance.ts

Logs correctly the case where there are multiple L2 tokens defined in the token config for a single l1 token

improve(InventoryClient): Log L2 token balances separately

---

src/clients/HubPoolClient.ts
src/clients/InventoryClient.ts
src/relayer/Relayer.ts
src/utils/AddressUtils.ts
test/InventoryClient.InventoryRebalance.ts

Handle case where an L2 token for chain ID can map to more than one TOKEN_SYMBOLS_MAP entry. For example, L2 Bridged USDC maps to both the USDC and USDC.e/USDbC entries in TOKEN_SYMBOLS_MAP.
This PR is a temporary patch that handles the known USDC issue where both USDC.e/USDbC contain the same chain-address combinations as the USDC entry. This can be reverted once we remove the USDC entry in the TOKEN_SYMBOLS_MAP.

fix: Handle L2 USDC symbol lookup 

---

package.json
yarn.lock

Get access to _USDC symbol in TOKEN_EQUIVALENCY_REMAPPING

fix: Bump constants v3 version

---

src/clients/InventoryClient.ts

See comments in PR for description. Triggered by case where Polygon USDC variant is officially Native USDC but fills with polygon as destination are using Bridged USDC as output

fix(InventoryClient): Handle case where input = Bridged USDC and output is Bridged USDC on chain where Native USDC is supported

---

src/finalizer/utils/arbitrum.ts
src/finalizer/utils/linea/l2ToL1.ts
src/finalizer/utils/opStack.ts
src/finalizer/utils/polygon.ts
src/finalizer/utils/zkSync.ts

These l2-->l2 finalizers will all break when trying to finalize an l2 token that is no longer linked to l1 via PoolRebalanceRoutes, like USDC.e for 137,10,8453,42161
We haven't seen this yet because polygon, the only CCTP enabled chain so far, has not withdawn any funds from L2 to L1

fix(finalizer): Look up L1TokenInfo using TOKEN_SYMBOLS_MAP

---

src/dataworker/DataworkerUtils.ts

This should only cause bugs currently when validating older bundles pre-pool rebalance route upgrade, but thsoe bundles have been fully 
executed already so the warnings are noise. This fixes warnings where older bundle roots can't be reconstructed bc the wrong pool 
rebalacne route is being used to map tokens

fix(Dataworker): Use correct pool rebalance route token mapping

---

src/libexec/RelayerSpokePoolIndexer.ts

PD alerts are occasionally raised regarding a 1200 second timeout on the fast relayer. Logs indicate that the relayer is actually exiting, so additional logs are needed in the external listener process to isolate the issue.

improve(indexer): Additional debug logging

---

src/clients/TokenClient.ts

The recent change to use multicall incorrectly uses the hub chain signer for remote chain tokens. This results in very confusing and counter-intuitive failures when the remote chain does not support multicall.
Also:
- There's no need to query the HubPoolClient for L2 token addresses when the target chain is the hub chain itself.
- Remove a redundant Promise.all().

fix(TokenClient): Use correct signer on direct token queries

---

src/finalizer/utils/arbitrum.ts
src/finalizer/utils/cctp/l1ToL2.ts
src/finalizer/utils/cctp/l2ToL1.ts
src/finalizer/utils/opStack.ts
src/finalizer/utils/polygon.ts
src/finalizer/utils/zkSync.ts

Currently the finalizer is optimized for run-time speed and tries to look over as short of an event search window as possible.
However, this provides very little margin for error in case the finalizer goes down for multiple days.
this PR gives every finalizer 7 days to look over events for outstanding finalizations

improve(finalizer): Increase margin of error for finalizer to cover for multiple day down-time

---

src/finalizer/utils/arbitrum.ts
src/finalizer/utils/cctp/l1ToL2.ts
src/finalizer/utils/cctp/l2ToL1.ts
src/finalizer/utils/opStack.ts
src/finalizer/utils/polygon.ts
src/finalizer/utils/zkSync.ts

We’re not de-duping the set of txn receipts to query for CCTP l2 to l1 deposits, but we do this in the l1 to l2 direciton.
What’s unique for L2 to L1 is we look for SpokePool.TokensBridged() events but we forget there might be multiple of these in the same block

fix(Finalizer): Dedup transaction hash list when creating list of transactions to query for CCTP l2->l1 transactions

---

src/finalizer/utils/arbitrum.ts
src/finalizer/utils/linea/l1ToL2.ts
src/finalizer/utils/linea/l2ToL1.ts
src/finalizer/utils/opStack.ts
src/finalizer/utils/polygon.ts

`TokenBridge` events that use CCTP to transfer tokens off Polygon are causing `UNKNOWN` errors to be thrown in the GCP logs. The reasoning is that our simulations are trying to simulate `exit()` with bridge events that did not originate on the canonical bridge. 
We can't directly filter out the `TokenBridge` events before the simulation logic because we need to be aware of potentially multiple events in one transaction for the `getUniqueLogIndex` and the subsequent call to `buildPayloadForExit`.
This PR simply makes these CCTP message have an error code of `NON_CANONICAL_BRIDGE` which prevents the message from actually being simulated and being pushed to the `finalizableMessages` array.
--
Note: this bug is mainly causes noise & shouldn't directly impact finalization since we catch this …

fix(finalizer): polygon

---

src/monitor/Monitor.ts
test/Monitor.ts

Currently we are only querying L2 tokens mapped to l1 tokens via PoolRebalanceRoutes, which means we are not reporting Bridged USDC balances

fix(reporter): Accumulate L2 token balances mapped to same L1 token address

---

src/finalizer/utils/cctp/l2ToL1.ts

Only Base has a block height lower than Ethereum's so we're missing all of the Base CCTP withdrawals

fix(CCTPFinalizer): Set `fromBlock` from correct `chainId`

---

src/monitor/Monitor.ts

Adds some special logic to break out USDC.e balances from USDC. L1 USDC is counted with Native USDC balance.
This is required to be a special case because the balance report uses the L1 token symbol mapped to all L2 tokens as the key, whereas USDC.e and Native USDC on L2s both map to a single USDC token, so we need to invent a "USDC.e" virtual L1 token to keep the structure of the report intact.
A more scalable change would have to change the report structure fundamentally.

improve(reporter): Add special USDC.e entry

---

src/libexec/RelayerSpokePoolIndexer.ts

In pursuit of a transient error in production. It may be related to 5xx errors on the WebSocketProvider.

improve(indexer): More debug logging

---

src/finalizer/utils/opStack.ts

Filter for events to finalize is incorrectly only counting events older than 14 days old. This PR changes it to look 
at any events older than 7 days old

fix(finalizer): OpStack finalizer filter

---

src/clients/MultiCallerClient.ts
src/dataworker/index.ts
test/Dataworker.executePoolRebalances.ts
test/Dataworker.executeRelayerRefunds.ts
test/Dataworker.executeSlowRelay.ts
test/Dataworker.proposeRootBundle.ts
test/Dataworker.validateRootBundle.ts
test/Monitor.ts
test/MultiCallerClient.ts

This permits a single chain to have its queue executed, returning a single array of transaction hashes. This is a prerequisite for a relayer change to further decouple per-chain execution.

refactor(MultiCallerClient): Permit single-chain execution

---

src/clients/bridges/ZKSyncAdapter.ts

This probably has no effect when the relayer doesn't loop, but it does cause problems in looping mode.

fix(ZkSyncAdapter): Set correct search fromBlock after update

---

src/relayer/Relayer.ts
src/relayer/index.ts
test/Relayer.BasicFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts

Failing to do this can produce a lot of log spam that is ultimately unnecessary.

improve(relayer): Ignore deposits for disabled destination chains

---

src/relayer/RelayerConfig.ts

Bug found because `unwrapWethThreshold` in rebalancer seemed to be getting ignored, turned out it was never getting parsed because this line was always false

fix(RelayerConfig): Read symbol not address

---

src/monitor/Monitor.ts

Resets default to 60 mins, and reads from process.env. where possible

improve(Monitor): Allow stuck rebalance monitor grace period to be configured

---

src/dataworker/Dataworker.ts

Simple QoL improvement but avoids false errors due to executor collisions in serverless mode

improve(Dataworker): Exit early in pool rebalance leaf execution if leaves are already executed

---

src/dataworker/DataworkerConfig.ts
src/dataworker/index.ts

We can run the pool rebalance leaf executor separately from the refund leaf executor to speed up both bots. It takes ~3 minutes to reconstruct a bundle, so executing the pool rebalance leaf + 2 refund leaf bundles into the past leads to 9 mins of run time just to execute pool rebalance leaves.

feat(Dataworker): Split l2 and l1 executors

---

src/clients/BundleDataClient.ts
src/dataworker/Dataworker.ts
test/Dataworker.loadData.ts

Loading bundle data is now consistently taking 3-5 minutes given increased volume, likely stemming from increase in total bridge events per bundle
I've narrowed down, using timers, the slowdown to the `loadDataFromScratch` and the `SpokePoolClient.update()` calls which together account for most of the vast majority of the total run time for any dataworker function
- Replacing `utils.getRelayHashFromEvent` implementation takes current bundle construction with ~5000 deposits and fills runtime from 160s to 5s within the `loadDataFromScratch` function.
- Fetching bundle data from Arweave instead of from scratch in the Executor saves executor time
- Added timers for loading bundle data to help track regressions

improve(Dataworker): Speed up BundleDataClient.loadDataFromScratch

---

src/relayer/Relayer.ts
src/utils/FillUtils.ts
test/Relayer.UnfilledDeposits.ts

The looping relayer is forced to drink from the fire hose when determining the set of unfilled deposits. In times of high demand this can lead to a lot of unnecessary looping to filter out deposits that have already been filled. This change adds tracking of fill status across loops in order to permit already-filled deposits to be filtered out as early as possible.

improve(relayer): Persist fillStatus across loops

---

src/dataworker/Dataworker.ts
src/dataworker/DataworkerUtils.ts

We noticed that the Dataworker failed to reconstruct a bundle using Arweave bundle data but could reconstruct the same bundle using fresh data from scratch. This indicated corrupted data posted to Arweave.
When investigating Arweave, we noticed that all the bundleData looked correct except for `bundleFillsV3.refunds` which contained refunds for expired deposits. This is odd and unexpected since refunds should only be filled with fast fill refunds, not expired deposit refunds. This led me to realize that [this function](https://github.com/across-protocol/relayer/blob/13c5f17db14f11789f3fb6322f52183293fdb3cd/src/dataworker/DataworkerUtils.ts#L233) touches both `bundleFillsV3.refunds` and `expiredDeposits`, which led me to then realize that we are mutating the former when examining the …

fix(Dataworker): Shallow copy refunds object when constructing RelayerRefundRoot

---

src/common/Constants.ts

Linea has a frustrating failure mode where some large multicall transactions will be accepted by their RPC, but will hang forever without confirmation. Subsequent transactions are rejected with REPLACEMENT_FEE_TOO_LOW. This has caused problems in the executor when trying to execute a lot of slow fills, and external intervention is needed.

fix(config): Limit Linea multicalls to 50 transactions

---

src/common/Config.ts

loadAndValidateConfigForChains() runs after the MultiCallerClient is instantiated, so assigning `config.multiCallChunkSize` to a new record forks the config and prevents updating the MultiCallerClient's internal config.

fix(MultiCallerClient): Don't overrwrite env config

---

.eslintrc.js
src/clients/BundleDataClient.ts
src/dataworker/Dataworker.ts

The `no-misused-promises` rule enforces unresolved promises to be resolved before used (e.g. in a boolean conditional or in an object). Adding this in the linter will ideally prevent bugs which occur due to handling promises instead of the resolved value.

lint: add no-misused promises to linter

---

contracts/MockLineaEvents.sol
src/clients/bridges/LineaAdapter.ts
src/common/ContractAddresses.ts
src/finalizer/utils/linea/common.ts

Linea have upgraded their token bridge and emit BridgingInitiatedV2 instead of BridgingInitiated. This allows for filtering on receipient to occur, at the expense of amount.
Required before merge:
- Do we ever rely on filtering by amount?
- Do all ERC20s now emit `BridgingInitiatedV2`, or do some still emit `BridgingInitiated`?
- Is this event emitted in both directions?
Side note: I initially thought we'd need the Linea SDK v0.3.0 and had spent some time struggling to update to it. It causes a lot of things in the current Linea adapter implementation to break, and the fixes seem non-trivial. I suspect we might want to re-architect the Linea finalizer to rely less on type unions, because it's painful when Consensys rug the types we rely on.

fix(Linea): Define BridgingInitiatedV2

---

src/clients/InventoryClient.ts
src/clients/bridges/CrossChainTransferClient.ts
src/relayer/RelayerClientHelper.ts

When inventory management is enabled, make cross-chain transfer querying for each chain conditional on the corresponding SpokePoolClient having been updated. This addresses a constraint that exists the various bridge adapters, whereby they rely on the SpokePoolClient having been updated first in order to piggyback on its event search config.

improve(relayer): Conditionally update cross chain transfers

---

package.json
src/clients/SpokePoolClient.ts
yarn.lock

This was not used in practice and has been removed upstream.

refactor: Drop CCTP from SpokePoolClient update

---

src/clients/InventoryClient.ts

If there are no pending repayments for the target chain, assume 0.

fix(InventoryClient): Fallback to 0 pending repayments

---

src/dataworker/Dataworker.ts
src/finalizer/index.ts
src/finalizer/utils/arbitrum.ts
src/finalizer/utils/linea/common.ts
src/finalizer/utils/linea/l1ToL2.ts
src/finalizer/utils/opStack.ts
src/finalizer/utils/polygon.ts
src/utils/NetworkUtils.ts
src/utils/SDKUtils.ts
yarn.lock

In preparation for NCA, we should remove all instances where we hardcode the chain IDs so that the bots will not automatically assume we are on mainnet.

improve(finalizer): remove hardcoded constants

---

package.json
yarn.lock

Finalizer uses SDK to submit proofs and finalize withdrawals but there was a bug in the current version when reading status of withdrawals and also creating calldata to submit proofs/finalize withdrawals

fix(optimism): Update to fault-proof-supported SDK

---

src/relayer/Relayer.ts
test/Relayer.BasicFill.ts

Any users of SpokePool.depositV3Now() inherit the origin chain's block.timestamp as their quoteTimestamp. Any integrators who call deposit() or depositV3() and supply block.timestamp for quoteTimestamp will see the same result. On fast L2s this will almost always be ahead of the latest HubPool timestamp. Per current relayer implementation, these deposits are silently ignored until the quoteTimestamp is behind the HubPool timestamp.
The risk of resolving an inaccurate LP utilisation at the quoteTimestamp is significantly reduced in v3, such that it's probably now not worth being strict on. The residual risk of future quoteTimestamps is really only when there are large gaps in which HubPool utilisation could change dramatically, and even then, the effect should be small (relayer repayment …

improve(relayer): Relax future quoteTimestamp constraint

---

src/relayer/RelayerClientHelper.ts

Checking the logs more closely, it's obvious that some chain adapters repeatedly produce the same copies of deposit hashes. This creates duplicates and will result in delays and odd results in balance projections. A proper fix is needed in the adapters, but this is deferred for now because of the ongoing new-chain automation work.

fix(relayer): Skip cross-chain transfer tracking when looping

---

src/clients/bridges/ArbitrumAdapter.ts
src/clients/bridges/LineaAdapter.ts
src/clients/bridges/PolygonAdapter.ts
src/clients/bridges/ZKSyncAdapter.ts
src/clients/bridges/op-stack/base/BaseChainAdapter.ts
src/clients/bridges/op-stack/mode/ModeAdapter.ts
src/clients/bridges/op-stack/optimism/OptimismAdapter.ts
src/common/Constants.ts

We want to be able to modify a small number of files (e.g. those in `src/common`) in order to support a new chain. A low-hanging fruit which also shrinks the diff in this PR: https://github.com/across-protocol/relayer/pull/1524 will move the tokens supported by a specific route to our constants. 
The motivation for this is to eventually be able to construct a generic adapter which can fetch all of its configuration directly when all it knows is its chain ID.

improve(adapters): centralize chain supported tokens

---

src/clients/TokenClient.ts

USDC was required back when constants defined _USDC, but now it's just a duplicate.

refactor(TokenClient): Cleanup USDC symbol aliases

---

src/common/Config.ts

This will be useful for the sweeper bots, where we don't want an attempt at filling a recent-ish deposit in a multicall to derail a fill for a much older deposit.

improve(multicaller): Permit global chunk size override

---

src/common/Constants.ts
src/monitor/Monitor.ts
test/Monitor.ts

Even if root bundle relay from L1 to L2 doesn't contain token transfers, we should still warn if something is stuck

feat(monitor): Add logs about stuck root bundle relays

---

src/clients/AcrossAPIClient.ts

The API was recently updated to return a modified definition of maxDeposit, such that it is capped at the largest desirable deposit amount (but not necessarily the largest deposit that Across can support). This change also added a destinationChainId-dependent aspect, which is incompatible with the relayer's existing use of the API where it tries to only query from anywhere -> mainnet to determine limits. This caused flow-on effects in the relayer where it would refuse to make fills that were perfectly OK to fill. This change restores the ability of the relayer to accurately fill based on configured limits.

fix(AcrossAPIClient): Support liquid-reserves query

---

src/utils/ProviderUtils.ts

We had an issue where Infura's Optimism RPC provider went down, leading to a large number of quorum disputes for `eth_getBlockByNumber` between Alchemy and Quicknode, particularly in the `totalDifficulty` field. This commit should filter out that field so we won't error if RPCs disagree on it.

fix(ProviderUtils): filter out totalDifficulty from RPC response

---

package.json
scripts/utils.ts
src/clients/bridges/AdapterManager.ts
src/finalizer/index.ts
src/finalizer/utils/linea/l1ToL2.ts
yarn.lock

We need to bump the constants repository to the most up-to-date version so we can use the respective Lisk information. A byproduct of this version bump is getting rid of all Goerli references in the relayer repository. This change also enables Lisk in the chain adapters and finalizer.

feat(finalizer): add Lisk to AdapterManager and finalizer

---

src/common/Constants.ts

Using symbols ensures that chain IDs can't accidentally be mistyped. While here, flush all Görli references because they're not longer needed. The ordering of entries is unchanged here; in a follow-up PR I will reorder alphabetically.

refactor(constants): Use symbolic chain labels

---

src/clients/bridges/op-stack/OpStackAdapter.ts

The DAI and SNX Optimism bridge adapters expect to receive the l1Signer before the l2Signer.

fix(dai): Correct signer ordering to bridge adapter constructor

---

src/common/Constants.ts
src/finalizer/utils/opStack.ts

The eth-optimism SDK does not have predefined contract addresses for Lisk like it does for all of our other OP Stack chains. This causes finalizations to throw undefined errors. This commit adds in the necessary contract addresses which we then pass into the optimismSDK's `CrossChainMessenger`. We will also need to do something similar for Blast.

fix(finalizer): define contract addresses required for Lisk finalizations

---

src/common/ClientHelper.ts
src/common/Config.ts
src/dataworker/DataworkerClientHelper.ts
src/monitor/MonitorClientHelper.ts
src/monitor/MonitorConfig.ts
src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts

The relayer currently has an annoying constraint that it needs to be updated each time a new chain is added to the config store. This is because the post-update configuration validation is unnecesarily strict. In cases where the relayer has a custom set of origin and destination chains, it actually doesn't make sense to require that configuration is defined for any new chain that has been added.
So:
- When the relayer does not rely on a new chain, don't verify configuration for that chain.
- When the relayer does rely on a new chain, warn about missing config and revert to a conservative default of 5k blocks for eth_getLogs() calls. The warnings should prompt the operator to update their bot or define the necessary config in their environment.

improve(relayer): Avoid friendly fire when new chains are added

---

src/clients/bridges/BaseAdapter.ts
src/common/ContractAddresses.ts
src/common/abi/Weth.json

Blast uses a non-standard OP address for WETH. The address we had specified was off by a single digit (0x42.....04 instead of 0x43..04). 0x42..04 is an OP predeploy, so deposit() simulation failed. Had it been an EOA then there was potential for loss of ETH when attempting to wrap to WETH. To protect against this in future, first call WETH.symbol() to verify that the destination contract is an ERC20, and secondly to verify that the contract claims to be a WETH implementation. This should catch the absolute majority of mistakes that could occur here.

fix(Blast): Correct WETH address

---

src/utils/ProviderUtils.ts

zkSync updated their RPC today and it disagreed with the third-parties on this field.

fix(ProviderUtils): Ignore zkSync blockTimestamp

---

src/common/Constants.ts

A 1x multiplier inherits the default 1.5 Gwei pricing from ethers and causes OP stack fills to be expensive.

improve(Constants): Revise OP stack priority fee multiplier

---

src/common/Constants.ts
src/relayer/Relayer.ts

The relayer doesn't need to respect HubPool limits on these deposits.

fix(relayer): Ignore HubPool liquidity on Lite deposits

---

src/finalizer/utils/opStack.ts

This changes the opStack finalizer to attempt finalizations on all OpStack chains after a seven day period.

fix(finalizer): blast finalizations now take 7 days

---

src/clients/bridges/AdapterManager.ts
src/clients/bridges/ScrollAdapter.ts
src/clients/bridges/index.ts

This instantiates a Scroll Adapter based off of the new generic adapter code. This is a smaller fix since I did not want to modify the Inventory/CrossChainTransfer clients when we would have to revert them back as soon as the generic code replaces the current.

feat(scroll): Add Scroll adapter

---

src/relayer/Relayer.ts
src/relayer/RelayerConfig.ts

Number.MAX_SAFE_INTEGER had a special meaning in the config code, so if
the operator incidentally used it as the actual configured MDC for a
threshold any given chain, the safe upper-limit would not be applied.

fix(relayer): Set fallback deposit confirmation defaults

---

src/relayer/Relayer.ts

This can otherwise occur due to inventory configuration and deposits made on lite chains.

fix(relayer): Don't assert on unresolved repaymentChainId

---

src/clients/InventoryClient.ts

The existing one-liner was marginally too clever and resulted in unintuitive behaviour. In the pre-existing code the expression would unconditionally be evaluated via the ternary statement, so any env-defined target overage would be ignored.
It's apparently not valid (...or maybe not wise) to combine a nullish coalescing operator with a ternary statement. It is possible to fix this in a one-liner by wrapping the ternary statement in brackets, but it feels risky to retain that so I've split the expression into two lines.
Having done some additional testing, the conclusion is that lite-chain overrides are tricky unless explicitly specified in the environment. The reason for this is that the existing relayer config parser automatically populates   targetOverageBuffer entries for all tokens …

fix(InventoryClient): Subtle target overage syntax error

---

src/relayer/RelayerConfig.ts

Once the upper MDC config taps out, permit anything in excess to be filled after the subsequent block. This is an improvement over the current config, because presently the relayer requires Number.MAX_SAFE_INTEGER (...lots) blocks before it'll fill these.

improve(relayer): Permit filling above MDC config

---

src/clients/InventoryClient.ts

This issue is especially pronounced with Lite chains such as Lisk, where filling a deposit from mainnet to Lisk may result in unwanted repayment on Lisk, causing the relayer's balance to be perpetually above target. In general, Lite chains cause the relayer to end up with a lot of inventory on the lite chain so we should aim to take repayment away from the lite chain when we get the chance.

improve(relayer): swap priority of origin/destination for Lite chain relayer repayments

---

src/clients/ProfitClient.ts

Integrators who are using Across settlement for in-protocal swaps are specifying unknown output tokens and it's causing quite a bit of noise in the logs.

fix(ProfitClient): Reduce log level for unexpected output token

---

src/relayer/Relayer.ts

In cases where the age of the deposit exceeds the uppermost configured deposit confirmation limit, just revert to the uppermost limit. This protects against resolving an index of -1, which causes a subsequent blowup when we try to reduce the limits for that index.

fix(relayer): Protect against unresolved limit idx

---

src/clients/InventoryClient.ts

Inventory management reacts badly if it tries to resolve a missing inventory config for a particular chain. This makes the bot unnecessarily fragile.

fix(relayer): Gracefully handle partial inventory config

---

src/clients/SpokePoolClient.ts
src/libexec/RelayerSpokePoolIndexer.ts
src/relayer/RelayerClientHelper.ts
src/utils/EventUtils.ts
test/EventManager.ts

The fast relayer currently imposes a finality overlay onto each indexer process, such that each process will wait for <finality> blocks, and will then forward events that have met quorum, or discard them. The actual number of blocks that is used for <finality> is the lowest MDC tier. For most chains this is 1 or 2 blocks, and for Polygon this is ~32.
This is fragile on chains with very short block times and results in some events being dropped due to delayed delivery of events by some RPC providers. Additionally, on chains with a high number of MDCs, it imposes an a long delay on relaying the events. This can be meaningful in the case of FilledV3Relay events, which are now used by the relayer to track its origin chain commitments.
With this change, retain events for a longer period and …

[WIP] improve(relayer): More robust fast relayer event ingestion

---

src/adapter/bridges/BaseBridgeAdapter.ts
src/adapter/bridges/ScrollERC20Bridge.ts

This is a simple fix to the issue we had for resolving a USDC address for scroll, whereby we would include a special case in `resolveL2TokenAddress` in BaseBridgeAdapter. This moves this logic to the Scroll bridge so this conditional won't be triggered by all bridges.

improve(bridges): add special USDC case for the ScrollBridge.

---

src/dataworker/Dataworker.ts
src/dataworker/DataworkerUtils.ts
src/dataworker/index.ts
src/interfaces/BundleData.ts
src/interfaces/index.ts

This PR adds a feature to the disputer which allows it repersist data to arweave in the event the pending bundle is valid, since it also reconstructs valid bundle data from scratch.
This way the disputer can have multiple chances throughout the bundle's challenge period to repersist to arweave.
A future PR would add this ability to the executor

feat(Dataworker): Move persistence of bundle data step to Disputer instead of Proposer

---

src/clients/BalanceAllocator.ts
src/common/ContractAddresses.ts
src/finalizer/utils/zkSync.ts
src/monitor/Monitor.ts
src/monitor/MonitorConfig.ts
src/utils/TokenUtils.ts

Motivation:
- Seeing lots of warning when trying to refill ETH from one account to another because the sender has lots of WETH but not enough ETH.
Features:
- Add feature in Monitor to automatically unwrap WETH into ETH when trying to refill ETH on Ethereum
- Refactor/rename functions to better support a future where we have different native tokens per chain.
Details
- Found a bug where we incorrectly assume that the `eth` address on Polygon is 0x0, but the MATIC address seems to be: [0x0000000000000000000000000000000000001010](https://polygonscan.com/token/0x0000000000000000000000000000000000001010)
- This has never really been an issue up until now since we make the correct balance calls (provider.getBalance) anyways even though we make faulty assumptions that the polygon eth token is …

improve(Monitor): Unwrap WETH on Ethereum when attempting to refill ETH for configured accounts

---

src/libexec/RelayerSpokePoolIndexer.ts

Some providers throw sporadic errors; without this it's difficult to troubleshoot which provider is responsible.

improve: Log provider information on websocket error

---

src/clients/SpokePoolClient.ts
src/relayer/index.ts

Websocket errors can sporadically cause a child listener process to hang, such that it doesn't respond properly to a channel disconnect or HUP from the parent.

fix(relayer): Hard stop child process on exit

---

src/clients/SpokePoolClient.ts
src/libexec/RelayerSpokePoolIndexer.ts

Rather than trying to recover a websocket error, just log it and try to keep going. Eventually it will bail; the parent can then be responsible for restarting it if necessary.

refactor(relayer): Rearrange external listener loop

---

package.json
src/clients/HubPoolClient.ts
src/utils/AddressUtils.ts
src/utils/CCTPUtils.ts
src/utils/SDKUtils.ts
src/utils/TokenUtils.ts
yarn.lock

Related to https://github.com/across-protocol/sdk/pull/705 - adds integrated sdk work back into the relayer.

improve(sdk): use sdk types/utils/hub

---

src/relayer/Relayer.ts

The relayer channel should ideally only show successful fills

feat: Log unprofitable fills in separate channel

---

src/adapter/bridges/ZKSyncWethBridge.ts
test/generic-adapters/zkSync.ts

The monitor thought there were stuck rebalance roots for zkSync since the `ZkSyncWethBridge` was unable to track HubPool transfers. This is because the code was based off of an older version [here](https://github.com/across-protocol/relayer/blob/c2f847c90b024d6970b0306654e68968479348ab/src/clients/bridges/ZKSyncAdapter.ts#L74) which has since been updated. This PR makes the changes to allow the monitor to use the hubPool as a monitored address.

fix(zkSyncWethBridge): enable hub pool tracking

---

src/clients/InventoryClient.ts
src/relayer/Relayer.ts

If Rebalancer, not Relayer, is running (i.e. config.sendingRelaysEnabled == false), then don't log about not being able to fill a deposit due to over allocation on lite chain.
Moreover, improve the logs by moving the informative log about over allocation from the inventory client to the relayer

improve(Relayer): Tune down lite chain repayment logs for rebalancer

---

src/relayer/index.ts

These log messages can be very large and can kill the log transport.

improve(relayer): Don't log ignored addresses on startup

---

src/clients/InventoryClient.ts

We will sometimes take repayments on on lite chains for routes from non-lite chains to lite chains. This is undesirable since it requires the relayer to manually pull funds back via the canonical bridge. We should prioritize taking repayment on non-lite chains whenever possible, so this PR makes the inventory client always select either a slow repayment chain or the origin chain when filling on a lite chain.

improve(relayer): take refunds on origin when filling on a lite chain.

---

src/clients/SpokePoolClient.ts

In the event that a child process terminates improperly, ensure that it is logged by the relayer. This will be extended in future to support restarting the listener process.

improve(SpokePoolClient): Log on failed listener

---

src/clients/SpokePoolClient.ts

This is normal behaviour but it's interesting to know if the parent does not register that the child exits, so continue to log on SIGKILL but at a lower log severity.

fix(relayer): Lower log severity on listener SIGKILL

---

src/relayer/Relayer.ts

No reason to log the full deposit object, and send to unprofitable fill channel. You can argue that an over allocated lite chain produces deposits that are unprofitable from a rebalancing perspective to fill

improve(Relayer): Reduce size of overallocated-lite-chain log and send to special channel

---

src/clients/BundleDataClient.ts
src/common/Constants.ts
src/dataworker/DataworkerUtils.ts
test/Dataworker.blockRangeUtils.ts
test/Dataworker.loadData.fill.ts

Bundle data client incorrectly marks a deposit as invalid when its origin chain block number is greater than the origin chain bundle end block
- This bug was discovered after https://github.com/across-protocol/relayer/commit/aa1ec0d4b9fe6f902be298632dd01e786e07c17c was deployed and it marked a deposit as invalid. Ironically, it wasn't a deposit that was too old that was triggered an invalid fill, but a deposit that was in the future that was ignored
- I would label this as a fix for a long-standing bug
Separately, increase lookback required for spoke pool clients to better accomodate situation where a fill is sent well after a deposit was mined but before it expired.
- This is a follow up to https://github.com/across-protocol/relayer/commit/aa1ec0d4b9fe6f902be298632dd01e786e07c17c

fix(BundleDataClient): Don't mark deposits in the future as invalid

---

src/relayer/index.ts

This log message is too large and is overwhelming the Slack logging transport. Drop it for now to see whether relayer behaviour improves.

fix(relayer): Don't log config on startup

---

src/utils/ProviderUtils.ts

The zkSync public provider is returning different results than the Alchemy and Quicknode providers since the `logsBloom` field is non-empty. 
To reproduce, run `cast rpc eth_getBlockByNumber 0x28d20b6 false --rpc-url $RPC`.
Public zkSync logsBloom:
```
0x00000000000400000000202000200000000000000000000200001000006810000000004000200000380000440028000000010000000002000400000000600200000284000108040000400008000050000000000010000120002400000002080000000000020010000000000050000904004000000600000000400050000000000000002000000000000004200004010120000000006000100004020000000100022001200100100000100000000014200000000000000801000000000000400000001002008400000001000040600800000000800000000000028000000020000410004000000050000000000000000000008100908800000000244000043000
```
Alchemy/Quicknode logsBloom …

fix: ignore logsBloom field for eth_getBlockByNumber rpc

---

src/relayer/Relayer.ts
test/Relayer.BasicFill.ts

If there are no deposits then it doesn't make sense to compute this. Defer it in order to reduce log noise.

refactor(relayer): Defer origin chain limits computation

---

src/relayer/RelayerConfig.ts
src/relayer/index.ts

This is not used in prod and it introduces unnecessary branching logic, so drop it to enable some subsequent refactoring.

refactor(relayer): Drop SKIP_RELAYS env configurable

---

src/relayer/RelayerClientHelper.ts
src/relayer/RelayerConfig.ts
src/relayer/index.ts

SKIP_REBALANCING and SEND_REBALANCES are opposites, so there's no reason to have support for both.

refactor(relayer): Drop SKIP_REBALANCING env configurable

---

src/relayer/Relayer.ts
src/relayer/index.ts

This ensures that token approvals are in place for all tokens held by the relayer EOA. For 99.999% of the time it's fine to do this once on startup; it doesn't need to be repeated on each loop.
This also removes a redundant tokenClient.update() call that is being performed on each loop.

refactor(relayer): Add one-time relayer init

---

src/adapter/BaseChainAdapter.ts

The contract object is quite large and seems to be upsetting the logger
\- potentially due to recursion when unpacking the JSON object. There's
no need to log the contract anyway; the intention is only to log the
address.

fix(relayer): Skip logging contract object on eth wrap

---

src/utils/ProviderUtils.ts

`logger` used to be globally defined in the `ProviderUtils` file. See [here](https://github.com/across-protocol/relayer/blob/955d2da9c373143ecb4e6ed1c8a383d0acd5006b/src/utils/ProviderUtils.ts#L19) and [here](https://github.com/across-protocol/relayer/blob/955d2da9c373143ecb4e6ed1c8a383d0acd5006b/src/utils/ProviderUtils.ts#L504)
As for most of the `getProvider` calls we are not explicitly setting the logger (see [here](https://github.com/across-protocol/relayer/blob/mguevara/default-logger/src/libexec/RelayerSpokePoolIndexer.ts#L226) for example), we should set a default logger for the `RetryProvider`.

fix: set default logger for retry providers

---

src/utils/ProviderUtils.ts

The SDK provider requires a winston logger or it will default to console transports.

fix(providers): pass logger to provider

---

src/relayer/Relayer.ts

Per current implementation, the relayer can prematurely mark a deposit as filled if it _intends_ to fill it. This can however be derailed in the event that the destination chain has pending fills, in which case the fill transaction is discarded. This creates problems for fill status tracking, which is otherwise marked at the time the transaction is enqueued.
The simple fix is to filter candidate deposits by whether their destination chain has pending fills. A more optimised version, which might follow, would apply a pending status for these fills and would apply that pending status at the time of transaction submission. That's more complex for an (at best) marginal benefit, so proceed with the simple solution for now.

fix(relayer): Don't prematurely mark deposits as filled

---

src/scripts/validateRootBundle.ts

The Dataworker complains that 8 bundles is insufficient to cover the 6
hour fillDeadlineBuffer with a 1 hour challenge window, so bump it to 10.

fix(validateRootBundle): Bump DATAWORKER_FAST_LOOKBACK_COUNT

---

src/clients/MultiCallerClient.ts

This should prevent submitting transactions when we build a tryMulticall and all internal transactions revert in simulation.

fix: do not submit multicall transactions with no calldata

---

src/dataworker/Dataworker.ts

Without this check, the code produces a Lisk block range of [6063320, 6063319] when validating the proposal associated with dispute https://etherscan.io/tx/0x5255006f0a66f151d6a419b876dd673f94ec85a97cd3570bc54f7def7a6422a6.
This originally arose because the primary RPC provider used for determining the latest block number on Lisk had an outage and began severely lagging the head of the chain, such that the proposer was not able to increment its end block number past the previous proposal's end block number due to the Lisk block buffer imposed on new proposals.

fix(dataworker): Don't permit out-of-order block ranges

---

.eslintrc.js
package.json
src/adapter/bridges/OpStackWethBridge.ts
src/adapter/utils.ts
src/clients/SpokePoolClient.ts
src/clients/TokenTransferClient.ts
src/clients/bridges/op-stack/OpStackAdapter.ts
src/clients/bridges/op-stack/OpStackBridgeInterface.ts
src/clients/bridges/op-stack/WethBridge.ts
src/clients/bridges/utils.ts
src/interfaces/index.ts
src/libexec/RelayerSpokePoolIndexer.ts
src/scripts/validateRunningBalances.ts
src/utils/CCTPUtils.ts
src/utils/EventUtils.ts
src/utils/index.ts
test/EventManager.ts
test/Relayer.IndexedSpokePoolClient.ts
yarn.lock

This follows a similar change in the SDK, with the same motivations. Reverting to Log instead of Event does not sacrifice any functionality but makes it easier to migrate away from ethers v5.

refactor: Replace ethers Event with Log

---

src/relayer/index.ts

The existing limit of 10 loops was somewhat imprecise and was too short as observed in production. This would occasionally trigger asserts in the BundleDataClient because it requires all SpokePoolClient instances to be updated. Instead, permit up to 120 seconds before proceeding.

improve(relayer): Permit up to 120s for SpokePoolClient readiness

---

src/relayer/Relayer.ts

This message can be quite spammy in the main logging channel, so redirect it to the more acceptably-noisy "unprofitable fills" channel.

improve(relayer): Redirect in-protocol swap message

---

src/utils/FillUtils.ts

getUnfilledDeposits() currently unconditionally computes the deposit version (i.e. the ConfigStore VERSION value applicable at the deposit quoteTimestamp), and then filters out all the deposits that have been filled. Determining the relevant version implies a lot of Array.find() calls, all of which is wasted when the object is subsequently discarded.

improve(relayer): Defer deposit version computation

---

src/finalizer/index.ts

This should probably have been part of the larger commit to support World Chain. It has been tested locally and successfully submitted a proof for a WBTC withdrawal.

feat: Support finalizing on World Chain

---

src/adapter/bridges/UsdcCCTPBridge.ts

This is a simple fix to guarantee that the rebalancer will not try to send an amount over CCTP which is greater than 1 million USDC, however, if we needed to send over 1 million USDC, this fix would split the transfers into multiple runs. 
Currently in draft so that we can see if there is a simple solution to be able to send > 1M USDC with CCTP in the same rebalancer run.

fix: force maximum USDC rebalance amount over CCTP to 1M

---

src/utils/AddressUtils.ts

This is to prevent resolving to an `undefined` when calling `getTranslatedTokenAddress` for USDC on Zora.

fix: resolve proper zora usdc address

---

src/utils/TransactionUtils.ts

Continuation of https://github.com/across-protocol/relayer/pull/1834. Now, we will always get the nonce based off of the most-recent confirmed transaction for each new run of a bot.

improve: force nonce reset across all chains

---

index.ts
src/clients/TransactionClient.ts
src/utils/LogUtils.ts
src/utils/TransactionUtils.ts

Closes ACX-3032
We've been seeing occasional error logs like `error: "[object Object]"`. AFAICT these can occur if the caught value is not an instance of the `Error` class. We _might_ be able to get more information if we use `JSON.stringify` instead if the thrown value is not an error. 
Also, if we use `JSON.stringify` on an error instance it returns `{}` if it doesn't implement a custom `toJSON` method. 
To cover both cases above, this PR therefore introduces a `stringifyThrownValue` that can be used for logging.

fix: error log stringify

---

src/finalizer/index.ts
src/finalizer/utils/arbStack.ts
src/finalizer/utils/index.ts

The Arbitrum finalizer was using `CHAIN_IDs.ARBITRUM` in all locations.

feat(alephzero): make arb finalizer generic

---

src/finalizer/utils/polygon.ts

There is a bug in the Polygon finalizer where a single transaction contains multiple token withdrawals from Spoke to Hub in which more than 1 million USDC are withdrawn, resulting in a single `TokensBridged` event getting emitted but multiple USDC "burns" happening (due to the CCTP 1mil withdrawal limit).
This messes up the `logIndex` computation math for any withdrawals that take place after the USDC withdrawals. This logic isn't needed in other chains with CCTP like Arbitrum or Optimism because the `logIndex` is relative to all other non-CCTP withdrawals, whereas in Polygon it seems that CCTP withdrawals also count towards the `logIndex` of non CCTP withdrawals

feat: handle Polygon finalizer edge case when CCTP limit is breached

---

src/relayer/Relayer.ts

The existing logic incorrectly only short-circuits when the fill status is unfilled. Once this has happened, the fill status changes to SlowFillRequested and the relayer will proceed to evaluate it as per its normal fill logic.

fix(relayer): Don't fast fill any deposit made by a slow depositor

---

src/adapter/BaseChainAdapter.ts

`indexOf` does not work for complex types, so this instead creates a "hash" of the token/bridge pair and removes duplicates via whether this string is the same.

fix: dedup bridges to approve properly

---

scripts/withdrawFromOpStack.ts
src/common/abi/OpStackStandardBridgeL2.json
src/finalizer/utils/opStack.ts

Updates script `withdrawFromOpStack` to support ERC20 withdrawals (e.g. USDT) and updates finalizer to automate these. Helps with withdrawing ERC20's from Lite chains

feat: Manual withdrawals of ERC20 on OpStack lite chains

---

scripts/spokepool.ts
src/clients/AcrossAPIClient.ts
src/clients/ProfitClient.ts

Permit the ACROSS_API_HOST env var to override the standard app.across.to and testnet.across.to API hostnames.
While here, sub out some hardcoded chain IDs.

improve(relayer): Better support for custom Across API host

---

src/common/Constants.ts
src/dataworker/Dataworker.ts
src/dataworker/DataworkerUtils.ts

We've received feedback from a user of the arweave data that its easier if the arweave stored `bundleBlockRanges` is a mapping of chainId to bundle block ranges rather than a list. This PR also shortens the `tag` used to uniquely identify bundle data to just a mainnet block associated with the bundle, which should always be unique. This avoids the 2048 tag length limit which we'd eventually run into.
example txn: https://arweave.app/tx/jBk5WzugtYMSa1jnXxEH7XN3Q6n0R_jxYsO6WkDHMc4

improve(arweave): Change arweave data key from list of chain ID's to map

---

package.json
scripts/withdrawFromArbitrumOrbit.ts
scripts/withdrawFromOpStack.ts
src/common/ContractAddresses.ts
src/common/abi/ArbSysL2.json
src/common/abi/ArbitrumErc20GatewayL2.json
src/finalizer/utils/arbStack.ts
yarn.lock

Similar to #1866 for OpStack but for Arbitrum Orbit.
Replaces original PR #1898 with smaller commit history. I essentially took the core changes and copied and pasted here, to avoid rebase hell

feat(AlephZero): Add manual withdrawal script and automate finalizations

---

src/monitor/Monitor.ts

There are reports which seem to either have an incorrect relayer refund amount or pool rebalance amount, and since there are no logs in `checkSpokePoolRunningBalances`, it is difficult to debug these occurrences. This should make it easier to understand if/why there are anomalies in the balance reports.

improve(reporter): log rebalance information for debugging

---

src/monitor/Monitor.ts

Right now, we're exporting strings to datadog, which you can't do numerical aggregations on. This changes the output to numbers.

fix: make datadog types numbers rather than strings

---

src/monitor/Monitor.ts

The logs for datadog are outputting balances for all tokens on all chains, causing there to be a lot of extraneous logs (i.e. we are having logs for BOBA on Lisk, or USDC on Blast). This is also causing the reporter logs to be ~70k lines, which also is likely why the reporter logs end abruptly in GCP. This should reduce the number of logs significantly and hopefully make balance reporting work for the fast relayer again.

improve: only log relayer balances for tokens on supported chains

---

package.json
test/Dataworker.loadData.slowFill.ts
test/Relayer.BasicFill.ts
test/Relayer.SlowFill.ts
yarn.lock

For some RPC-related improvements & bugfixes, as well as:
- WBTC on Lisk.
- POOL on World Chain.
- USDC.e on Aleph Zero.

chore: Bump constants, contracts & sdk

---

src/relayer/RelayerConfig.ts

This will be used to limit the fill size on testnet in order to preserve the relayer's token balance.

improve(relayer): Permit testnet deposit confirmation override

---

src/relayer/Relayer.ts

We currently log deposits that are ignored because they are from over-allocated lite-chains as unprofitable, but this isn't super clear.
These deposits will have no preferred repayment chain [chosen](https://github.com/across-protocol/relayer/blob/72279954ddb71e008b1e7a6c43c8b901b55acc53/src/relayer/Relayer.ts#L1064) by the inventory client and the lpFeePct will get set to [infinity](https://github.com/across-protocol/relayer/blob/72279954ddb71e008b1e7a6c43c8b901b55acc53/src/relayer/Relayer.ts#L1082). This produces a very noisy log that claims the deposit is unproftable but in reality, it was ignored because it came from an overallocated lite chain.

improve(Relayer): Log clearer about overallocated lite chain deposits 

---

src/relayer/Relayer.ts

This is incorrectly dereferencing the `unprofitableDeposits` object, which is type `{ chainId: UnprofitableFill[] }`
Separately, the `depositMrkdwn` doesn't render well unless I put the ternary inside a ${} syntax

fix(Relayer): Fix unprofitable deposit log

---

src/clients/ProfitClient.ts
src/relayer/Relayer.ts

When determining why a deposit is unprofitable its definitely useful to know upfront if there is a non empty message in the deposit, which often indicates we failed to simulate the fill.
This PR also sends the warning about failure to estimate gas costs for deposit to a different slack channel than "unprofitable fills". 
We should isolate across-unprofitable-fills channel to only include messages for deposits that are unprofitable. The developer should then go to across-warn to figure

improve(Relayer): Add information about message size to unprofitability log

---

package.json
scripts/zkSyncDemo.ts
src/clients/ProfitClient.ts
src/utils/TransactionUtils.ts
yarn.lock

This reverts commit 72279954ddb71e008b1e7a6c43c8b901b55acc53.
This imports 3.4.7 as well as reverts the above commit. This SDK change will use the priorityFeeMultiplier correctly for Linea, previously the baseFeeMultiplier was used to scale the Linea priority fee.

Reapply "improve: Use base fee multiplier option in SDK to resolve gas fees (#1969)" (#1985)

---

src/common/ContractAddresses.ts

Using the chain id alias instead of the actual number should make this file easier to read, which will become more important the more chains we add.

nit: prefer use of chain id alias in constants

---

src/clients/ProfitClient.ts

`GRASS` is enabled as a token in the hub pool (for liquidity provision), but we are unable to query its price on coingecko. This causes the testnet bot to fail repeatedly, so this PR adds an exception for sepolia to map unknown tokens to ETH.

fix: add token mapping exception for sepolia

---

src/utils/ContractUtils.ts

Required because `SONEIUM` uses the codename `Cher` therefore we have:
```
export { Cher_SpokePool__factory } from "./factories/contracts/Cher_SpokePool__factory";
```

hotfix(soneium): cast to codename

---

src/relayer/Relayer.ts

This log message was added during the v2 -> v3 transition where it was interesting to know about deposits with unsupported outputTokens. There are now other protocols building on top of Across and supporting this, so it generates quite a bit of log spam. Reduce the loglevel and the information bundled in the log.

improve(relayer): Reduce token swap log spam

---

src/clients/SpokePoolClient.ts
src/dataworker/Dataworker.ts
src/relayer/Relayer.ts

SpokePoolClient doesn't set depositId correctly in a rare case.
Also, to be safe, log a known BN as a string where we currently don't do so

fix(IndexedSpokePoolClient): Cast depositId correctly

---

src/common/Constants.ts

Reduces amortized gas cost at expense of locking up some capital. I think this is worth it given how often we need to top up the fee payer for executing L1 leaves

improve(dataworker): Fund more fee tokens into fee payer address

---

package.json
test/Dataworker.loadData.fill.ts
test/mocks/MockConfigStoreClient.ts
yarn.lock

This activates another upgrade to the BundleDataClient, which should now be able to (partially) handle bytes32 addresses.

chore: bump sdk version for new BundleDataClient

---

src/scripts/validateRunningBalances.ts

Simple refactor to suppress some noisy logs and also use `chainIsOPStack` where we currently hardcode chain ID's

improve(validateRunningBalances): Replace hardcoded OP stack chain ID's

---

src/relayer/Relayer.ts
test/Relayer.BasicFill.ts

We should prefer sending a slow fill over self relays.

improve: prefer slow fills over self relays

---

package.json
test/Dataworker.loadData.fill.ts
yarn.lock

The main utility of this PR is to now coerce specific address fields ingested by the spoke pool client to bytes20 addresses. Functionally, this should have no effect on any of the bots, since all spoke pool events emit `address`es and not `bytes32` values, but this will be necessary to have active when the contracts upgrade goes live.

feat: bump sdk to use new utilites

---

src/relayer/Relayer.ts

The relayer calls SpokePoolClient.getFillForDeposit to find a fill to determine if its committed capital to filling deposits from an origin chain. This function however can match with an invalid fill.

fix(Relayer): Identify correct fills when computing commitments

---

src/relayer/Relayer.ts

The intention of computing origin chain commitments is to identify how much the relayer has filled for a given origin chain within a given timeframe. Filtering out invalid fills incorrectly reduces the perceived commitment and makes this feature effective.

fix(relayer): Origin chain commitments should include invalid fills

---

src/libexec/SpokePoolListenerExperimental.ts

The viem provider has suffered from odd performance issues on some chains, whereby subscriptions have seemed not to work. This has produced very long fill times, but only on some chains.
After some debugging, poor performance is isolated to chains with quorum > 1. This was ultimately traced to the naming of the client vs. the naming of the transport, which is currently what is named uniquely. Because the top-level client was named generically "Public Client", the downstream event manager was unable to distinguish the same event from different providers, so these chains typically did not meet the quorum requirement with quorum > 1.
While here, restore the JSON stringification hack for bigints. Without this, any JSON.stringify() involving a BigInt produces an exception. This makes debugging …

improve(relayer): Override fast relayer bigint JSON encoder

---

src/libexec/RelayerSpokePoolIndexer.ts
src/libexec/SpokePoolListenerExperimental.ts
src/libexec/util/evm/util.ts

The fast relayer doesn't need to care about these anymore. Most other bots still do though.

chore(relayer): Skip queries for V3 event types

---

src/finalizer/index.ts
src/finalizer/types.ts
src/finalizer/utils/cctp/l1ToL2.ts
src/finalizer/utils/linea/l1ToL2.ts

Currently we are always using the hub pool client's lookback to find events in the l1 to l2 direction, which is [hardcoded to 8 hours](https://github.com/across-protocol/relayer/blob/8028594423460034c064c73faf5ed994812bb6dc/src/finalizer/index.ts#L435). But if we wanted to increase this lookback using the MAX_FINALIZER_LOOKBACK environment variable, it would unexpectedly not affect the lookback in the L1 to L2 direction.

improve(l1l2Finalizer): Make sure L1 finalizer uses hub chain spokepool's lookback

---

src/utils/LogUtils.ts

`Error.toString()` doesn't stringify the stack. This change always try to log the trace now if available

fix: log error stack when stringifying

---

package.json
src/scripts/validateRunningBalances.ts
test/Dataworker.loadData.unexecutableSlowFill.ts
yarn.lock

See SDK [PR](https://github.com/across-protocol/sdk/pull/880) for details about bundle data client change that will avoid producing invalid unexecutable slow fill requests. There is an edge case where a pre-slow-fill request from a prior bundle can trick the bundle data client into creating an unexecutable slow fill and send funds from Spoke to Hub. This doesn't result in lost LP funds--it just reallocates them unexpectedly.
Additionally, updates the `validateRunningBalances` script which I used to debug this issue.

fix(Dataworker): Handle edge case for unexecutable slow fill requests

---

src/relayer/index.ts

Currently seeing some issues on startup and it'd be nice to be able to extend the wait time before bailing.

improve(relayer): Permit configuration of max startup delay

---

src/clients/InventoryClient.ts

Its possible that the RootBundleExecued event for a chain and token is old enough that the ProposedRootBundle event is older than the earliest block searched. In this case,  our best way to approximate the running balance is to use the running balance from the RootBundleExecuted event plus any deposits and minus any refunds seen in the entire spoke pool client's lookback. This lookback window is correct to use because the bundle end block associated with the RootBundleExecued by definition must be older than the spoke pool client's lookback. If we can't even see the ProposedRootBundle event then the bundle end block must be even older

fix(InventoryClient): Handle when ProposedRootBundle event preceding RootBundleExecuted event cannot be found

---

src/clients/SpokePoolClient.ts

This corrects an issue in the fast relayer instance that was exposed after the previous update.

fix(relayer): Don't assume a [V3]FundsDeposited was read

---

src/relayer/index.ts

If the relayer's execution loop is taking long enough that it does not sleep between loops, a transaction that is pending submission may appear to take a long time because its post-submission task cannot be scheduled.
This change enforces a minimum delay of 0.1 seconds when there are transactions pending submission in order to ensure the submission tasks are not CPU-starved.

improve(relayer): Ensure relayer yields execution between loops

---

src/relayer/Relayer.ts
test/Relayer.TokenShortfall.ts

Brought to our attention from other relayers, calling fillV3Relay does not let us fill deposits with deterministic deposit IDs, so we should start calling fillRelay.

improve: start calling `fillRelay` over `fillV3Relay`

---

src/monitor/Monitor.ts

The spoke pool reporter keeps the total amount the spoke pool must pay out internally as a positive integer (e.g. it has balance of 100 ETH but must pay out 20 ETH on the next bundle). When there are slow fills for a specific token on a monitored network, the spoke pool reporter is incorrectly subtracting the slow fill amount from the total amount it must pay out from the spoke instead of adding it. This causes the reports to be incorrect, and when the slow fill amount exceeds the amount it needs to pay out with relayer refunds, we even get a "negative" refund amount, which clearly isn't possible. Here is an example incorrect log for USDC on Arbitrum (order is current balance, obligations, pool rebalance amounts, and virtual balance (current balance - obligations + pool rebalances)):
``` …
```

fix: correctly accumulate refund amounts in spoke reporter

---

src/dataworker/DataworkerConfig.ts
src/dataworker/index.ts
src/finalizer/index.ts
src/relayer/Relayer.ts
src/relayer/RelayerClientHelper.ts
src/relayer/index.ts

Each bot currently has different ways to toggle sim mode on its different functions. this is confusing and makes it hard to test.
Moreover, the InventoryClient has no way to simulate sending tokens across chains in sim mode, since its [sim mode flag](https://github.com/across-protocol/relayer/blob/37354395e9e77abd904171551be9019f43a1fde9/src/relayer/RelayerClientHelper.ts#L176) is the same flag that [activates its functionality](https://github.com/across-protocol/relayer/blob/37354395e9e77abd904171551be9019f43a1fde9/src/relayer/Relayer.ts#L167).

improve: Use sendingTransactionsEnabled flag for all bots to toggle sim mode

---

src/relayer/index.ts

This makes it possible to bi-directionally trace handovers from one relayer to another. At the moment it's only possible to do this forwards in time, because the existing relayer logs the runIdentifier of the subsequent relayer, but the subsequent relayer does not log the runIdentifier of the preceding relayer.

improve(relayer): Ensure bi-directional handover logging

---

package.json
yarn.lock

This is needed for the sepolia relayer to have the addresses for the testnet XYZ token.

chore: bump constants version

---

src/utils/TransactionUtils.ts

Because there are multiple providers for each chain, reduce the number of retries on transaction submission to speed-up the case where a transaction is actually unable to be submitted.
There are two layers of transaction submission at play - one at the quorum provider level, and one above. The quorum provider ensures that transactions are submitted successively to each provider until success or failure. For most chains, this means that transactions are submitted to 2 - 3 providers per retry. The upper layer then implements its own retry mechanism, currently at 2 retries. In cases where the transaction is ultimately unable to be submitted (i.e. underpriced replacement), this results in multiple futile submission attempts.

improve: Reduce transaction submission retries

---

src/adapter/l2Bridges/OpStackWethBridge.ts

Constructing an L2 to L1 WETH withdrawal takes two transactions: unwrap() WETH followed by bridgeETHTo(). The second will almost always fail simulation because the caller doesn't have enough WETH in their actual balance. We also can't batch simulate these transactions because of the requirement that msg.sender has the funds.

fix(OpStackWethBridge): bridgeEthTo() call should be able to fail simulaton following unwrap()

---

scripts/sendTokens.ts

This  script can be easily modified to allow for easy stuck-nonce fixes

improve(sendTokens.ts): Add options to send txn at nonce and with overridden gas prices

---

src/relayer/Relayer.ts

This asserted in production today, taking the relayer down. Warn about this condition instead.

improve(relayer): Warn on invalid repaymentChainId selection

---

src/clients/InventoryClient.ts
src/relayer/Relayer.ts
test/InventoryClient.RefundChain.ts

We were including mainnet as a possible repayment chain even when deposits were originated from a lite chain.
That was raising the error `Lite chain deposits must be filled on its origin chain`.

fix(InventoryClient): avoid hubChain as eligible refund chain when origin is a lite chain

---

src/common/ContractAddresses.ts
src/common/abi/ZkStackSharedBridge.json
src/finalizer/utils/zkSync.ts

this isn't required but its probably more future proof. We can still use the old mailbox to finalize

improve(finalizer): Finalize ZkStack withdrawals via SharedBridge 

---

src/adapter/bridges/ZKStackBridge.ts

The latest PR replaced the `ZKSyncWethBridge` with the `ZKStackWethBridge`. Since we [query hub pool events](https://github.com/across-protocol/relayer/blob/19865446407b590b99248b6f0d9350b0755da73f/src/adapter/bridges/ZKStackWethBridge.ts#L97) in this bridge, we need to provide that contract with an ethers provider the same way we did on the [previous bridge](https://github.com/across-protocol/relayer/blob/6df8eca644fc542c40e324f4345939857ea3007d/src/adapter/bridges/ZKSyncWethBridge.ts#L199).

fix: give a provider to the hub pool contract in ZkStackWethBridge

---

src/relayer/Relayer.ts

Cap the deposits under consideration to 25 per chain per loop. This is more than enough for 99% of use cases, but will reduce the worst-case impact in case of heavy deposit spam.

improve(relayer): Rate-limit deposits considered for fill

---

src/common/ContractAddresses.ts
src/utils/TokenUtils.ts

This updates information needed for the rebalancer. The rebalancer has only been tested with weth, but it functions as expected.
[L1](https://etherscan.io/tx/0xad9d37bcf961a5084ee96e1df9cd90b9885d7830b522074eebd915b0112057bf) [L2](https://explorer.lens.xyz/tx/0xc5b187049e7eb46ed7837414e5b3d56fbc8865aad585c40abb722db553107ee7)

improve: clean up Lens utility functions

---

package.json
yarn.lock

Need to have the correct `TATARA-USDC` address in the `TOKEN_SYMBOLS_MAP`

chore: bump testnet constants

---

package.json
yarn.lock

The finalizer has been throwing because of a new OpStack revert reason unhandled by the current `viem` version, which is patched [here](https://github.com/wevm/viem/commit/58db8b90d72983814664b12bd27bcd2bdf0f15f3)

improve(finalizer): Bump Viem version to handle OpStack error

---

package.json
yarn.lock

Some finalizations are stuck in `waiting-to-prove`, which should be resolved after bumping viem to include [this](https://github.com/wevm/viem/commit/33a01b96554759bb9fa60d3c4bfc1c2cd5974ddc).

improve: bump viem for finalizer

---

src/dataworker/README.md

Hi! I fixed a broken documentation link in `src/dataworker/README.md` that referenced UMIP-157 without the proper `.md` file extension. This ensures users can access the complete protocol specifications.

chore: updated broken link

---

src/dataworker/Dataworker.ts

This getLogs call caused a blowup on Blast this morning due to logs requests spanning > 10k blocks.

fix(dataworker): Avoid unbounded getLogs queries

---

scripts/sendTokens.ts

noticed a small issue where the variable was written as `withmaxFeePerGas` instead of `with maxFeePerGas`.
fixed.

fix: variable naming issue for withmaxFeePerGas

---

src/clients/InventoryClient.ts
src/relayer/Relayer.ts
src/relayer/index.ts
test/InventoryClient.InventoryRebalance.ts
test/InventoryClient.RefundChain.ts
test/mocks/MockAdapterManager.ts
test/mocks/MockBaseChainAdapter.ts

Currently the InventoryClient would not be able to compute allocation %'s correctly if an L2 token had a different decimal than the L1 token.
This PR normalizes the following L2 values to the same decimals as L1 so that the internal inventory calculations work:
- chain virtual balance
- cumulative virtual balance
- short falls when a deposit is outstanding for a chain
- repayment amounts (relevant for `determineRefundChain` for a Deposit)
- upcoming bundle refunds

improve(InventoryClient): Normalize l2 chain amounts to correct decimals if l2 token decimals differs from l1 token equivalent's

---

package.json
src/clients/InventoryClient.ts
src/clients/ProfitClient.ts
src/clients/bridges/AdapterManager.ts
src/dataworker/Dataworker.ts
src/dataworker/PoolRebalanceUtils.ts
src/finalizer/utils/linea/common.ts
src/finalizer/utils/linea/l1ToL2.ts
src/finalizer/utils/scroll.ts
src/monitor/Monitor.ts
src/relayer/Relayer.ts
src/scripts/validateRunningBalances.ts
src/utils/SDKUtils.ts
test/Dataworker.executePoolRebalanceUtils.ts
test/Dataworker.executePoolRebalances.ts
test/ProfitClient.ConsiderProfitability.ts
test/Relayer.UnfilledDeposits.ts
test/fixtures/Dataworker.Fixture.ts
test/mocks/MockHubPoolClient.ts
yarn.lock

- ProfitClient assumes in a few places that output amount is denominated in same precision as equivalent L1 token
- Monitor will not currently report balances of L2 tokens that are not mapped to L1 tokens, which I've left a TODO comment for
- PoolRebalance logs might not render correctly without adjusting for output token decimals
This PR also replaces use of functions in the SDK that might not resolve the correct `L1TokenInfo` object if different entries in TOKEN_SYMBOLS_MAP have the same mainnet token. These functions are removed in this SDK [pr](https://github.com/across-protocol/sdk/pull/981/files) and this PR uses the safer SDK functions that grabs the correct L2 chain's decimals

improve: Follow up fixes to use correct precision on output token amounts

---

src/relayer/Relayer.ts

The fill amount in USD check is meaningless if the output token does match the input token, so only do that check after we validate that the output token and input token are equivalent.

refactor: filter uncertain outputs after in-protocol swap checks

---

src/clients/InventoryClient.ts
src/clients/ProfitClient.ts
src/clients/TokenClient.ts
src/clients/bridges/AdapterManager.ts
src/dataworker/Dataworker.ts
src/monitor/Monitor.ts
src/relayer/Relayer.ts
src/utils/FillUtils.ts
src/utils/TokenUtils.ts
test/Dataworker.loadData.prefill.ts
test/InventoryClient.RefundChain.ts
test/Monitor.ts
test/Relayer.BasicFill.ts
test/Relayer.SlowFill.ts
test/Relayer.TokenShortfall.ts
test/Relayer.UnfilledDeposits.ts
test/TokenClient.Approval.ts
test/TokenClient.BalanceAlowance.ts
test/TokenClient.TokenShortfall.ts
test/fixtures/Dataworker.Fixture.ts
test/generic-adapters/AdapterManager.SendTokensCrossChain.ts
test/mocks/MockDataworker.ts
test/mocks/MockHubPoolClient.ts
test/mocks/MockInventoryClient.ts
test/mocks/MockTokenClient.ts

If a deposit's inputToken is not mapped to a PoolRebalanceRoute mapping then the fill must take repayment on origin chain, which is similar to a lite chain deposit.
There is a lot of logic in the Relayer and InventoryClient that deals with lite chain deposits that should therefore also apply to these "forced origin chain repayment" deposits.
Additionally, this PR replaces more token matching lookups via PoolRebalanceRoute events with looking up in the TOKEN_SYMBOLS_MAP constants file. This is required to make all bots be able to support deposited tokens that do not map to any L1 token via PoolRebalanceRoutes

feat: Treat lite chain deposits and forced origin chain repayments similarly

---

src/clients/ProfitClient.ts
src/monitor/Monitor.ts

See comment in PR explaining the fix:
```
// WETH is the symbol that `getL1TokenInfo()` will return for WETH on Mainnet but ETH is what
// it will return for a non-Mainnet chain, so unify the symbols. This is because TOKEN_SYMBOLS_MAP
// defines both an ETH and WETH mapping that both reference "WETH" addresses but the ETH mapping comes first.
```
The issue stems from 1b0bed4dae8303b93bd43865d6f379e8d22657e4 where we now load token infos from the TOKEN_SYMBOLS_MAP for all L2 tokens or via the HubPoolClient for L1 tokens. This is necessary because L2 tokens might share the same L1 token despite having different symbols and decimals so we opt to read symbol and decimals for L1 tokens directly from on-chain. This does mean that whereas an L2 token address can load the "ETH" mapping from …

fix(Monitor): Report should unify ETH balances under WETH

---

src/adapter/bridges/ZKStackBridge.ts

We are double counting Hub->Spoke transfers because of the way the monitor works.
The `BaseChainAdapter` queries L1 and L2 events for each address passed into it by setting the `fromAddress` and `toAddress` [equal to each other](https://github.com/across-protocol/relayer/blob/0e8b9c143a477d409191c72ccfb8cf9314d03a65/src/adapter/BaseChainAdapter.ts#L356). This works great when tracking EOA transfers but not when sending transfers from Hub to Spoke.
Therefore, each adapter must handle this case and not double count such transfers. The ZkStackBridge is correctly tracking when the `from` and `to` addresses are set to the SpokePool, but not when they are set to the HubPool. When the `from` and `to` address is set to the HubPool, then `queryL1BridgeInitiationEvents` is returning some events but …

fix(ZkStackBridge): Fix getOutstandingTransfers

---

src/dataworker/Dataworker.ts
src/finalizer/utils/linea/common.ts
src/finalizer/utils/linea/l1ToL2.ts
src/finalizer/utils/scroll.ts

follow up to https://github.com/across-protocol/relayer/pull/2209/files

improve: Replace hubPoolClient.getL1TokenInfo calls where input is not a guaranteed LP token

---

src/clients/InventoryClient.ts
src/clients/bridges/AdapterManager.ts
src/dataworker/Dataworker.ts
src/finalizer/utils/linea/common.ts
src/finalizer/utils/linea/l1ToL2.ts
src/finalizer/utils/scroll.ts
src/utils/SDKUtils.ts

We will need to rebalance tokens which are not enabled for liquidity provision, so the inventory client and adapter manager should not use the hub pool client to resolve L1 token information. They should instead use `TOKEN_SYMBOLS_MAP.` This is safe since all calls use an L1 token as input, and `getTokenInfo` has a specific block of code [here](https://github.com/across-protocol/sdk/blob/4b856bdd2cf4020ea1dde286048afe83d2d1648a/src/utils/TokenUtils.ts#L114) which ensures that if there are many L1 definitions for a token, we will use the remapped symbol when resolving token information.

improve: use token symbols map over hub pool client for rebalancing

---

src/relayer/RelayerConfig.ts

This enabled the relayer to filter out unsupported tokens from a single superset inventory config.

improve(RelayerConfig): Filter inventory config by enabled tokens

---

src/adapter/bridges/BinanceCEXBridge.ts
src/common/Constants.ts
src/finalizer/utils/binance/l1ToL2.ts

The BaseChainAdapter will not get outstanding transfers if the L1Token to query is not in `SUPPORTED_TOKENS` (see `SUPPORTED_TOKENS`[here](https://github.com/across-protocol/relayer/blob/8dc44a1600d51920e8bfa5eef61d6d172743bcf4/src/adapter/BaseChainAdapter.ts#L107 ). Our `SUPPORTED_TOKENS` had a `BNB` [entry](https://github.com/across-protocol/relayer/blob/8dc44a1600d51920e8bfa5eef61d6d172743bcf4/src/common/Constants.ts#L332) which was resolving to `WBNB` when fetching its token symbol, meaning we were not getting outstanding transfers for BNB rebalances properly. From Binance's perspective, these are deposits of BNB, not WBNB, so both the adapter and the finalizer must re-map this to BNB.

fix: re-map BNB in the finalizer, not in the adapter

---

src/relayer/Relayer.ts

We are trying to check if a token which has no pool rebalance route has an LP fee, which it won't ever have due to changes made in the inventory client.

fix: do not evaluate destination profitability if token has no route

---

src/finalizer/utils/binance/l1ToL2.ts
src/finalizer/utils/binance/l2ToL1.ts

In practice this log happens often since there are diffs between deposit amounts and withdrawal amounts due to withdrawal fees.

chore: reduce bsc finalizer log level

---

package.json
test/DataworkerUtils.ts
yarn.lock

If a chain has no running balances but has refunds, then we should still produce an empty pool rebalance leaf for it

fix(Dataworker): Produce leaves for chains with no running balances

---

src/finalizer/utils/binance/l1ToL2.ts

This was an artifact of a previous commit used for testing that was mistakenly kept in.

chore: remove test override in finalizer

---

src/monitor/Monitor.ts
src/monitor/MonitorConfig.ts
test/Monitor.ts

1. L2 token balances are all converted to L1 token decimals to normalize reporting cross chain relayer balances
2. Allows Monitor constructor to specify additional L1 tokens to report cross chain relayer balances for

fix(Monitor): Convert decimals properly for L2 token balances and support additional L1 token reporting

---

src/finalizer/index.ts

We should rely on the multicaller client's transaction simulation logic rather than directly call the transaction client to simulate finalization txns invidually. This code is leftover from legacy code before we used to submit finalization txns to the multicaller client.
Replaces https://github.com/across-protocol/relayer/pull/2218

feat(finalizer): Remove individual txn client simulation

---

src/adapter/bridges/BinanceCEXBridge.ts
src/adapter/bridges/BinanceCEXNativeBridge.ts
src/adapter/l2Bridges/BinanceCEXBridge.ts
src/finalizer/utils/binance/l1ToL2.ts
src/finalizer/utils/binance/l2ToL1.ts
src/utils/BinanceUtils.ts
src/utils/CLIUtils.ts
src/utils/NetworkUtils.ts
src/utils/index.ts

We should be able to retrieve Binance secret keys from GCKMS and not the environment.
Also, in order to avoid being rate-limited by the Binance API, we should only query it when it makes sense to do so, i.e. when the address we are querying for is an EOA and not a contract (since the API should never be used to transfer contract funds, anyways).

feat: retrieve binance keys from gckms and avoid unnecesary binance queries

---

src/adapter/bridges/UsdcCCTPBridge.ts

Without this, we think we have a much larger amount of outstanding transfers for a given chain than we do in reality, since each CCTP bridge thinks that _any_ rebalance is a rebalance to their l2 network.

fix: filter CCTP initiation events by destination domain

---

src/finalizer/utils/opStack.ts

https://github.com/across-protocol/relayer/commit/eb6024a812e2d5b00b19d7a872f28ba19e9959b5 unintentionally broke the OPStack finalizer by removing the TokensBridged event query from discovering withdrawals to finalize. This is because certain tokens do not go through the standard OP Stack bridge, like USDC.e on WorldChain, Sonieum and Ink, and DAI and SNX on Optimism.

fix(OpStackFinalizer): Add back TokensBridged query to catch non standard withdrawals

---

src/common/abi/SP1Helios.json
src/finalizer/utils/helios.ts
src/interfaces/Helios.ts
src/interfaces/ZkApi.ts
src/utils/ZkApiUtils.ts

If SP1Helios.head is left unupdated for > 1 WEEK, the contract gets bricked. We let 24hrs go by with no updates, but after then we call .update() even if there are no new messages to finalize (by requesting a new ZK proof with empty storage slots to prove).
This turned out to be a large refactor. IMO, the current flow is nice though:
we identify required HeliosActions
try to enrich them with ZK proof data
for all the actions that are "ready", generate on-chain txs
Closes ACX-4075

improve: add periodic KeepAlive messages for SP1Helios

---

src/finalizer/index.ts

This reverts commit 54ff57e91d167af51485bf83ed6809c23a323ddc.
The key revert here is to avoid the bundling of transactions before they're being supplied to the MultiCallerClient, because this prevents the MultiCallerClient from filtering out failing transactions and allows a single bad transaction to spoil the bundle.
The rationale for reverting this change is that there's currently an impossible-to-execute message awaiting finalization on Linea. Since the message can't be executed on Linea (due to SpokePool v4 upgrade) it can never be finalized. The only (apparent) way to be rid of it is to wait for it to drop out of the finalizer lookback. Without this, the sweeper finalizer would continue to error for the next ~15 days (due to its long lookback configuration).

Revert "Update index.ts (#2229)"

---

src/utils/CCTPUtils.ts

When getting an attestation from Circle's api by index [here](https://github.com/across-protocol/relayer/blob/6fbe3eaf6742ff5b23c52cf9b4248e949fbc2f53/src/utils/CCTPUtils.ts#L300), we didn't account for the fact that one message can contain both L1 and L2 attestations.
As a result, our `count` variable only knows about v2 messages, but trying to get an attestation by index from an array of both v1 and v2 messages.
Solution: filter L1 messages from an array.
✅ Tested locally, fixes finalizer error and simulates a batch on Linea successfully.

fix: CCTP v2 attestation index

---

src/finalizer/utils/helios.ts

Don't page if we receive 'is not divisible by 32 error' from ZK API.

improve: paging logic for helios finalizer

---

src/clients/InventoryClient.ts
src/utils/FillUtils.ts
test/InventoryClient.RefundChain.ts

The current IM logic will return zero possible repayment chains if the deposit forces origin chain repayment and the origin chain is over allocated. This lets us avoid accruing too much balance on these chains, typically lite chains, that force origin chain repayment.
However, BSC Is now included as one of these chains since it does force origin chain repayment. However, BSC is relatively easy to rebalance tokens out of--so we shouldn't impose the same constraints.
This PR therefore allows the IM to return the origin chain as a possible repayment chain if the origin chain is BSC.

improve(InventoryClient): Don't skip BSC deposits

---

src/utils/AddressUtils.ts
src/utils/SDKUtils.ts

Remove redundant util function compareAddresses from relayer, and start using the same function from SDK.

Chore: Remove compareAddresses function from relayer and start using one from SDK

---

src/libexec/RelayerSpokePoolListener.ts
src/libexec/RelayerSpokePoolListenerHTTPS.ts
src/libexec/util/ipc.ts

I'd previously (mis)understood that process.send() should be actively set undefined if the IPC has been closed, but this is not the documented behaviour, nor what is observed in practice.
I think this was previously OK when ethers websocket transports were used, but viem seems to suppress the exception so that the process continues to run despite being an orphan.

improve(relayer): Catch IPC failures

---

src/common/Constants.ts

Mode enabled fraud proofs but OP SDK doesn't support it yet so need to manually inject address

fix(Finalizer): Add DisputeGameFactory entry for Mode

---

src/dataworker/Dataworker.ts
src/dataworker/index.ts

This isn't used in practice and it's hard to see a concrete use case for it. Drop it to remove a level of indentation.

refactor: Drop loop support in Dataworker

---

src/monitor/MonitorConfig.ts

If `binanceWithdrwalAlertThreshold` and `binanceWithdrwalWarnThreshold` are not set in bot-configs, default value should be `1` so it doesn't alert every time.

fix: Change default Binance Withdrawal Alert Threshold

---

src/common/abi/MinimalERC20.json

This fixes an error in the rebalancer
```
TypeError: erc20.allowance is not a function
at OpStackUSDCBridge.constructWithdrawToL1Txns (/across-relayer/dist/src/adapter/l2Bridges/OpStackUSDCBridge.js:30:39)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async BaseChainAdapter.withdrawTokenFromL2 (/across-relayer/dist/src/adapter/BaseChainAdapter.js:204:26)
at async /across-relayer/dist/src/clients/InventoryClient.js:1064:32
at async Promise.all (index 0)
```

fix: add `allowance` to MinimalERC20 json

---

src/finalizer/index.ts

Identified after Dylan queried abnormally high USDC utilization.

fix(finalizer): Enable CCTP withdrawals on World Chain

---

test/InventoryClient.InventoryRebalance.ts
test/mocks/MockAdapterManager.ts

- Use EvmAddress.from() where an EvmAddress instance is required.
- Prefer Address.toNative().
- Update mocked AdapterManager for incomplete use of Address type.
- Drop use of toBytes32().

fix(test): Address type oopses in InventoryClient test

---

src/finalizer/index.ts
src/finalizer/types.ts
src/finalizer/utils/arbStack.ts
src/finalizer/utils/binance.ts
src/finalizer/utils/cctp/l1ToL2.ts
src/finalizer/utils/cctp/l2ToL1.ts
src/finalizer/utils/helios.ts
src/finalizer/utils/linea/l1ToL2.ts
src/finalizer/utils/opStack.ts
src/utils/CCTPUtils.ts

We need to be able to distinguish between svm and evm addresses in the finalizer.

improve: use `Address` in the finalizer

---

src/clients/BalanceAllocator.ts
src/clients/TokenClient.ts
src/dataworker/Dataworker.ts
src/utils/TokenUtils.ts

We need the balance allocator to work for relayer refund leaf tokens on Solana. A natural way to get this to work is to reuse the TokenClient's logic.

fix: query svm balance in BalanceAllocator

---

src/dataworker/DataworkerConfig.ts
src/dataworker/index.ts

There are cases where the proposer & executor are unable to do anthing. This can be detected well in advance of doing a HubPoolClient update, which is otherwise a quite heavy procedure.

refactor Permit early exit in HubPool proposer/executor

---

src/clients/ProfitClient.ts

Can be used when there is a gas spike on a specific chain. Is lower in precedence than the more specific `routeKey` but higher than more general `tokenKey`

feat(ProfitClient): Allow Relayer to set min relayer fee just for single destination chain

---

src/clients/ProfitClient.ts

A common use case when debugging is to find out how the profitability is calculated for a specific destination chain since the destination chain's gas costs are a big factor in the calculation.
This PR makes it easier to search for a specific chain ID

improve(ProfitClient): Add destinationChainId into `message` when printing out profitability

---

src/adapter/l2Bridges/ArbitrumOrbitBridge.ts
src/adapter/l2Bridges/OpStackBridge.ts
src/adapter/l2Bridges/OpStackUSDCBridge.ts
src/adapter/l2Bridges/OpStackWethBridge.ts
src/adapter/l2Bridges/UsdcCCTPBridge.ts
src/adapter/l2Bridges/index.ts
src/clients/AcrossAPIClient.ts
src/clients/InventoryClient.ts
src/common/Constants.ts

This will unlock more USDC capital efficiency. The finalizer doesn't need any changes to support finalizing these USDC withdrawals.
1. [Base withdrawal](https://basescan.org/tx/0x82ced92aff24d903256ca43c79f6a999ee01265e41bd0eccb5dfa4478732dae4#eventlog)
```
2025-07-17 21:18:28 [debug]: {
"at": "InventoryClient",
"message": "Evaluated withdrawing excess balance on Base for token USDC: HAS EXCESS ✅",
"l1Token": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
"l2Token": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
"cumulativeBalance": "755.10",
"currentAllocPct": "0.400835260824695875",
"excessWithdrawThresholdPct": "0.285",
"targetPct": "0.2",
"withdrawalParams": {
"withdrawPct": "0.200835260824695875",
"desiredWithdrawalAmount": "151.65"
},
"bot-identifier": "nick-local",
"run-identifier": …
```

feat(InventoryClient): Add ability to withdraw USDC over CCTP from L2 to L1

---

src/dataworker/DataworkerClientHelper.ts
src/monitor/Monitor.ts
src/monitor/MonitorClientHelper.ts

Two optimizations, the first is a bigger help:
1) Limit HubPoolClient's default event lookback to 30 days, unless the `dataworkerFastLookbackCount` is set very high in which case default to the current settings which sets this to the genesis block. Apply similar settings to the Monitor
2) Remove RootBundleCancelled event query, this is basically unused except by the monitor which we also don't really need

improve(HubPoolClient): Optimize update speed

---

src/dataworker/Dataworker.ts

I believe we cannot handle logging encoded accounts in some environments, so instead of logging the entire account, just log the address.

chore: do not log encoded accounts

---

src/dataworker/Dataworker.ts

This PR does two things:
- Fixes an instance where we still log an encoded account
- Moves the `executorIgnoreChains` check to the beginning of `executeRelayerRefundLeaves` and `executeSlowRelayLeaves` so that we don't spend time constructing those leaves if we aren't going to enqueue them.

improve: refactor executor early exit and logs

---

src/dataworker/Dataworker.ts

It's possible that the time between the ALT to being confirmed to the time of the extend ALT transaction is less than the time it takes for a new solana block to be added, so wait after creating the ALT to guarantee that the extend transaction will not fail in simulation. 
For all ALT transactions, we need to wait a block for them to "activate": https://solana.com/developers/courses/program-optimization/lookup-tables#6-modify-main-to-use-lookup-tables

fix: wait for a block after creation of ALT

---

src/clients/InventoryClient.ts
src/relayer/Relayer.ts
src/relayer/index.ts

Prepare bundleRefundsPromise on init of InventoryClient. This will speed up the relayers bcs, during the relayer handover, it will load bundleRefunds into a relayer so the relayer doesn't need to wait for it when it wants to fill the deposit.

feat: Prepare bundleRefundsPromise on init of InventoryClient

---

src/finalizer/utils/binance.ts

Since this is no longer in a Promise.all, we need to `continue` and not `return`.

fix: avoid exiting early on binance finalizer

---

src/clients/ProfitClient.ts

We are using cached gas prices for relays with no messages. This doesn't work for Solana since we also need to know whether the recipient has an ATA.

fix: simulate all solana fills

---

src/clients/ProfitClient.ts
src/relayer/RelayerClientHelper.ts
test/ProfitClient.ConsiderProfitability.ts
test/ProfitClient.PriceRetrieval.ts
test/mocks/MockProfitClient.ts

This change was added in this PR https://github.com/across-protocol/relayer/pull/2439, but is needed now since we no longer cache gas prices for empty message relays destined for Solana.

fix: distinguish solana/evm relayers in profit client

---

src/dataworker/Dataworker.ts

**Logger tag fixes**:
- `Dataworke#propose` → `Dataworker#propose`
- `Dataworke#validate` → `Dataworker#validate`
- `Dataworke#validater` → `Dataworker#validate`
- `Dataworke#executeSlowRelayLeaves` → `Dataworker#executeSlowRelayLeaves`
- `Dataworke#executeRelayerRefundLeaves` → `Dataworker#executeRelayerRefundLeaves`
**Comment path correction**:
- `validateRunningbalances.ts` → `validateRunningBalances.ts`

chore(dataworker): fix logger tag typos and correct comment path

---

src/scripts/validateRunningBalances.ts
src/utils/CCTPUtils.ts

Fix a comment typo and make an assertion message accurately reflect its boundary condition. No functional changes.
- Correct “auxilary” → “auxiliary”
- Update assertion message to match the actual check PAGE_SIZE <= bundlesToValidate:
from “PAGE_SIZE must be less than BUNDLES_COUNT” to “PAGE_SIZE must be less than or equal to BUNDLES_COUNT”.

chore: Fix typo and assertion text

---

src/clients/InventoryClient.ts
src/common/Constants.ts

Avoid taking repayment on 7 day withdrawal chains where a fast rebalance route is available for the given token (i.e. USDC on CCTP chains, USDT on OFT chains). This increases the chance of taking repayment on a chain where it would actually make a difference for HubPool utilisation.
Additionally, add Unichain as a slow withdrawal chain. It has a lot of activity so it's generally fine to prioritise taking repayments there.

improve(relayer): Skip benevolent repayment for fast routes

---

src/monitor/Monitor.ts

This should make the reporter stop throwing when we need to refund an unknown token.

fix: ignore refunds which do not relate to the monitored relayer

---

src/monitor/Monitor.ts

Open question: There's no way to correlate an EVM address with an SVM address, so we can either choose to report the two addresses as completely separate addresses (what this PR does) or we can update the config to have `monitoredRelayers` contain both an svm and evm aspect, and then combine their inventories. 
This PR can be updated to the second part if there is a demand for that.

improve: report balances of svm relayers

---

src/scripts/validateRootBundle.ts

There is an implicit assumption in `validateRootBundle` that the root bundle being validated has a mainnet bundle end block which is strictly after the last root bundle was executed. This is obviously not the case when we create a root bundle optimistically (that is, under the assumption that the pending root bundle is valid and will pass liveness). 
The main thing to keep in mind is that when checking a bundle, **latestMainnetBlock is set to the bundle to validate's bundleEndBlock** in the validate root bundle script. The block ranges we pass in to `dataworker.validateRootBundle` requires that the start block corresponds to a bundle's start block (see [this derivation](https://github.com/across-protocol/relayer/blob/0e9a7083d12b812d20d9162255093cd4be98cc5b/src/dataworker/Dataworker.ts#L87 …

fix: validateRootBundle script incorrectly assumes proposal is not optimistic

---

src/libexec/RelayerSpokePoolListener.ts

The existing hard-stop implementation might be too strict and causing fragility in the relayer. viem is OK to reconnect in the background and continue listening for new blocks. This doesn't affect re-org detection since that's based on the individual events; in fact it allows more time for a re-org to be detected.
This change is prompted by an odd pairing of zkSync & QuickNode, which tends to cause a lot of JSON parsing errors to be thrown. Unfortunately it's unclear exactly which response is causing the error, investigation ongoing.

improve(relayer): Don't auto-bail on block error

---

src/common/abi/ZkStackUSDCBridge.json
src/finalizer/utils/zkSync.ts

USDC withdrawals require special handling because the L2 USDC bridge doesn't have an `l1SharedBridge` method but instead has a `l1USDCBridge` method. The rest of the process is the same.
This PR keeps the `zksync` finalizer adapter very light weight but we should replace it eventually with a bump to `zksync-ethers>=6.20.0`

fix(zkstack-finalizer): Add special case for USDC withdrawals

---

src/relayer/index.ts

Observed this morning on Polygon - the relayer refused to start due to Polygon node issues. Try to proceed to active state even though one or more chains did not come up successfully.

improve(relayer): Proceed to active state despite degraded chains

---

src/caching/RedisCache.ts
src/clients/AcrossSwapApiClient.ts
src/clients/index.ts
src/monitor/Monitor.ts
src/utils/RedisUtils.ts
src/utils/TransactionUtils.ts

Eventually we can move the refiller logic out of the Monitor but I wanted to test this PoC out in the Monitor without adding too much code. Assuming the SwapClient works well we can productionize it into a separate bot in a follow up PR

feat(Monitor): Incorporate SwapHelper into Monitor.refiller

---

src/relayer/index.ts

Flushing TokenClient state before considering withdrawals means that the rebalancer assumes that there are no deposits awaiting to be filled. This can cause the rebalancer to pull back tokens that were intended to be used by the relayer to fill shortfalls. The rebalancer should instead factor in any simulated fills that were made as part of identifying shortfalls.

fix(rebalancer): Don't flush TokenClient state prematurely

---

src/clients/InventoryClient.ts
test/InventoryClient.RefundChain.ts
test/Relayer.BasicFill.ts

Downside:
- initialize()-ing the BundleDataApproxClient will be slower because it is now fetching refunds over all L1 tokens, regardless if the user sets a smaller subset in the inventory config
Upside:
- Relayer will not complain if a token is enabled in RELAYED_SUPPORTED_TOKENS but not in the INVENTORY_CONFIG because the refund data will now be available in the BundleDataApproxClient

improve(InventoryClient): Initialize BundleDataApproxClient with all possible L1 tokens

---

src/common/Constants.ts
src/utils/BinanceUtils.ts

This can be merged with no immediate effect since in order for withdrawals to happen, withdrawal parameters need to be set in the inventory config.

chore: define more CEX bridge routes

---

src/utils/RedisUtils.ts

If connecting to Redis fails constantly, it will loop until the process is killed. We should throw error after N retries.

fix: Fail bots after Redis Connection Error

---

src/adapter/bridges/UsdcCCTPBridge.ts
src/adapter/l2Bridges/UsdcCCTPBridge.ts
src/clients/InventoryClient.ts
test/InventoryClient.InventoryRebalance.ts

I think we can go over the max transfer size when we want to rebalance > 1M using fast mode.

fix: cap max CCTP transfer amount at 1M

---

src/finalizer/utils/binance.ts

We sometimes run into issues when timing of withdrawals cause pending deposits to be credited to the binance hot wallet but not finalized/ready to withdraw. This causes the finalizer to crash since we then attempt to withdraw this credited amount (as currently we are only aware of our balance). 
This PR makes the finalizer aware of the credited, but not finalized deposits, and will check whether the amount it wants to finalize falls within the finalized balance amounts (and does not overlap with the credited balance).

improve: do not withdraw credited balances from binance
